(define (problem menuext3b-tc2)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carxofa crema_espinacs raviolis_ricotta tallarins_carbonara truita_potatge verdures_amb_salsa verdures_a_la_planxa crema_de_carbassa brocoli_allada sopa_de_marisc - primer
crema_taronja crema_de_xocolata bacalla_amb_tomaquet parrillada_verdures crema_de_limon truita_verdures crema_catalana sopa_de_galets tataki_verdures crema_avellana - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible raviolis_ricotta crema_catalana)
    (incompatible tallarins_carbonara crema_de_limon)
    (incompatible verdures_a_la_planxa sopa_de_galets)
    (incompatible tallarins_carbonara crema_de_xocolata)
    (incompatible crema_de_carxofa bacalla_amb_tomaquet)
    (incompatible brocoli_allada sopa_de_galets)
    (incompatible truita_potatge bacalla_amb_tomaquet)
    (incompatible tallarins_carbonara crema_catalana)
    (platTipus crema_de_carxofa crema)
    (platTipus crema_espinacs crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus tallarins_carbonara pasta)
    (platTipus truita_potatge llegums)
    (platTipus verdures_amb_salsa verdures)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus brocoli_allada verdures)
    (platTipus sopa_de_marisc sopa)
    (platTipus crema_taronja crema)
    (platTipus crema_de_xocolata crema)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus parrillada_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus truita_verdures verdures)
    (platTipus crema_catalana crema)
    (platTipus sopa_de_galets sopa)
    (platTipus tataki_verdures verdures)
    (platTipus crema_avellana crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori crema_taronja dimecres)
    (platObligatori crema_de_xocolata divendres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )