(define (problem menuext3b-tc1)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
macarrons_forn sopa_verdures verdures_a_la_planxa escalivada_verdures cigrons_saltejats amanida_de_tomaquet truita_potatge sopa_de_marisc crema_de_bolets amanida_asiatica - primer
bacalla_amb_tomate hamburguesa_mongeta crema_de_limon cuixa_ànec crema_taronja truita_de_llenties wok_verdures xai_rostit salmo_grillat parrillada_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_asiatica cuixa_ànec)
    (incompatible amanida_asiatica salmo_grillat)
    (incompatible escalivada_verdures cuixa_ànec)
    (incompatible sopa_de_marisc parrillada_verdures)
    (incompatible cigrons_saltejats bacalla_amb_tomate)
    (incompatible macarrons_forn crema_taronja)
    (incompatible amanida_de_tomaquet bacalla_amb_tomate)
    (incompatible cigrons_saltejats salmo_grillat)
    (platTipus macarrons_forn pasta)
    (platTipus sopa_verdures sopa)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus escalivada_verdures verdures)
    (platTipus cigrons_saltejats llegums)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus truita_potatge llegums)
    (platTipus sopa_de_marisc sopa)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_asiatica amanida)
    (platTipus bacalla_amb_tomate peix)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus crema_de_limon crema)
    (platTipus cuixa_ànec carn)
    (platTipus crema_taronja crema)
    (platTipus truita_de_llenties llegums)
    (platTipus wok_verdures verdures)
    (platTipus xai_rostit carn)
    (platTipus salmo_grillat peix)
    (platTipus parrillada_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori cigrons_saltejats dimecres)
    (platObligatori crema_de_limon dijous)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )