(define (problem menuext3b-tc2)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
truita_potatge amanida_de_tomaquet amanida_asiatica sopa_miso crema_de_carbassa verdures_amb_salsa penne_arrabiata sopa_de_cigrons amanida_quinoa verdures_a_la_planxa - primer
llenguado_amb_lima crema_avellana sopa_de_galets sopa_de_pedra turbot_planxa crema_catalana crema_de_limon truita_verdures tataki_verdures estofat_cigrons - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa turbot_planxa)
    (incompatible amanida_de_tomaquet llenguado_amb_lima)
    (incompatible verdures_amb_salsa sopa_de_galets)
    (incompatible sopa_de_cigrons truita_verdures)
    (incompatible sopa_miso tataki_verdures)
    (incompatible penne_arrabiata crema_de_limon)
    (incompatible truita_potatge turbot_planxa)
    (incompatible verdures_amb_salsa sopa_de_pedra)
    (platTipus truita_potatge llegums)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus amanida_asiatica amanida)
    (platTipus sopa_miso sopa)
    (platTipus crema_de_carbassa crema)
    (platTipus verdures_amb_salsa verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus sopa_de_cigrons sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus llenguado_amb_lima peix)
    (platTipus crema_avellana crema)
    (platTipus sopa_de_galets sopa)
    (platTipus sopa_de_pedra sopa)
    (platTipus turbot_planxa peix)
    (platTipus crema_catalana crema)
    (platTipus crema_de_limon crema)
    (platTipus truita_verdures verdures)
    (platTipus tataki_verdures verdures)
    (platTipus estofat_cigrons llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori truita_potatge dimecres)
    (platObligatori verdures_a_la_planxa dilluns)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )