(define (problem menuext3b-tc3)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_quinoa brocoli_allada hummus amanida_catalana gnocchi_pesto macarrons_forn amanida_fasols raviolis_ricotta crema_de_bolets truita_potatge - primer
botifarra_a_la_planxa tataki_verdures salmo_grillat sopa_de_peix sopa_ajo xai_rostit filet_porc turbot_planxa crema_catalana orata_forno - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_bolets orata_forno)
    (incompatible brocoli_allada sopa_de_peix)
    (incompatible raviolis_ricotta crema_catalana)
    (incompatible amanida_fasols orata_forno)
    (incompatible truita_potatge turbot_planxa)
    (incompatible amanida_quinoa filet_porc)
    (incompatible macarrons_forn crema_catalana)
    (incompatible crema_de_bolets botifarra_a_la_planxa)
    (platTipus amanida_quinoa amanida)
    (platTipus brocoli_allada verdures)
    (platTipus hummus llegums)
    (platTipus amanida_catalana amanida)
    (platTipus gnocchi_pesto pasta)
    (platTipus macarrons_forn pasta)
    (platTipus amanida_fasols llegums)
    (platTipus raviolis_ricotta pasta)
    (platTipus crema_de_bolets crema)
    (platTipus truita_potatge llegums)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus tataki_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_ajo sopa)
    (platTipus xai_rostit carn)
    (platTipus filet_porc carn)
    (platTipus turbot_planxa peix)
    (platTipus crema_catalana crema)
    (platTipus orata_forno peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori truita_potatge dimecres)
    (platObligatori filet_porc divendres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )