(define (problem menuext3b-tc4)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_asiatica raviolis_ricotta macarrons_forn amanida_de_tomaquet crema_espinacs fajitas_verdures verdures_a_la_planxa amanida_quinoa sopa_de_cigrons cigrons_saltejats - primer
truita_de_llenties crema_avellana wok_verdures salmo_grillat faves_estofades xai_rostit sopa_de_pedra parrillada_verdures cuixa_anec sopa_ceba - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_a_la_planxa sopa_de_pedra)
    (incompatible sopa_de_cigrons wok_verdures)
    (incompatible amanida_asiatica xai_rostit)
    (incompatible fajitas_verdures sopa_ceba)
    (incompatible crema_espinacs salmo_grillat)
    (incompatible fajitas_verdures cuixa_anec)
    (incompatible cigrons_saltejats salmo_grillat)
    (incompatible amanida_de_tomaquet xai_rostit)
    (platTipus amanida_asiatica amanida)
    (platTipus raviolis_ricotta pasta)
    (platTipus macarrons_forn pasta)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus crema_espinacs crema)
    (platTipus fajitas_verdures verdures)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus amanida_quinoa amanida)
    (platTipus sopa_de_cigrons sopa)
    (platTipus cigrons_saltejats llegums)
    (platTipus truita_de_llenties llegums)
    (platTipus crema_avellana crema)
    (platTipus wok_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus faves_estofades llegums)
    (platTipus xai_rostit carn)
    (platTipus sopa_de_pedra sopa)
    (platTipus parrillada_verdures verdures)
    (platTipus cuixa_anec carn)
    (platTipus sopa_ceba sopa)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori parrillada_verdures dijous)
    (platObligatori cuixa_anec dimecres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )