(define (problem menuext3b-tc5)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_verdures gnocchi_pesto verdures_amb_salsa sopa_de_cigrons amanida_catalana amanida_quinoa sopa_de_peix sopa_de_marisc estofat_llenties crema_de_carxofa - primer
filet_porc hamburguesa_mongeta pollastre_a_la_planxa estofat_soja sopa_ajo sopa_ceba xai_rostit crema_taronja tataki_verdures crema_de_limon - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_quinoa xai_rostit)
    (incompatible amanida_catalana pollastre_a_la_planxa)
    (incompatible amanida_quinoa pollastre_a_la_planxa)
    (incompatible verdures_amb_salsa filet_porc)
    (incompatible amanida_catalana xai_rostit)
    (incompatible verdures_amb_salsa sopa_ajo)
    (incompatible verdures_amb_salsa pollastre_a_la_planxa)
    (incompatible gnocchi_pesto crema_de_limon)
    (platTipus sopa_verdures sopa)
    (platTipus gnocchi_pesto pasta)
    (platTipus verdures_amb_salsa verdures)
    (platTipus sopa_de_cigrons sopa)
    (platTipus amanida_catalana amanida)
    (platTipus amanida_quinoa amanida)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_de_marisc sopa)
    (platTipus estofat_llenties llegums)
    (platTipus crema_de_carxofa crema)
    (platTipus filet_porc carn)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus estofat_soja llegums)
    (platTipus sopa_ajo sopa)
    (platTipus sopa_ceba sopa)
    (platTipus xai_rostit carn)
    (platTipus crema_taronja crema)
    (platTipus tataki_verdures verdures)
    (platTipus crema_de_limon crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_de_peix dimecres)
    (platObligatori sopa_ceba dijous)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )