(define (problem menuext3b-tc2)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_espinacs raviolis_ricotta brocoli_allada estofat_llenties verdures_a_la_planxa truita_potatge amanida_catalana hummus amanida_quinoa cigrons_saltejats - primer
cuixa_anec sopa_de_peix sopa_de_pedra truita_verdures crema_de_limon xai_rostit turbot_planxa faves_estofades bacalla_amb_tomaquet filet_porc - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible truita_potatge bacalla_amb_tomaquet)
    (incompatible hummus turbot_planxa)
    (incompatible hummus bacalla_amb_tomaquet)
    (incompatible estofat_llenties bacalla_amb_tomaquet)
    (incompatible verdures_a_la_planxa cuixa_anec)
    (incompatible verdures_a_la_planxa sopa_de_pedra)
    (incompatible brocoli_allada sopa_de_pedra)
    (incompatible estofat_llenties turbot_planxa)
    (platTipus crema_espinacs crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus brocoli_allada verdures)
    (platTipus estofat_llenties llegums)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus truita_potatge llegums)
    (platTipus amanida_catalana amanida)
    (platTipus hummus llegums)
    (platTipus amanida_quinoa amanida)
    (platTipus cigrons_saltejats llegums)
    (platTipus cuixa_anec carn)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_de_pedra sopa)
    (platTipus truita_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus xai_rostit carn)
    (platTipus turbot_planxa peix)
    (platTipus faves_estofades llegums)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus filet_porc carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori cigrons_saltejats dimarts)
    (platObligatori sopa_de_pedra divendres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )