(define (problem menuext3b-tc1)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
hummus sopa_de_cigrons verdures_amb_salsa sopa_de_peix crema_de_bolets amanida_asiatica penne_arrabiata amanida_quinoa crema_de_carabasso sopa_miso - primer
estofat_cigrons truita_de_llenties cuixa_anec sopa_ceba filet_porc crema_de_xocolata sopa_de_peix pollastre_a_la_planxa parrillada_verdures xai_rostit - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_amb_salsa cuixa_anec)
    (incompatible sopa_de_peix parrillada_verdures)
    (incompatible crema_de_carabasso cuixa_anec)
    (incompatible crema_de_carabasso xai_rostit)
    (incompatible crema_de_carabasso pollastre_a_la_planxa)
    (incompatible amanida_quinoa xai_rostit)
    (incompatible verdures_amb_salsa filet_porc)
    (incompatible crema_de_bolets filet_porc)
    (platTipus hummus llegums)
    (platTipus sopa_de_cigrons sopa)
    (platTipus verdures_amb_salsa verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_asiatica amanida)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_quinoa amanida)
    (platTipus crema_de_carabasso crema)
    (platTipus sopa_miso sopa)
    (platTipus estofat_cigrons llegums)
    (platTipus truita_de_llenties llegums)
    (platTipus cuixa_anec carn)
    (platTipus sopa_ceba sopa)
    (platTipus filet_porc carn)
    (platTipus crema_de_xocolata crema)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus parrillada_verdures verdures)
    (platTipus xai_rostit carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_de_peix dimarts)
    (platObligatori pollastre_a_la_planxa divendres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )