(define (problem menuext3b-tc3)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
escalivada_verdures amanida_quinoa cigrons_saltejats sopa_de_marisc tallarins_carbonara crema_de_carbassa sopa_miso brocoli_allada amanida_catalana hummus - primer
faves_estofades sopa_de_galets truita_de_llenties hamburguesa_mongeta llenguado_amb_lima filet_porc botifarra_a_la_planxa tataki_verdures sopa_ceba salmo_grillat - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_catalana botifarra_a_la_planxa)
    (incompatible escalivada_verdures filet_porc)
    (incompatible amanida_catalana llenguado_amb_lima)
    (incompatible escalivada_verdures sopa_de_galets)
    (incompatible cigrons_saltejats llenguado_amb_lima)
    (incompatible escalivada_verdures botifarra_a_la_planxa)
    (incompatible amanida_catalana salmo_grillat)
    (incompatible hummus llenguado_amb_lima)
    (platTipus escalivada_verdures verdures)
    (platTipus amanida_quinoa amanida)
    (platTipus cigrons_saltejats llegums)
    (platTipus sopa_de_marisc sopa)
    (platTipus tallarins_carbonara pasta)
    (platTipus crema_de_carbassa crema)
    (platTipus sopa_miso sopa)
    (platTipus brocoli_allada verdures)
    (platTipus amanida_catalana amanida)
    (platTipus hummus llegums)
    (platTipus faves_estofades llegums)
    (platTipus sopa_de_galets sopa)
    (platTipus truita_de_llenties llegums)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus llenguado_amb_lima peix)
    (platTipus filet_porc carn)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus tataki_verdures verdures)
    (platTipus sopa_ceba sopa)
    (platTipus salmo_grillat peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori filet_porc dimecres)
    (platObligatori sopa_ceba dimarts)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )