(define (problem menuext3b-tc4)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_de_cogombre escalivada_verdures sopa_miso amanida_quinoa estofat_llenties penne_arrabiata verdures_a_la_planxa amanida_asiatica crema_espinacs raviolis_ricotta - primer
sopa_de_pedra crema_taronja curry_verdures botifarra_a_la_planxa parrillada_verdures crema_de_limon estofat_soja crema_avellana sopa_ceba filet_porc - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible penne_arrabiata crema_de_limon)
    (incompatible raviolis_ricotta crema_taronja)
    (incompatible escalivada_verdures filet_porc)
    (incompatible amanida_de_cogombre filet_porc)
    (incompatible penne_arrabiata crema_taronja)
    (incompatible verdures_a_la_planxa sopa_de_pedra)
    (incompatible crema_espinacs botifarra_a_la_planxa)
    (incompatible penne_arrabiata crema_avellana)
    (platTipus amanida_de_cogombre amanida)
    (platTipus escalivada_verdures verdures)
    (platTipus sopa_miso sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus estofat_llenties llegums)
    (platTipus penne_arrabiata pasta)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus amanida_asiatica amanida)
    (platTipus crema_espinacs crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus sopa_de_pedra sopa)
    (platTipus crema_taronja crema)
    (platTipus curry_verdures verdures)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus parrillada_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus estofat_soja llegums)
    (platTipus crema_avellana crema)
    (platTipus sopa_ceba sopa)
    (platTipus filet_porc carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_ceba dijous)
    (platObligatori penne_arrabiata dimecres)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )