(define (problem menuext3b-tc5)
          (:domain menuext3b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_de_peix sopa_de_marisc sopa_de_cigrons sopa_verdures hummus crema_de_carabasso penne_arrabiata amanida_fasols macarrons_forn amanida_de_cogombre - primer
truita_verdures turbot_planxa wok_verdures llenguado_amb_lima crema_taronja estofat_soja filet_porc sopa_ceba salmo_grillat estofat_cigrons - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_de_cogombre filet_porc)
    (incompatible sopa_de_marisc wok_verdures)
    (incompatible amanida_fasols turbot_planxa)
    (incompatible amanida_fasols llenguado_amb_lima)
    (incompatible amanida_fasols salmo_grillat)
    (incompatible sopa_verdures truita_verdures)
    (incompatible hummus salmo_grillat)
    (incompatible sopa_de_marisc truita_verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_de_marisc sopa)
    (platTipus sopa_de_cigrons sopa)
    (platTipus sopa_verdures sopa)
    (platTipus hummus llegums)
    (platTipus crema_de_carabasso crema)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_fasols llegums)
    (platTipus macarrons_forn pasta)
    (platTipus amanida_de_cogombre amanida)
    (platTipus truita_verdures verdures)
    (platTipus turbot_planxa peix)
    (platTipus wok_verdures verdures)
    (platTipus llenguado_amb_lima peix)
    (platTipus crema_taronja crema)
    (platTipus estofat_soja llegums)
    (platTipus filet_porc carn)
    (platTipus sopa_ceba sopa)
    (platTipus salmo_grillat peix)
    (platTipus estofat_cigrons llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori estofat_soja dimarts)
    (platObligatori sopa_ceba dilluns)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )