      (define (problem menu-ext4b-2)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  macarrons_forn sopa_de_peix carpaccio_vedella hummus estofat_llenties tallarins_carbonara botifarra_brasa llobarro_forn tataki_salmo cigrons_saltejats crema_de_carbassa sopa_de_marisc - primer
  llenguado_amb_lima crema_de_xocolata truita_verdures amanida_de_espinacs espaguetis_marisc bacalla_amb_tomate pennes_amb_pesto faves_estofades sopa_de_galets salmo_grillat crema_de_limon crema_catalana - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn amanida_de_espinacs)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn crema_catalana)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible sopa_de_peix espaguetis_marisc)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible carpaccio_vedella sopa_de_galets)
      (incompatible hummus llenguado_amb_lima)
      (incompatible hummus espaguetis_marisc)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus salmo_grillat)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible estofat_llenties espaguetis_marisc)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (incompatible tallarins_carbonara amanida_de_espinacs)
      (incompatible tallarins_carbonara crema_de_limon)
      (incompatible tallarins_carbonara crema_catalana)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible llobarro_forn crema_catalana)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible tataki_salmo crema_catalana)
      (incompatible cigrons_saltejats llenguado_amb_lima)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible crema_de_carbassa llenguado_amb_lima)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible sopa_de_marisc truita_verdures)
      (incompatible sopa_de_marisc espaguetis_marisc)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (platTipus macarrons_forn pasta)
      (platTipus sopa_de_peix sopa)
      (platTipus carpaccio_vedella carn)
      (platTipus hummus llegums)
      (platTipus estofat_llenties llegums)
      (platTipus tallarins_carbonara pasta)
      (platTipus botifarra_brasa carn)
      (platTipus llobarro_forn peix)
      (platTipus tataki_salmo peix)
      (platTipus cigrons_saltejats llegums)
      (platTipus crema_de_carbassa crema)
      (platTipus sopa_de_marisc sopa)
      (platTipus llenguado_amb_lima peix)
      (platTipus crema_de_xocolata crema)
      (platTipus truita_verdures verdures)
      (platTipus amanida_de_espinacs amanida)
      (platTipus espaguetis_marisc pasta)
      (platTipus bacalla_amb_tomate peix)
      (platTipus pennes_amb_pesto pasta)
      (platTipus faves_estofades llegums)
      (platTipus sopa_de_galets sopa)
      (platTipus salmo_grillat peix)
      (platTipus crema_de_limon crema)
      (platTipus crema_catalana crema)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories macarrons_forn) 380)
      (= (calories sopa_de_peix) 250)
      (= (calories carpaccio_vedella) 200)
      (= (calories hummus) 300)
      (= (calories estofat_llenties) 350)
      (= (calories tallarins_carbonara) 420)
      (= (calories botifarra_brasa) 350)
      (= (calories llobarro_forn) 260)
      (= (calories tataki_salmo) 240)
      (= (calories cigrons_saltejats) 330)
      (= (calories crema_de_carbassa) 180)
      (= (calories sopa_de_marisc) 320)
      (= (calories llenguado_amb_lima) 500)
      (= (calories crema_de_xocolata) 260)
      (= (calories truita_verdures) 300)
      (= (calories amanida_de_espinacs) 170)
      (= (calories espaguetis_marisc) 550)
      (= (calories bacalla_amb_tomate) 550)
      (= (calories pennes_amb_pesto) 500)
      (= (calories faves_estofades) 480)
      (= (calories sopa_de_galets) 280)
      (= (calories salmo_grillat) 520)
      (= (calories crema_de_limon) 240)
      (= (calories crema_catalana) 250)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (platObligatori botifarra_brasa dilluns)
      (platObligatori estofat_llenties divendres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )