(define (problem menu-ext4b-5)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_miso fajitas_verdures hummus penne_arrabiata crema_de_carabasso cigrons_saltejats truita_potatge sopa_de_marisc macarrons_forn amanida_fasols crema_de_carxofa amanida_quinoa - primer
  estofat_cigrons faves_estofades crema_catalana estofat_soja tataki_verdures crema_taronja filet_porc sopa_de_peix sopa_de_pedra bacalla_amb_tomate cuixa_ànec crema_de_limon - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_miso tataki_verdures)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible fajitas_verdures sopa_de_pedra)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible hummus bacalla_amb_tomate)
  (incompatible penne_arrabiata crema_catalana)
  (incompatible penne_arrabiata crema_taronja)
  (incompatible penne_arrabiata crema_de_limon)
  (incompatible crema_de_carabasso filet_porc)
  (incompatible crema_de_carabasso bacalla_amb_tomate)
  (incompatible crema_de_carabasso cuixa_ànec)
  (incompatible cigrons_saltejats bacalla_amb_tomate)
  (incompatible truita_potatge bacalla_amb_tomate)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible macarrons_forn crema_catalana)
  (incompatible macarrons_forn crema_taronja)
  (incompatible macarrons_forn crema_de_limon)
  (incompatible amanida_fasols bacalla_amb_tomate)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa bacalla_amb_tomate)
  (incompatible crema_de_carxofa cuixa_ànec)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa bacalla_amb_tomate)
  (incompatible amanida_quinoa cuixa_ànec)
  (platTipus sopa_miso sopa)
  (platTipus fajitas_verdures verdures)
  (platTipus hummus llegums)
  (platTipus penne_arrabiata pasta)
  (platTipus crema_de_carabasso crema)
  (platTipus cigrons_saltejats llegums)
  (platTipus truita_potatge llegums)
  (platTipus sopa_de_marisc sopa)
  (platTipus macarrons_forn pasta)
  (platTipus amanida_fasols llegums)
  (platTipus crema_de_carxofa crema)
  (platTipus amanida_quinoa amanida)
  (platTipus estofat_cigrons llegums)
  (platTipus faves_estofades llegums)
  (platTipus crema_catalana crema)
  (platTipus estofat_soja llegums)
  (platTipus tataki_verdures verdures)
  (platTipus crema_taronja crema)
  (platTipus filet_porc carn)
  (platTipus sopa_de_peix sopa)
  (platTipus sopa_de_pedra sopa)
  (platTipus bacalla_amb_tomate peix)
  (platTipus cuixa_ànec carn)
  (platTipus crema_de_limon crema)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_miso) 500)
  (= (calories fajitas_verdures) 390)
  (= (calories hummus) 530)
  (= (calories penne_arrabiata) 720)
  (= (calories crema_de_carabasso) 330)
  (= (calories cigrons_saltejats) 570)
  (= (calories truita_potatge) 580)
  (= (calories sopa_de_marisc) 560)
  (= (calories macarrons_forn) 650)
  (= (calories amanida_fasols) 560)
  (= (calories crema_de_carxofa) 320)
  (= (calories amanida_quinoa) 360)
  (= (calories estofat_cigrons) 690)
  (= (calories faves_estofades) 730)
  (= (calories crema_catalana) 440)
  (= (calories estofat_soja) 700)
  (= (calories tataki_verdures) 520)
  (= (calories crema_taronja) 410)
  (= (calories filet_porc) 900)
  (= (calories sopa_de_peix) 520)
  (= (calories sopa_de_pedra) 500)
  (= (calories bacalla_amb_tomate) 810)
  (= (calories cuixa_ànec) 980)
  (= (calories crema_de_limon) 430)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (platObligatori crema_taronja dilluns)
  (platObligatori sopa_de_marisc dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )