      (define (problem menu-ext4b-3)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_cigrons ceviche_tonyina estofat_llenties amanida_de_tomaquet botifarra_brasa carpaccio_vedella sopa_de_peix croquetes_carn escalivada_verdures llobarro_forn crema_de_carbassa cigrons_saltejats - primer
  faves_estofades tataki_verdures amanida_cesar crema_catalana xai_rostit sopa_de_galets crema_de_xocolata bacalla_amb_tomate botifarra_a_la_planxa truita_verdures sopa_de_peix parrillada_verdures - segon
  amanida carn crema llegums peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible ceviche_tonyina crema_catalana)
      (incompatible ceviche_tonyina xai_rostit)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible botifarra_brasa tataki_verdures)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible carpaccio_vedella sopa_de_galets)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible croquetes_carn tataki_verdures)
      (incompatible croquetes_carn sopa_de_galets)
      (incompatible croquetes_carn truita_verdures)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible escalivada_verdures botifarra_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible llobarro_forn crema_catalana)
      (incompatible llobarro_forn xai_rostit)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (platTipus sopa_de_cigrons sopa)
      (platTipus ceviche_tonyina peix)
      (platTipus estofat_llenties llegums)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus botifarra_brasa carn)
      (platTipus carpaccio_vedella carn)
      (platTipus sopa_de_peix sopa)
      (platTipus croquetes_carn carn)
      (platTipus escalivada_verdures verdures)
      (platTipus llobarro_forn peix)
      (platTipus crema_de_carbassa crema)
      (platTipus cigrons_saltejats llegums)
      (platTipus faves_estofades llegums)
      (platTipus tataki_verdures verdures)
      (platTipus amanida_cesar amanida)
      (platTipus crema_catalana crema)
      (platTipus xai_rostit carn)
      (platTipus sopa_de_galets sopa)
      (platTipus crema_de_xocolata crema)
      (platTipus bacalla_amb_tomate peix)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus truita_verdures verdures)
      (platTipus sopa_de_peix sopa)
      (platTipus parrillada_verdures verdures)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories sopa_de_cigrons) 300)
      (= (calories ceviche_tonyina) 220)
      (= (calories estofat_llenties) 350)
      (= (calories amanida_de_tomaquet) 130)
      (= (calories botifarra_brasa) 350)
      (= (calories carpaccio_vedella) 200)
      (= (calories sopa_de_peix) 250)
      (= (calories croquetes_carn) 250)
      (= (calories escalivada_verdures) 180)
      (= (calories llobarro_forn) 260)
      (= (calories crema_de_carbassa) 180)
      (= (calories cigrons_saltejats) 330)
      (= (calories faves_estofades) 480)
      (= (calories tataki_verdures) 320)
      (= (calories amanida_cesar) 180)
      (= (calories crema_catalana) 250)
      (= (calories xai_rostit) 700)
      (= (calories sopa_de_galets) 280)
      (= (calories crema_de_xocolata) 260)
      (= (calories bacalla_amb_tomate) 550)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories truita_verdures) 300)
      (= (calories sopa_de_peix) 320)
      (= (calories parrillada_verdures) 340)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (platObligatori amanida_de_tomaquet dimarts)
      (platObligatori amanida_cesar dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )