(define (problem menu-ext4b-3)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  cigrons_saltejats crema_espinacs raviolis_ricotta amanida_quinoa crema_de_carabasso sopa_miso estofat_llenties sopa_de_marisc amanida_fasols crema_de_carbassa gnocchi_pesto penne_arrabiata - primer
  sopa_ajo botifarra_a_la_planxa salmo_grillat tataki_verdures crema_catalana wok_verdures estofat_soja sopa_de_galets filet_porc orata_forno turbot_planxa pollastre_a_la_planxa - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible cigrons_saltejats orata_forno)
  (incompatible cigrons_saltejats turbot_planxa)
  (incompatible crema_espinacs botifarra_a_la_planxa)
  (incompatible crema_espinacs salmo_grillat)
  (incompatible crema_espinacs filet_porc)
  (incompatible crema_espinacs orata_forno)
  (incompatible crema_espinacs turbot_planxa)
  (incompatible crema_espinacs pollastre_a_la_planxa)
  (incompatible raviolis_ricotta crema_catalana)
  (incompatible amanida_quinoa botifarra_a_la_planxa)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa orata_forno)
  (incompatible amanida_quinoa turbot_planxa)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible crema_de_carabasso botifarra_a_la_planxa)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible crema_de_carabasso filet_porc)
  (incompatible crema_de_carabasso orata_forno)
  (incompatible crema_de_carabasso turbot_planxa)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible sopa_miso tataki_verdures)
  (incompatible sopa_miso wok_verdures)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible estofat_llenties orata_forno)
  (incompatible estofat_llenties turbot_planxa)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible amanida_fasols orata_forno)
  (incompatible amanida_fasols turbot_planxa)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa salmo_grillat)
  (incompatible crema_de_carbassa filet_porc)
  (incompatible crema_de_carbassa orata_forno)
  (incompatible crema_de_carbassa turbot_planxa)
  (incompatible crema_de_carbassa pollastre_a_la_planxa)
  (incompatible gnocchi_pesto crema_catalana)
  (incompatible penne_arrabiata crema_catalana)
  (platTipus cigrons_saltejats llegums)
  (platTipus crema_espinacs crema)
  (platTipus raviolis_ricotta pasta)
  (platTipus amanida_quinoa amanida)
  (platTipus crema_de_carabasso crema)
  (platTipus sopa_miso sopa)
  (platTipus estofat_llenties llegums)
  (platTipus sopa_de_marisc sopa)
  (platTipus amanida_fasols llegums)
  (platTipus crema_de_carbassa crema)
  (platTipus gnocchi_pesto pasta)
  (platTipus penne_arrabiata pasta)
  (platTipus sopa_ajo sopa)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus salmo_grillat peix)
  (platTipus tataki_verdures verdures)
  (platTipus crema_catalana crema)
  (platTipus wok_verdures verdures)
  (platTipus estofat_soja llegums)
  (platTipus sopa_de_galets sopa)
  (platTipus filet_porc carn)
  (platTipus orata_forno peix)
  (platTipus turbot_planxa peix)
  (platTipus pollastre_a_la_planxa carn)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories cigrons_saltejats) 570)
  (= (calories crema_espinacs) 380)
  (= (calories raviolis_ricotta) 680)
  (= (calories amanida_quinoa) 360)
  (= (calories crema_de_carabasso) 330)
  (= (calories sopa_miso) 500)
  (= (calories estofat_llenties) 600)
  (= (calories sopa_de_marisc) 560)
  (= (calories amanida_fasols) 560)
  (= (calories crema_de_carbassa) 350)
  (= (calories gnocchi_pesto) 740)
  (= (calories penne_arrabiata) 720)
  (= (calories sopa_ajo) 490)
  (= (calories botifarra_a_la_planxa) 880)
  (= (calories salmo_grillat) 780)
  (= (calories tataki_verdures) 520)
  (= (calories crema_catalana) 440)
  (= (calories wok_verdures) 540)
  (= (calories estofat_soja) 700)
  (= (calories sopa_de_galets) 470)
  (= (calories filet_porc) 900)
  (= (calories orata_forno) 800)
  (= (calories turbot_planxa) 790)
  (= (calories pollastre_a_la_planxa) 940)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (platObligatori salmo_grillat dimarts)
  (platObligatori orata_forno dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )