(define (problem menu-ext4b-4)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  verdures_a_la_planxa fajitas_verdures brocoli_allada amanida_fasols crema_de_carbassa estofat_llenties amanida_de_tomaquet crema_espinacs tallarins_carbonara hummus gnocchi_pesto sopa_de_peix - primer
  crema_de_xocolata tataki_verdures estofat_soja sopa_de_peix truita_de_llenties sopa_ajo curry_verdures sopa_de_galets crema_avellana crema_catalana crema_de_limon hamburguesa_mongeta - segon
  amanida crema llegums pasta sopa verdures DummyT - tipus
)

        (:init
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible brocoli_allada sopa_de_peix)
  (incompatible brocoli_allada sopa_ajo)
  (incompatible brocoli_allada sopa_de_galets)
  (incompatible tallarins_carbonara crema_de_xocolata)
  (incompatible tallarins_carbonara crema_avellana)
  (incompatible tallarins_carbonara crema_catalana)
  (incompatible tallarins_carbonara crema_de_limon)
  (incompatible gnocchi_pesto crema_de_xocolata)
  (incompatible gnocchi_pesto crema_avellana)
  (incompatible gnocchi_pesto crema_catalana)
  (incompatible gnocchi_pesto crema_de_limon)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible sopa_de_peix curry_verdures)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus fajitas_verdures verdures)
  (platTipus brocoli_allada verdures)
  (platTipus amanida_fasols llegums)
  (platTipus crema_de_carbassa crema)
  (platTipus estofat_llenties llegums)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus crema_espinacs crema)
  (platTipus tallarins_carbonara pasta)
  (platTipus hummus llegums)
  (platTipus gnocchi_pesto pasta)
  (platTipus sopa_de_peix sopa)
  (platTipus crema_de_xocolata crema)
  (platTipus tataki_verdures verdures)
  (platTipus estofat_soja llegums)
  (platTipus sopa_de_peix sopa)
  (platTipus truita_de_llenties llegums)
  (platTipus sopa_ajo sopa)
  (platTipus curry_verdures verdures)
  (platTipus sopa_de_galets sopa)
  (platTipus crema_avellana crema)
  (platTipus crema_catalana crema)
  (platTipus crema_de_limon crema)
  (platTipus hamburguesa_mongeta llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories verdures_a_la_planxa) 300)
  (= (calories fajitas_verdures) 390)
  (= (calories brocoli_allada) 360)
  (= (calories amanida_fasols) 560)
  (= (calories crema_de_carbassa) 350)
  (= (calories estofat_llenties) 600)
  (= (calories amanida_de_tomaquet) 270)
  (= (calories crema_espinacs) 380)
  (= (calories tallarins_carbonara) 700)
  (= (calories hummus) 530)
  (= (calories gnocchi_pesto) 740)
  (= (calories sopa_de_peix) 450)
  (= (calories crema_de_xocolata) 450)
  (= (calories tataki_verdures) 520)
  (= (calories estofat_soja) 700)
  (= (calories sopa_de_peix) 520)
  (= (calories truita_de_llenties) 620)
  (= (calories sopa_ajo) 490)
  (= (calories curry_verdures) 580)
  (= (calories sopa_de_galets) 470)
  (= (calories crema_avellana) 480)
  (= (calories crema_catalana) 440)
  (= (calories crema_de_limon) 430)
  (= (calories hamburguesa_mongeta) 670)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (platObligatori sopa_de_peix dilluns)
  (platObligatori sopa_de_galets dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )