      (define (problem menu-ext4b-1)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  carpaccio_vedella amanida_de_tomaquet verdures_a_la_planxa tallarins_carbonara estofat_llenties cigrons_saltejats crema_de_carbassa macarrons_forn tataki_salmo hummus sopa_de_peix crema_de_carxofa - primer
  pollastre_a_la_planxa tataki_verdures espaguetis_marisc salmo_grillat crema_de_limon sopa_de_pedra xai_rostit parrillada_verdures crema_de_xocolata truita_verdures botifarra_a_la_planxa truita_de_llenties - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible carpaccio_vedella sopa_de_pedra)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
      (incompatible verdures_a_la_planxa sopa_de_pedra)
      (incompatible verdures_a_la_planxa xai_rostit)
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible tallarins_carbonara crema_de_limon)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (incompatible estofat_llenties espaguetis_marisc)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible tataki_salmo pollastre_a_la_planxa)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible tataki_salmo xai_rostit)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible hummus espaguetis_marisc)
      (incompatible hummus salmo_grillat)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix espaguetis_marisc)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible crema_de_carxofa xai_rostit)
      (incompatible crema_de_carxofa botifarra_a_la_planxa)
      (platTipus carpaccio_vedella carn)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus tallarins_carbonara pasta)
      (platTipus estofat_llenties llegums)
      (platTipus cigrons_saltejats llegums)
      (platTipus crema_de_carbassa crema)
      (platTipus macarrons_forn pasta)
      (platTipus tataki_salmo peix)
      (platTipus hummus llegums)
      (platTipus sopa_de_peix sopa)
      (platTipus crema_de_carxofa crema)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus tataki_verdures verdures)
      (platTipus espaguetis_marisc pasta)
      (platTipus salmo_grillat peix)
      (platTipus crema_de_limon crema)
      (platTipus sopa_de_pedra sopa)
      (platTipus xai_rostit carn)
      (platTipus parrillada_verdures verdures)
      (platTipus crema_de_xocolata crema)
      (platTipus truita_verdures verdures)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus truita_de_llenties llegums)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories carpaccio_vedella) 200)
      (= (calories amanida_de_tomaquet) 130)
      (= (calories verdures_a_la_planxa) 150)
      (= (calories tallarins_carbonara) 420)
      (= (calories estofat_llenties) 350)
      (= (calories cigrons_saltejats) 330)
      (= (calories crema_de_carbassa) 180)
      (= (calories macarrons_forn) 380)
      (= (calories tataki_salmo) 240)
      (= (calories hummus) 300)
      (= (calories sopa_de_peix) 250)
      (= (calories crema_de_carxofa) 160)
      (= (calories pollastre_a_la_planxa) 650)
      (= (calories tataki_verdures) 320)
      (= (calories espaguetis_marisc) 550)
      (= (calories salmo_grillat) 520)
      (= (calories crema_de_limon) 240)
      (= (calories sopa_de_pedra) 300)
      (= (calories xai_rostit) 700)
      (= (calories parrillada_verdures) 340)
      (= (calories crema_de_xocolata) 260)
      (= (calories truita_verdures) 300)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories truita_de_llenties) 400)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (platObligatori pollastre_a_la_planxa dilluns)
      (platObligatori sopa_de_pedra dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )