(define (problem menu-ext4b-1)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_peix crema_de_bolets verdures_amb_salsa amanida_de_tomaquet truita_potatge fajitas_verdures sopa_de_cigrons hummus tallarins_carbonara sopa_de_marisc raviolis_ricotta brocoli_allada - primer
  crema_catalana crema_taronja sopa_ceba sopa_de_pedra orata_forno parrillada_verdures crema_de_limon curry_verdures turbot_planxa filet_porc xai_rostit pollastre_a_la_planxa - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible sopa_de_peix curry_verdures)
  (incompatible crema_de_bolets orata_forno)
  (incompatible crema_de_bolets turbot_planxa)
  (incompatible crema_de_bolets filet_porc)
  (incompatible crema_de_bolets xai_rostit)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_ceba)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible verdures_amb_salsa xai_rostit)
  (incompatible verdures_amb_salsa pollastre_a_la_planxa)
  (incompatible amanida_de_tomaquet orata_forno)
  (incompatible amanida_de_tomaquet turbot_planxa)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet xai_rostit)
  (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
  (incompatible truita_potatge orata_forno)
  (incompatible truita_potatge turbot_planxa)
  (incompatible fajitas_verdures sopa_ceba)
  (incompatible fajitas_verdures sopa_de_pedra)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures xai_rostit)
  (incompatible fajitas_verdures pollastre_a_la_planxa)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible sopa_de_cigrons curry_verdures)
  (incompatible hummus orata_forno)
  (incompatible hummus turbot_planxa)
  (incompatible tallarins_carbonara crema_catalana)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible tallarins_carbonara crema_de_limon)
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc curry_verdures)
  (incompatible raviolis_ricotta crema_catalana)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible raviolis_ricotta crema_de_limon)
  (incompatible brocoli_allada sopa_ceba)
  (incompatible brocoli_allada sopa_de_pedra)
  (incompatible brocoli_allada filet_porc)
  (incompatible brocoli_allada xai_rostit)
  (incompatible brocoli_allada pollastre_a_la_planxa)
  (platTipus sopa_de_peix sopa)
  (platTipus crema_de_bolets crema)
  (platTipus verdures_amb_salsa verdures)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus truita_potatge llegums)
  (platTipus fajitas_verdures verdures)
  (platTipus sopa_de_cigrons sopa)
  (platTipus hummus llegums)
  (platTipus tallarins_carbonara pasta)
  (platTipus sopa_de_marisc sopa)
  (platTipus raviolis_ricotta pasta)
  (platTipus brocoli_allada verdures)
  (platTipus crema_catalana crema)
  (platTipus crema_taronja crema)
  (platTipus sopa_ceba sopa)
  (platTipus sopa_de_pedra sopa)
  (platTipus orata_forno peix)
  (platTipus parrillada_verdures verdures)
  (platTipus crema_de_limon crema)
  (platTipus curry_verdures verdures)
  (platTipus turbot_planxa peix)
  (platTipus filet_porc carn)
  (platTipus xai_rostit carn)
  (platTipus pollastre_a_la_planxa carn)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_de_peix) 450)
  (= (calories crema_de_bolets) 390)
  (= (calories verdures_amb_salsa) 380)
  (= (calories amanida_de_tomaquet) 270)
  (= (calories truita_potatge) 580)
  (= (calories fajitas_verdures) 390)
  (= (calories sopa_de_cigrons) 530)
  (= (calories hummus) 530)
  (= (calories tallarins_carbonara) 700)
  (= (calories sopa_de_marisc) 560)
  (= (calories raviolis_ricotta) 680)
  (= (calories brocoli_allada) 360)
  (= (calories crema_catalana) 440)
  (= (calories crema_taronja) 410)
  (= (calories sopa_ceba) 450)
  (= (calories sopa_de_pedra) 500)
  (= (calories orata_forno) 800)
  (= (calories parrillada_verdures) 550)
  (= (calories crema_de_limon) 430)
  (= (calories curry_verdures) 580)
  (= (calories turbot_planxa) 790)
  (= (calories filet_porc) 900)
  (= (calories xai_rostit) 1000)
  (= (calories pollastre_a_la_planxa) 940)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (platObligatori crema_taronja divendres)
  (platObligatori curry_verdures dilluns)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )