      (define (problem menu-ext4b-5)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  tallarins_carbonara llobarro_forn amanida_de_tomaquet crema_de_carabasso cigrons_saltejats sopa_de_cigrons croquetes_carn estofat_llenties sopa_de_peix amanida_de_cogombre ceviche_tonyina carpaccio_vedella - primer
  pennes_amb_pesto salmo_grillat botifarra_a_la_planxa xai_rostit amanida_de_remolatxa sopa_de_pedra faves_estofades pollastre_a_la_planxa amanida_cesar tataki_verdures bacalla_amb_tomate espaguetis_marisc - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible tallarins_carbonara amanida_de_remolatxa)
      (incompatible tallarins_carbonara amanida_cesar)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible llobarro_forn xai_rostit)
      (incompatible llobarro_forn pollastre_a_la_planxa)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible crema_de_carabasso botifarra_a_la_planxa)
      (incompatible crema_de_carabasso xai_rostit)
      (incompatible crema_de_carabasso pollastre_a_la_planxa)
      (incompatible crema_de_carabasso bacalla_amb_tomate)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons espaguetis_marisc)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible croquetes_carn tataki_verdures)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties espaguetis_marisc)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix espaguetis_marisc)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre botifarra_a_la_planxa)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible ceviche_tonyina xai_rostit)
      (incompatible ceviche_tonyina pollastre_a_la_planxa)
      (incompatible carpaccio_vedella sopa_de_pedra)
      (incompatible carpaccio_vedella tataki_verdures)
      (platTipus tallarins_carbonara pasta)
      (platTipus llobarro_forn peix)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus crema_de_carabasso crema)
      (platTipus cigrons_saltejats llegums)
      (platTipus sopa_de_cigrons sopa)
      (platTipus croquetes_carn carn)
      (platTipus estofat_llenties llegums)
      (platTipus sopa_de_peix sopa)
      (platTipus amanida_de_cogombre amanida)
      (platTipus ceviche_tonyina peix)
      (platTipus carpaccio_vedella carn)
      (platTipus pennes_amb_pesto pasta)
      (platTipus salmo_grillat peix)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus xai_rostit carn)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus sopa_de_pedra sopa)
      (platTipus faves_estofades llegums)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus amanida_cesar amanida)
      (platTipus tataki_verdures verdures)
      (platTipus bacalla_amb_tomate peix)
      (platTipus espaguetis_marisc pasta)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories tallarins_carbonara) 420)
      (= (calories llobarro_forn) 260)
      (= (calories amanida_de_tomaquet) 130)
      (= (calories crema_de_carabasso) 170)
      (= (calories cigrons_saltejats) 330)
      (= (calories sopa_de_cigrons) 300)
      (= (calories croquetes_carn) 250)
      (= (calories estofat_llenties) 350)
      (= (calories sopa_de_peix) 250)
      (= (calories amanida_de_cogombre) 120)
      (= (calories ceviche_tonyina) 220)
      (= (calories carpaccio_vedella) 200)
      (= (calories pennes_amb_pesto) 500)
      (= (calories salmo_grillat) 520)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories xai_rostit) 700)
      (= (calories amanida_de_remolatxa) 160)
      (= (calories sopa_de_pedra) 300)
      (= (calories faves_estofades) 480)
      (= (calories pollastre_a_la_planxa) 650)
      (= (calories amanida_cesar) 180)
      (= (calories tataki_verdures) 320)
      (= (calories bacalla_amb_tomate) 550)
      (= (calories espaguetis_marisc) 550)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (platObligatori pennes_amb_pesto dilluns)
      (platObligatori xai_rostit dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )