      (define (problem menu-ext4b-4)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  verdures_a_la_planxa tataki_salmo llobarro_forn estofat_llenties tallarins_carbonara botifarra_brasa escalivada_verdures carpaccio_vedella hummus ceviche_tonyina amanida_de_tomaquet raviolis_ricotta - primer
  llenguado_amb_lima botifarra_a_la_planxa sopa_de_peix sopa_de_galets truita_verdures bacalla_amb_tomate parrillada_verdures faves_estofades truita_de_llenties estofat_cigrons amanida_de_remolatxa tortellinis_carne - segon
  amanida carn llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible verdures_a_la_planxa sopa_de_galets)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties tortellinis_carne)
      (incompatible tallarins_carbonara amanida_de_remolatxa)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible escalivada_verdures botifarra_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible carpaccio_vedella sopa_de_galets)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible hummus llenguado_amb_lima)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible hummus tortellinis_carne)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible amanida_de_tomaquet llenguado_amb_lima)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible raviolis_ricotta amanida_de_remolatxa)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus tataki_salmo peix)
      (platTipus llobarro_forn peix)
      (platTipus estofat_llenties llegums)
      (platTipus tallarins_carbonara pasta)
      (platTipus botifarra_brasa carn)
      (platTipus escalivada_verdures verdures)
      (platTipus carpaccio_vedella carn)
      (platTipus hummus llegums)
      (platTipus ceviche_tonyina peix)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus raviolis_ricotta pasta)
      (platTipus llenguado_amb_lima peix)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus sopa_de_peix sopa)
      (platTipus sopa_de_galets sopa)
      (platTipus truita_verdures verdures)
      (platTipus bacalla_amb_tomate peix)
      (platTipus parrillada_verdures verdures)
      (platTipus faves_estofades llegums)
      (platTipus truita_de_llenties llegums)
      (platTipus estofat_cigrons llegums)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus tortellinis_carne pasta)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories verdures_a_la_planxa) 150)
      (= (calories tataki_salmo) 240)
      (= (calories llobarro_forn) 260)
      (= (calories estofat_llenties) 350)
      (= (calories tallarins_carbonara) 420)
      (= (calories botifarra_brasa) 350)
      (= (calories escalivada_verdures) 180)
      (= (calories carpaccio_vedella) 200)
      (= (calories hummus) 300)
      (= (calories ceviche_tonyina) 220)
      (= (calories amanida_de_tomaquet) 130)
      (= (calories raviolis_ricotta) 400)
      (= (calories llenguado_amb_lima) 500)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories sopa_de_peix) 320)
      (= (calories sopa_de_galets) 280)
      (= (calories truita_verdures) 300)
      (= (calories bacalla_amb_tomate) 550)
      (= (calories parrillada_verdures) 340)
      (= (calories faves_estofades) 480)
      (= (calories truita_de_llenties) 400)
      (= (calories estofat_cigrons) 450)
      (= (calories amanida_de_remolatxa) 160)
      (= (calories tortellinis_carne) 600)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (platObligatori ceviche_tonyina dimecres)
      (platObligatori carpaccio_vedella divendres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )