(define (problem menu-ext4b-2)
        (:domain menuext4b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_marisc fajitas_verdures penne_arrabiata crema_de_carabasso crema_de_bolets amanida_de_cogombre cigrons_saltejats sopa_miso amanida_catalana tallarins_carbonara raviolis_ricotta escalivada_verdures - primer
  xai_rostit filet_porc crema_de_xocolata truita_de_llenties pollastre_a_la_planxa turbot_planxa truita_verdures tataki_verdures crema_taronja sopa_ajo bacalla_amb_tomate estofat_cigrons - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_de_marisc truita_verdures)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible fajitas_verdures xai_rostit)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures pollastre_a_la_planxa)
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible penne_arrabiata crema_de_xocolata)
  (incompatible penne_arrabiata crema_taronja)
  (incompatible crema_de_carabasso xai_rostit)
  (incompatible crema_de_carabasso filet_porc)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible crema_de_carabasso turbot_planxa)
  (incompatible crema_de_carabasso bacalla_amb_tomate)
  (incompatible crema_de_bolets xai_rostit)
  (incompatible crema_de_bolets filet_porc)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets turbot_planxa)
  (incompatible crema_de_bolets bacalla_amb_tomate)
  (incompatible amanida_de_cogombre xai_rostit)
  (incompatible amanida_de_cogombre filet_porc)
  (incompatible amanida_de_cogombre pollastre_a_la_planxa)
  (incompatible amanida_de_cogombre turbot_planxa)
  (incompatible amanida_de_cogombre bacalla_amb_tomate)
  (incompatible cigrons_saltejats turbot_planxa)
  (incompatible cigrons_saltejats bacalla_amb_tomate)
  (incompatible sopa_miso truita_verdures)
  (incompatible sopa_miso tataki_verdures)
  (incompatible amanida_catalana xai_rostit)
  (incompatible amanida_catalana filet_porc)
  (incompatible amanida_catalana pollastre_a_la_planxa)
  (incompatible amanida_catalana turbot_planxa)
  (incompatible amanida_catalana bacalla_amb_tomate)
  (incompatible tallarins_carbonara crema_de_xocolata)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible raviolis_ricotta crema_de_xocolata)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible escalivada_verdures xai_rostit)
  (incompatible escalivada_verdures filet_porc)
  (incompatible escalivada_verdures pollastre_a_la_planxa)
  (incompatible escalivada_verdures sopa_ajo)
  (platTipus sopa_de_marisc sopa)
  (platTipus fajitas_verdures verdures)
  (platTipus penne_arrabiata pasta)
  (platTipus crema_de_carabasso crema)
  (platTipus crema_de_bolets crema)
  (platTipus amanida_de_cogombre amanida)
  (platTipus cigrons_saltejats llegums)
  (platTipus sopa_miso sopa)
  (platTipus amanida_catalana amanida)
  (platTipus tallarins_carbonara pasta)
  (platTipus raviolis_ricotta pasta)
  (platTipus escalivada_verdures verdures)
  (platTipus xai_rostit carn)
  (platTipus filet_porc carn)
  (platTipus crema_de_xocolata crema)
  (platTipus truita_de_llenties llegums)
  (platTipus pollastre_a_la_planxa carn)
  (platTipus turbot_planxa peix)
  (platTipus truita_verdures verdures)
  (platTipus tataki_verdures verdures)
  (platTipus crema_taronja crema)
  (platTipus sopa_ajo sopa)
  (platTipus bacalla_amb_tomate peix)
  (platTipus estofat_cigrons llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_de_marisc) 560)
  (= (calories fajitas_verdures) 390)
  (= (calories penne_arrabiata) 720)
  (= (calories crema_de_carabasso) 330)
  (= (calories crema_de_bolets) 390)
  (= (calories amanida_de_cogombre) 260)
  (= (calories cigrons_saltejats) 570)
  (= (calories sopa_miso) 500)
  (= (calories amanida_catalana) 300)
  (= (calories tallarins_carbonara) 700)
  (= (calories raviolis_ricotta) 680)
  (= (calories escalivada_verdures) 350)
  (= (calories xai_rostit) 1000)
  (= (calories filet_porc) 900)
  (= (calories crema_de_xocolata) 450)
  (= (calories truita_de_llenties) 620)
  (= (calories pollastre_a_la_planxa) 940)
  (= (calories turbot_planxa) 790)
  (= (calories truita_verdures) 500)
  (= (calories tataki_verdures) 520)
  (= (calories crema_taronja) 410)
  (= (calories sopa_ajo) 490)
  (= (calories bacalla_amb_tomate) 810)
  (= (calories estofat_cigrons) 690)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (platObligatori sopa_ajo dimecres)
  (platObligatori filet_porc dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )