      (define (problem menu-ext3b-2)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_de_tomaquet cigrons_saltejats carpaccio_vedella sopa_de_marisc amanida_de_cogombre amanida_catalana tallarins_carbonara crema_de_carabasso escalivada_verdures verdures_amb_salsa raviolis_ricotta sopa_de_cigrons - primer
  salmo_grillat tataki_verdures xai_rostit parrillada_verdures amanida_cesar crema_catalana amanida_de_espinacs crema_de_limon amanida_de_remolatxa truita_verdures crema_de_xocolata espaguetis_marisc - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible sopa_de_marisc tataki_verdures)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc truita_verdures)
      (incompatible sopa_de_marisc espaguetis_marisc)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_catalana salmo_grillat)
      (incompatible amanida_catalana xai_rostit)
      (incompatible tallarins_carbonara amanida_cesar)
      (incompatible tallarins_carbonara crema_catalana)
      (incompatible tallarins_carbonara amanida_de_espinacs)
      (incompatible tallarins_carbonara crema_de_limon)
      (incompatible tallarins_carbonara amanida_de_remolatxa)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible crema_de_carabasso xai_rostit)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible verdures_amb_salsa xai_rostit)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible raviolis_ricotta crema_catalana)
      (incompatible raviolis_ricotta amanida_de_espinacs)
      (incompatible raviolis_ricotta crema_de_limon)
      (incompatible raviolis_ricotta amanida_de_remolatxa)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible sopa_de_cigrons espaguetis_marisc)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus cigrons_saltejats llegums)
      (platTipus carpaccio_vedella carn)
      (platTipus sopa_de_marisc sopa)
      (platTipus amanida_de_cogombre amanida)
      (platTipus amanida_catalana amanida)
      (platTipus tallarins_carbonara pasta)
      (platTipus crema_de_carabasso crema)
      (platTipus escalivada_verdures verdures)
      (platTipus verdures_amb_salsa verdures)
      (platTipus raviolis_ricotta pasta)
      (platTipus sopa_de_cigrons sopa)
      (platTipus salmo_grillat peix)
      (platTipus tataki_verdures verdures)
      (platTipus xai_rostit carn)
      (platTipus parrillada_verdures verdures)
      (platTipus amanida_cesar amanida)
      (platTipus crema_catalana crema)
      (platTipus amanida_de_espinacs amanida)
      (platTipus crema_de_limon crema)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus truita_verdures verdures)
      (platTipus crema_de_xocolata crema)
      (platTipus espaguetis_marisc pasta)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (platObligatori crema_catalana dijous)
      (platObligatori amanida_de_cogombre dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )