      (define (problem menu-ext3b-3)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_de_cogombre macarrons_forn raviolis_ricotta verdures_amb_salsa verdures_a_la_planxa sopa_de_peix sopa_de_cigrons crema_de_carbassa estofat_llenties croquetes_carn sopa_de_marisc hummus - primer
  truita_de_llenties crema_de_limon sopa_de_galets crema_de_xocolata faves_estofades xai_rostit amanida_cesar parrillada_verdures pennes_amb_pesto pollastre_a_la_planxa sopa_de_pedra botifarra_a_la_planxa - segon
  amanida carn crema llegums pasta sopa verdures DummyT - tipus
)

        (:init
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible amanida_de_cogombre botifarra_a_la_planxa)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn amanida_cesar)
      (incompatible raviolis_ricotta crema_de_limon)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible verdures_amb_salsa sopa_de_galets)
      (incompatible verdures_amb_salsa xai_rostit)
      (incompatible verdures_amb_salsa pollastre_a_la_planxa)
      (incompatible verdures_amb_salsa sopa_de_pedra)
      (incompatible verdures_amb_salsa botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa sopa_de_galets)
      (incompatible verdures_a_la_planxa xai_rostit)
      (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
      (incompatible verdures_a_la_planxa sopa_de_pedra)
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible croquetes_carn sopa_de_galets)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible hummus pennes_amb_pesto)
      (platTipus amanida_de_cogombre amanida)
      (platTipus macarrons_forn pasta)
      (platTipus raviolis_ricotta pasta)
      (platTipus verdures_amb_salsa verdures)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus sopa_de_peix sopa)
      (platTipus sopa_de_cigrons sopa)
      (platTipus crema_de_carbassa crema)
      (platTipus estofat_llenties llegums)
      (platTipus croquetes_carn carn)
      (platTipus sopa_de_marisc sopa)
      (platTipus hummus llegums)
      (platTipus truita_de_llenties llegums)
      (platTipus crema_de_limon crema)
      (platTipus sopa_de_galets sopa)
      (platTipus crema_de_xocolata crema)
      (platTipus faves_estofades llegums)
      (platTipus xai_rostit carn)
      (platTipus amanida_cesar amanida)
      (platTipus parrillada_verdures verdures)
      (platTipus pennes_amb_pesto pasta)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus sopa_de_pedra sopa)
      (platTipus botifarra_a_la_planxa carn)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (platObligatori pollastre_a_la_planxa dimarts)
      (platObligatori botifarra_a_la_planxa dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )