(define (problem menu-ext3b-1)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  tallarins_carbonara sopa_de_peix crema_de_bolets crema_de_carabasso estofat_llenties cigrons_saltejats fajitas_verdures crema_de_carxofa verdures_amb_salsa sopa_de_marisc amanida_quinoa crema_espinacs - primer
  cuixa_ànec pollastre_a_la_planxa estofat_soja crema_de_xocolata crema_catalana wok_verdures turbot_planxa orata_forno crema_taronja tataki_verdures salmo_grillat sopa_de_galets - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible tallarins_carbonara crema_de_xocolata)
  (incompatible tallarins_carbonara crema_catalana)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible sopa_de_peix wok_verdures)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets turbot_planxa)
  (incompatible crema_de_bolets orata_forno)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_carabasso cuixa_ànec)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible crema_de_carabasso turbot_planxa)
  (incompatible crema_de_carabasso orata_forno)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible estofat_llenties turbot_planxa)
  (incompatible estofat_llenties orata_forno)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible cigrons_saltejats turbot_planxa)
  (incompatible cigrons_saltejats orata_forno)
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible fajitas_verdures pollastre_a_la_planxa)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible crema_de_carxofa cuixa_ànec)
  (incompatible crema_de_carxofa pollastre_a_la_planxa)
  (incompatible crema_de_carxofa turbot_planxa)
  (incompatible crema_de_carxofa orata_forno)
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa pollastre_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_de_galets)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible amanida_quinoa cuixa_ànec)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible amanida_quinoa turbot_planxa)
  (incompatible amanida_quinoa orata_forno)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible crema_espinacs cuixa_ànec)
  (incompatible crema_espinacs pollastre_a_la_planxa)
  (incompatible crema_espinacs turbot_planxa)
  (incompatible crema_espinacs orata_forno)
  (incompatible crema_espinacs salmo_grillat)
  (platTipus tallarins_carbonara pasta)
  (platTipus sopa_de_peix sopa)
  (platTipus crema_de_bolets crema)
  (platTipus crema_de_carabasso crema)
  (platTipus estofat_llenties llegums)
  (platTipus cigrons_saltejats llegums)
  (platTipus fajitas_verdures verdures)
  (platTipus crema_de_carxofa crema)
  (platTipus verdures_amb_salsa verdures)
  (platTipus sopa_de_marisc sopa)
  (platTipus amanida_quinoa amanida)
  (platTipus crema_espinacs crema)
  (platTipus cuixa_ànec carn)
  (platTipus pollastre_a_la_planxa carn)
  (platTipus estofat_soja llegums)
  (platTipus crema_de_xocolata crema)
  (platTipus crema_catalana crema)
  (platTipus wok_verdures verdures)
  (platTipus turbot_planxa peix)
  (platTipus orata_forno peix)
  (platTipus crema_taronja crema)
  (platTipus tataki_verdures verdures)
  (platTipus salmo_grillat peix)
  (platTipus sopa_de_galets sopa)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (platObligatori crema_catalana dimarts)
  (platObligatori verdures_amb_salsa dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )