(define (problem menu-ext3b-3)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  cigrons_saltejats sopa_de_peix crema_de_carabasso estofat_llenties hummus crema_de_bolets tallarins_carbonara macarrons_forn truita_potatge amanida_de_cogombre amanida_de_tomaquet sopa_miso - primer
  tataki_verdures sopa_ceba crema_de_limon crema_catalana pollastre_a_la_planxa estofat_soja crema_avellana estofat_cigrons curry_verdures sopa_de_pedra cuixa_ànec salmo_grillat - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible sopa_de_peix curry_verdures)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible crema_de_carabasso cuixa_ànec)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible hummus salmo_grillat)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible tallarins_carbonara crema_de_limon)
  (incompatible tallarins_carbonara crema_catalana)
  (incompatible tallarins_carbonara crema_avellana)
  (incompatible macarrons_forn crema_de_limon)
  (incompatible macarrons_forn crema_catalana)
  (incompatible macarrons_forn crema_avellana)
  (incompatible truita_potatge salmo_grillat)
  (incompatible amanida_de_cogombre pollastre_a_la_planxa)
  (incompatible amanida_de_cogombre cuixa_ànec)
  (incompatible amanida_de_cogombre salmo_grillat)
  (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
  (incompatible amanida_de_tomaquet cuixa_ànec)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible sopa_miso tataki_verdures)
  (incompatible sopa_miso curry_verdures)
  (platTipus cigrons_saltejats llegums)
  (platTipus sopa_de_peix sopa)
  (platTipus crema_de_carabasso crema)
  (platTipus estofat_llenties llegums)
  (platTipus hummus llegums)
  (platTipus crema_de_bolets crema)
  (platTipus tallarins_carbonara pasta)
  (platTipus macarrons_forn pasta)
  (platTipus truita_potatge llegums)
  (platTipus amanida_de_cogombre amanida)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus sopa_miso sopa)
  (platTipus tataki_verdures verdures)
  (platTipus sopa_ceba sopa)
  (platTipus crema_de_limon crema)
  (platTipus crema_catalana crema)
  (platTipus pollastre_a_la_planxa carn)
  (platTipus estofat_soja llegums)
  (platTipus crema_avellana crema)
  (platTipus estofat_cigrons llegums)
  (platTipus curry_verdures verdures)
  (platTipus sopa_de_pedra sopa)
  (platTipus cuixa_ànec carn)
  (platTipus salmo_grillat peix)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (platObligatori cuixa_ànec divendres)
  (platObligatori sopa_ceba dilluns)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )