      (define (problem menu-ext3b-1)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  escalivada_verdures macarrons_forn estofat_llenties cigrons_saltejats tataki_salmo amanida_catalana llobarro_forn verdures_amb_salsa crema_de_carbassa botifarra_brasa amanida_de_tomaquet crema_de_carabasso - primer
  crema_catalana parrillada_verdures salmo_grillat crema_de_limon sopa_de_peix espaguetis_marisc sopa_de_pedra pennes_amb_pesto truita_verdures bacalla_amb_tomate botifarra_a_la_planxa faves_estofades - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures botifarra_a_la_planxa)
      (incompatible macarrons_forn crema_catalana)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible estofat_llenties espaguetis_marisc)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible tataki_salmo crema_catalana)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible amanida_catalana salmo_grillat)
      (incompatible amanida_catalana bacalla_amb_tomate)
      (incompatible amanida_catalana botifarra_a_la_planxa)
      (incompatible llobarro_forn crema_catalana)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible verdures_amb_salsa sopa_de_peix)
      (incompatible verdures_amb_salsa sopa_de_pedra)
      (incompatible verdures_amb_salsa botifarra_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa sopa_de_pedra)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible crema_de_carabasso bacalla_amb_tomate)
      (incompatible crema_de_carabasso botifarra_a_la_planxa)
      (platTipus escalivada_verdures verdures)
      (platTipus macarrons_forn pasta)
      (platTipus estofat_llenties llegums)
      (platTipus cigrons_saltejats llegums)
      (platTipus tataki_salmo peix)
      (platTipus amanida_catalana amanida)
      (platTipus llobarro_forn peix)
      (platTipus verdures_amb_salsa verdures)
      (platTipus crema_de_carbassa crema)
      (platTipus botifarra_brasa carn)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus crema_de_carabasso crema)
      (platTipus crema_catalana crema)
      (platTipus parrillada_verdures verdures)
      (platTipus salmo_grillat peix)
      (platTipus crema_de_limon crema)
      (platTipus sopa_de_peix sopa)
      (platTipus espaguetis_marisc pasta)
      (platTipus sopa_de_pedra sopa)
      (platTipus pennes_amb_pesto pasta)
      (platTipus truita_verdures verdures)
      (platTipus bacalla_amb_tomate peix)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus faves_estofades llegums)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (platObligatori sopa_de_peix dimecres)
      (platObligatori crema_de_limon dilluns)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )