      (define (problem menu-ext3b-4)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  crema_de_carxofa escalivada_verdures crema_de_carbassa croquetes_carn amanida_de_cogombre ceviche_tonyina sopa_de_cigrons sopa_de_peix botifarra_brasa verdures_amb_salsa crema_de_carabasso cigrons_saltejats - primer
  sopa_de_galets parrillada_verdures amanida_cesar sopa_de_pedra pollastre_a_la_planxa pennes_amb_pesto sopa_de_peix amanida_de_espinacs salmo_grillat crema_de_xocolata estofat_cigrons llenguado_amb_lima - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible crema_de_carxofa llenguado_amb_lima)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures pollastre_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible crema_de_carbassa llenguado_amb_lima)
      (incompatible croquetes_carn sopa_de_galets)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre llenguado_amb_lima)
      (incompatible ceviche_tonyina pollastre_a_la_planxa)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible botifarra_brasa sopa_de_pedra)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible verdures_amb_salsa sopa_de_galets)
      (incompatible verdures_amb_salsa sopa_de_pedra)
      (incompatible verdures_amb_salsa pollastre_a_la_planxa)
      (incompatible verdures_amb_salsa sopa_de_peix)
      (incompatible crema_de_carabasso pollastre_a_la_planxa)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible crema_de_carabasso llenguado_amb_lima)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible cigrons_saltejats llenguado_amb_lima)
      (platTipus crema_de_carxofa crema)
      (platTipus escalivada_verdures verdures)
      (platTipus crema_de_carbassa crema)
      (platTipus croquetes_carn carn)
      (platTipus amanida_de_cogombre amanida)
      (platTipus ceviche_tonyina peix)
      (platTipus sopa_de_cigrons sopa)
      (platTipus sopa_de_peix sopa)
      (platTipus botifarra_brasa carn)
      (platTipus verdures_amb_salsa verdures)
      (platTipus crema_de_carabasso crema)
      (platTipus cigrons_saltejats llegums)
      (platTipus sopa_de_galets sopa)
      (platTipus parrillada_verdures verdures)
      (platTipus amanida_cesar amanida)
      (platTipus sopa_de_pedra sopa)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus pennes_amb_pesto pasta)
      (platTipus sopa_de_peix sopa)
      (platTipus amanida_de_espinacs amanida)
      (platTipus salmo_grillat peix)
      (platTipus crema_de_xocolata crema)
      (platTipus estofat_cigrons llegums)
      (platTipus llenguado_amb_lima peix)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (platObligatori sopa_de_galets divendres)
      (platObligatori crema_de_xocolata dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )