      (define (problem menu-ext3b-5)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_catalana crema_de_carbassa sopa_de_marisc crema_de_carxofa hummus verdures_a_la_planxa amanida_de_cogombre escalivada_verdures carpaccio_vedella cigrons_saltejats raviolis_ricotta croquetes_carn - primer
  pennes_amb_pesto xai_rostit truita_de_llenties bacalla_amb_tomate crema_catalana pollastre_a_la_planxa sopa_de_pedra sopa_de_peix amanida_de_remolatxa tortellinis_carne salmo_grillat amanida_cesar - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible amanida_catalana xai_rostit)
      (incompatible amanida_catalana bacalla_amb_tomate)
      (incompatible amanida_catalana pollastre_a_la_planxa)
      (incompatible amanida_catalana salmo_grillat)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_marisc tortellinis_carne)
      (incompatible crema_de_carxofa xai_rostit)
      (incompatible crema_de_carxofa bacalla_amb_tomate)
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible hummus tortellinis_carne)
      (incompatible hummus salmo_grillat)
      (incompatible verdures_a_la_planxa xai_rostit)
      (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
      (incompatible verdures_a_la_planxa sopa_de_pedra)
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible escalivada_verdures pollastre_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible carpaccio_vedella sopa_de_pedra)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats tortellinis_carne)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible raviolis_ricotta crema_catalana)
      (incompatible raviolis_ricotta amanida_de_remolatxa)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible croquetes_carn sopa_de_peix)
      (platTipus amanida_catalana amanida)
      (platTipus crema_de_carbassa crema)
      (platTipus sopa_de_marisc sopa)
      (platTipus crema_de_carxofa crema)
      (platTipus hummus llegums)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus amanida_de_cogombre amanida)
      (platTipus escalivada_verdures verdures)
      (platTipus carpaccio_vedella carn)
      (platTipus cigrons_saltejats llegums)
      (platTipus raviolis_ricotta pasta)
      (platTipus croquetes_carn carn)
      (platTipus pennes_amb_pesto pasta)
      (platTipus xai_rostit carn)
      (platTipus truita_de_llenties llegums)
      (platTipus bacalla_amb_tomate peix)
      (platTipus crema_catalana crema)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus sopa_de_pedra sopa)
      (platTipus sopa_de_peix sopa)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus tortellinis_carne pasta)
      (platTipus salmo_grillat peix)
      (platTipus amanida_cesar amanida)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (platObligatori crema_catalana dimarts)
      (platObligatori pollastre_a_la_planxa dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )