(define (problem menu-ext3b-2)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  fajitas_verdures amanida_de_tomaquet crema_de_carxofa sopa_de_cigrons crema_espinacs crema_de_carbassa sopa_verdures raviolis_ricotta verdures_a_la_planxa gnocchi_pesto tallarins_carbonara amanida_catalana - primer
  truita_de_llenties tataki_verdures salmo_grillat sopa_ajo wok_verdures crema_taronja crema_avellana sopa_ceba estofat_soja truita_verdures parrillada_verdures hamburguesa_mongeta - segon
  amanida crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible fajitas_verdures sopa_ceba)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible sopa_de_cigrons tataki_verdures)
  (incompatible sopa_de_cigrons wok_verdures)
  (incompatible sopa_de_cigrons truita_verdures)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible crema_espinacs salmo_grillat)
  (incompatible crema_de_carbassa salmo_grillat)
  (incompatible sopa_verdures tataki_verdures)
  (incompatible sopa_verdures wok_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible raviolis_ricotta crema_avellana)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible gnocchi_pesto crema_taronja)
  (incompatible gnocchi_pesto crema_avellana)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible tallarins_carbonara crema_avellana)
  (incompatible amanida_catalana salmo_grillat)
  (platTipus fajitas_verdures verdures)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus crema_de_carxofa crema)
  (platTipus sopa_de_cigrons sopa)
  (platTipus crema_espinacs crema)
  (platTipus crema_de_carbassa crema)
  (platTipus sopa_verdures sopa)
  (platTipus raviolis_ricotta pasta)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus gnocchi_pesto pasta)
  (platTipus tallarins_carbonara pasta)
  (platTipus amanida_catalana amanida)
  (platTipus truita_de_llenties llegums)
  (platTipus tataki_verdures verdures)
  (platTipus salmo_grillat peix)
  (platTipus sopa_ajo sopa)
  (platTipus wok_verdures verdures)
  (platTipus crema_taronja crema)
  (platTipus crema_avellana crema)
  (platTipus sopa_ceba sopa)
  (platTipus estofat_soja llegums)
  (platTipus truita_verdures verdures)
  (platTipus parrillada_verdures verdures)
  (platTipus hamburguesa_mongeta llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (platObligatori verdures_a_la_planxa divendres)
  (platObligatori gnocchi_pesto dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )