(define (problem menu-ext3b-5)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  verdures_amb_salsa crema_de_carbassa verdures_a_la_planxa brocoli_allada fajitas_verdures sopa_miso amanida_catalana escalivada_verdures sopa_de_peix truita_potatge crema_de_carxofa crema_de_bolets - primer
  sopa_de_pedra truita_verdures faves_estofades crema_taronja botifarra_a_la_planxa crema_de_limon llenguado_amb_lima sopa_de_peix sopa_de_galets cuixa_ànec xai_rostit sopa_ajo - segon
  amanida carn crema llegums peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa sopa_de_galets)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa xai_rostit)
  (incompatible verdures_amb_salsa sopa_ajo)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa llenguado_amb_lima)
  (incompatible crema_de_carbassa cuixa_ànec)
  (incompatible crema_de_carbassa xai_rostit)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa xai_rostit)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible brocoli_allada sopa_de_pedra)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible brocoli_allada sopa_de_peix)
  (incompatible brocoli_allada sopa_de_galets)
  (incompatible brocoli_allada cuixa_ànec)
  (incompatible brocoli_allada xai_rostit)
  (incompatible brocoli_allada sopa_ajo)
  (incompatible fajitas_verdures sopa_de_pedra)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible fajitas_verdures xai_rostit)
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible sopa_miso truita_verdures)
  (incompatible amanida_catalana botifarra_a_la_planxa)
  (incompatible amanida_catalana llenguado_amb_lima)
  (incompatible amanida_catalana cuixa_ànec)
  (incompatible amanida_catalana xai_rostit)
  (incompatible escalivada_verdures sopa_de_pedra)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible escalivada_verdures sopa_de_galets)
  (incompatible escalivada_verdures cuixa_ànec)
  (incompatible escalivada_verdures xai_rostit)
  (incompatible escalivada_verdures sopa_ajo)
  (incompatible sopa_de_peix truita_verdures)
  (incompatible truita_potatge llenguado_amb_lima)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa llenguado_amb_lima)
  (incompatible crema_de_carxofa cuixa_ànec)
  (incompatible crema_de_carxofa xai_rostit)
  (incompatible crema_de_bolets botifarra_a_la_planxa)
  (incompatible crema_de_bolets llenguado_amb_lima)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible crema_de_bolets xai_rostit)
  (platTipus verdures_amb_salsa verdures)
  (platTipus crema_de_carbassa crema)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus brocoli_allada verdures)
  (platTipus fajitas_verdures verdures)
  (platTipus sopa_miso sopa)
  (platTipus amanida_catalana amanida)
  (platTipus escalivada_verdures verdures)
  (platTipus sopa_de_peix sopa)
  (platTipus truita_potatge llegums)
  (platTipus crema_de_carxofa crema)
  (platTipus crema_de_bolets crema)
  (platTipus sopa_de_pedra sopa)
  (platTipus truita_verdures verdures)
  (platTipus faves_estofades llegums)
  (platTipus crema_taronja crema)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus crema_de_limon crema)
  (platTipus llenguado_amb_lima peix)
  (platTipus sopa_de_peix sopa)
  (platTipus sopa_de_galets sopa)
  (platTipus cuixa_ànec carn)
  (platTipus xai_rostit carn)
  (platTipus sopa_ajo sopa)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (platObligatori escalivada_verdures dimarts)
  (platObligatori verdures_amb_salsa dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )