(define (problem menu-ext3b-4)
        (:domain menuext3b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_asiatica amanida_de_tomaquet cigrons_saltejats amanida_quinoa raviolis_ricotta amanida_de_cogombre sopa_de_cigrons penne_arrabiata verdures_a_la_planxa escalivada_verdures sopa_miso hummus - primer
  crema_de_limon sopa_ajo xai_rostit truita_verdures wok_verdures parrillada_verdures sopa_de_galets truita_de_llenties sopa_de_peix crema_taronja estofat_soja salmo_grillat - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible amanida_asiatica xai_rostit)
  (incompatible amanida_asiatica salmo_grillat)
  (incompatible amanida_de_tomaquet xai_rostit)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible amanida_quinoa xai_rostit)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible raviolis_ricotta crema_de_limon)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible amanida_de_cogombre xai_rostit)
  (incompatible amanida_de_cogombre salmo_grillat)
  (incompatible sopa_de_cigrons truita_verdures)
  (incompatible sopa_de_cigrons wok_verdures)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible penne_arrabiata crema_de_limon)
  (incompatible penne_arrabiata crema_taronja)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible verdures_a_la_planxa xai_rostit)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible escalivada_verdures sopa_ajo)
  (incompatible escalivada_verdures xai_rostit)
  (incompatible escalivada_verdures sopa_de_galets)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible sopa_miso truita_verdures)
  (incompatible sopa_miso wok_verdures)
  (incompatible sopa_miso parrillada_verdures)
  (incompatible hummus salmo_grillat)
  (platTipus amanida_asiatica amanida)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus cigrons_saltejats llegums)
  (platTipus amanida_quinoa amanida)
  (platTipus raviolis_ricotta pasta)
  (platTipus amanida_de_cogombre amanida)
  (platTipus sopa_de_cigrons sopa)
  (platTipus penne_arrabiata pasta)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus escalivada_verdures verdures)
  (platTipus sopa_miso sopa)
  (platTipus hummus llegums)
  (platTipus crema_de_limon crema)
  (platTipus sopa_ajo sopa)
  (platTipus xai_rostit carn)
  (platTipus truita_verdures verdures)
  (platTipus wok_verdures verdures)
  (platTipus parrillada_verdures verdures)
  (platTipus sopa_de_galets sopa)
  (platTipus truita_de_llenties llegums)
  (platTipus sopa_de_peix sopa)
  (platTipus crema_taronja crema)
  (platTipus estofat_soja llegums)
  (platTipus salmo_grillat peix)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (platObligatori sopa_ajo dimarts)
  (platObligatori truita_de_llenties divendres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )