(define (problem menu-ext1b-3)
        (:domain menuext1b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  verdures_amb_salsa hummus crema_espinacs escalivada_verdures fajitas_verdures tallarins_carbonara gnocchi_pesto crema_de_carabasso amanida_quinoa sopa_de_cigrons crema_de_carbassa raviolis_ricotta - primer
  estofat_soja bacalla_amb_tomate crema_catalana turbot_planxa pollastre_a_la_planxa llenguado_amb_lima parrillada_verdures crema_taronja xai_rostit sopa_ajo sopa_de_peix crema_de_limon - segon
)

        (:init
  (incompatible verdures_amb_salsa pollastre_a_la_planxa)
  (incompatible verdures_amb_salsa xai_rostit)
  (incompatible verdures_amb_salsa sopa_ajo)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible hummus bacalla_amb_tomate)
  (incompatible hummus turbot_planxa)
  (incompatible hummus llenguado_amb_lima)
  (incompatible crema_espinacs bacalla_amb_tomate)
  (incompatible crema_espinacs turbot_planxa)
  (incompatible crema_espinacs pollastre_a_la_planxa)
  (incompatible crema_espinacs llenguado_amb_lima)
  (incompatible crema_espinacs xai_rostit)
  (incompatible escalivada_verdures pollastre_a_la_planxa)
  (incompatible escalivada_verdures xai_rostit)
  (incompatible escalivada_verdures sopa_ajo)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible fajitas_verdures pollastre_a_la_planxa)
  (incompatible fajitas_verdures xai_rostit)
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible tallarins_carbonara crema_catalana)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible tallarins_carbonara crema_de_limon)
  (incompatible gnocchi_pesto crema_catalana)
  (incompatible gnocchi_pesto crema_taronja)
  (incompatible gnocchi_pesto crema_de_limon)
  (incompatible crema_de_carabasso bacalla_amb_tomate)
  (incompatible crema_de_carabasso turbot_planxa)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible crema_de_carabasso llenguado_amb_lima)
  (incompatible crema_de_carabasso xai_rostit)
  (incompatible amanida_quinoa bacalla_amb_tomate)
  (incompatible amanida_quinoa turbot_planxa)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible amanida_quinoa llenguado_amb_lima)
  (incompatible amanida_quinoa xai_rostit)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible crema_de_carbassa bacalla_amb_tomate)
  (incompatible crema_de_carbassa turbot_planxa)
  (incompatible crema_de_carbassa pollastre_a_la_planxa)
  (incompatible crema_de_carbassa llenguado_amb_lima)
  (incompatible crema_de_carbassa xai_rostit)
  (incompatible raviolis_ricotta crema_catalana)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible raviolis_ricotta crema_de_limon)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )