      (define (problem menu-ext1b-2)
        (:domain menuext1b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  amanida_catalana sopa_de_marisc tataki_salmo crema_de_carxofa verdures_a_la_planxa crema_de_carbassa macarrons_forn estofat_llenties sopa_de_peix amanida_de_tomaquet cigrons_saltejats croquetes_carn - primer
  crema_de_xocolata salmo_grillat bacalla_amb_tomate amanida_cesar truita_de_llenties pennes_amb_pesto llenguado_amb_lima faves_estofades crema_catalana botifarra_a_la_planxa parrillada_verdures pollastre_a_la_planxa - segon
)

        (:init
      (incompatible amanida_catalana salmo_grillat)
      (incompatible amanida_catalana bacalla_amb_tomate)
      (incompatible amanida_catalana llenguado_amb_lima)
      (incompatible amanida_catalana botifarra_a_la_planxa)
      (incompatible amanida_catalana pollastre_a_la_planxa)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo crema_catalana)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible tataki_salmo pollastre_a_la_planxa)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible crema_de_carxofa bacalla_amb_tomate)
      (incompatible crema_de_carxofa llenguado_amb_lima)
      (incompatible crema_de_carxofa botifarra_a_la_planxa)
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa llenguado_amb_lima)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn amanida_cesar)
      (incompatible macarrons_forn crema_catalana)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet llenguado_amb_lima)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats llenguado_amb_lima)
      (incompatible croquetes_carn parrillada_verdures)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )