(define (problem menu-ext1b-4)
        (:domain menuext1b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  crema_de_carxofa fajitas_verdures penne_arrabiata amanida_de_tomaquet escalivada_verdures amanida_fasols macarrons_forn verdures_a_la_planxa raviolis_ricotta amanida_quinoa hummus truita_potatge - primer
  salmo_grillat sopa_de_pedra sopa_ceba bacalla_amb_tomate turbot_planxa filet_porc sopa_de_galets wok_verdures hamburguesa_mongeta sopa_ajo botifarra_a_la_planxa xai_rostit - segon
)

        (:init
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible crema_de_carxofa bacalla_amb_tomate)
  (incompatible crema_de_carxofa turbot_planxa)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa xai_rostit)
  (incompatible fajitas_verdures sopa_de_pedra)
  (incompatible fajitas_verdures sopa_ceba)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible fajitas_verdures sopa_ajo)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures xai_rostit)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible amanida_de_tomaquet bacalla_amb_tomate)
  (incompatible amanida_de_tomaquet turbot_planxa)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet xai_rostit)
  (incompatible escalivada_verdures sopa_de_pedra)
  (incompatible escalivada_verdures sopa_ceba)
  (incompatible escalivada_verdures filet_porc)
  (incompatible escalivada_verdures sopa_de_galets)
  (incompatible escalivada_verdures sopa_ajo)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures xai_rostit)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible amanida_fasols bacalla_amb_tomate)
  (incompatible amanida_fasols turbot_planxa)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible verdures_a_la_planxa filet_porc)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa xai_rostit)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible amanida_quinoa bacalla_amb_tomate)
  (incompatible amanida_quinoa turbot_planxa)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa botifarra_a_la_planxa)
  (incompatible amanida_quinoa xai_rostit)
  (incompatible hummus salmo_grillat)
  (incompatible hummus bacalla_amb_tomate)
  (incompatible hummus turbot_planxa)
  (incompatible truita_potatge salmo_grillat)
  (incompatible truita_potatge bacalla_amb_tomate)
  (incompatible truita_potatge turbot_planxa)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )