      (define (problem menu-ext1b-3)
        (:domain menuext1b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  macarrons_forn sopa_de_cigrons amanida_de_cogombre escalivada_verdures hummus amanida_de_tomaquet estofat_llenties ceviche_tonyina llobarro_forn croquetes_carn sopa_de_marisc botifarra_brasa - primer
  crema_de_limon parrillada_verdures truita_verdures llenguado_amb_lima salmo_grillat crema_de_xocolata sopa_de_peix bacalla_amb_tomate xai_rostit crema_catalana truita_de_llenties pollastre_a_la_planxa - segon
)

        (:init
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn crema_catalana)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible amanida_de_cogombre llenguado_amb_lima)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible escalivada_verdures pollastre_a_la_planxa)
      (incompatible hummus llenguado_amb_lima)
      (incompatible hummus salmo_grillat)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet llenguado_amb_lima)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible ceviche_tonyina crema_de_limon)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible ceviche_tonyina xai_rostit)
      (incompatible ceviche_tonyina crema_catalana)
      (incompatible ceviche_tonyina pollastre_a_la_planxa)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn xai_rostit)
      (incompatible llobarro_forn crema_catalana)
      (incompatible llobarro_forn pollastre_a_la_planxa)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible croquetes_carn truita_verdures)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc truita_verdures)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible botifarra_brasa sopa_de_peix)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )