(define (problem menuext4b-tc2)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
raviolis_ricotta crema_de_carbassa amanida_de_tomaquet amanida_asiatica gnocchi_pesto sopa_miso verdures_a_la_planxa escalivada_verdures crema_espinacs penne_arrabiata - primer
turbot_planxa orata_forno sopa_ceba parrillada_verdures crema_de_xocolata filet_porc crema_catalana crema_taronja estofat_cigrons estofat_soja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_a_la_planxa filet_porc)
    (incompatible amanida_de_tomaquet filet_porc)
    (incompatible gnocchi_pesto crema_de_xocolata)
    (incompatible raviolis_ricotta crema_taronja)
    (incompatible amanida_de_tomaquet turbot_planxa)
    (incompatible raviolis_ricotta crema_de_xocolata)
    (incompatible crema_de_carbassa filet_porc)
    (incompatible crema_espinacs turbot_planxa)
    (platTipus raviolis_ricotta pasta)
    (platTipus crema_de_carbassa crema)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus amanida_asiatica amanida)
    (platTipus gnocchi_pesto pasta)
    (platTipus sopa_miso sopa)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus escalivada_verdures verdures)
    (platTipus crema_espinacs crema)
    (platTipus penne_arrabiata pasta)
    (platTipus turbot_planxa peix)
    (platTipus orata_forno peix)
    (platTipus sopa_ceba sopa)
    (platTipus parrillada_verdures verdures)
    (platTipus crema_de_xocolata crema)
    (platTipus filet_porc carn)
    (platTipus crema_catalana crema)
    (platTipus crema_taronja crema)
    (platTipus estofat_cigrons llegums)
    (platTipus estofat_soja llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori verdures_a_la_planxa dimarts)
    (platObligatori gnocchi_pesto dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories raviolis_ricotta) 680)
    (= (calories crema_de_carbassa) 350)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories amanida_asiatica) 330)
    (= (calories gnocchi_pesto) 740)
    (= (calories sopa_miso) 500)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories escalivada_verdures) 350)
    (= (calories crema_espinacs) 380)
    (= (calories penne_arrabiata) 720)
    (= (calories turbot_planxa) 790)
    (= (calories orata_forno) 800)
    (= (calories sopa_ceba) 450)
    (= (calories parrillada_verdures) 550)
    (= (calories crema_de_xocolata) 450)
    (= (calories filet_porc) 900)
    (= (calories crema_catalana) 440)
    (= (calories crema_taronja) 410)
    (= (calories estofat_cigrons) 690)
    (= (calories estofat_soja) 700)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )