(define (problem menuext4b-tc5)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_de_tomaquet hummus crema_de_carbassa amanida_catalana fajitas_verdures escalivada_verdures penne_arrabiata sopa_de_peix brocoli_allada estofat_llenties - primer
crema_de_limon crema_avellana filet_porc llenguado_amb_lima parrillada_verdures sopa_de_pedra bacalla_amb_tomaquet truita_verdures turbot_planxa truita_de_llenties - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible estofat_llenties turbot_planxa)
    (incompatible hummus llenguado_amb_lima)
    (incompatible estofat_llenties bacalla_amb_tomaquet)
    (incompatible amanida_catalana filet_porc)
    (incompatible penne_arrabiata crema_de_limon)
    (incompatible amanida_de_tomaquet turbot_planxa)
    (incompatible crema_de_carbassa llenguado_amb_lima)
    (incompatible amanida_catalana llenguado_amb_lima)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus hummus llegums)
    (platTipus crema_de_carbassa crema)
    (platTipus amanida_catalana amanida)
    (platTipus fajitas_verdures verdures)
    (platTipus escalivada_verdures verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus sopa_de_peix sopa)
    (platTipus brocoli_allada verdures)
    (platTipus estofat_llenties llegums)
    (platTipus crema_de_limon crema)
    (platTipus crema_avellana crema)
    (platTipus filet_porc carn)
    (platTipus llenguado_amb_lima peix)
    (platTipus parrillada_verdures verdures)
    (platTipus sopa_de_pedra sopa)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus truita_verdures verdures)
    (platTipus turbot_planxa peix)
    (platTipus truita_de_llenties llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori amanida_de_tomaquet divendres)
    (platObligatori truita_verdures dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories hummus) 530)
    (= (calories crema_de_carbassa) 350)
    (= (calories amanida_catalana) 300)
    (= (calories fajitas_verdures) 390)
    (= (calories escalivada_verdures) 350)
    (= (calories penne_arrabiata) 720)
    (= (calories sopa_de_peix) 450)
    (= (calories brocoli_allada) 360)
    (= (calories estofat_llenties) 600)
    (= (calories crema_de_limon) 430)
    (= (calories crema_avellana) 480)
    (= (calories filet_porc) 900)
    (= (calories llenguado_amb_lima) 750)
    (= (calories parrillada_verdures) 550)
    (= (calories sopa_de_pedra) 500)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories truita_verdures) 500)
    (= (calories turbot_planxa) 790)
    (= (calories truita_de_llenties) 620)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )