(define (problem menuext4b-tc4)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_espinacs sopa_de_peix crema_de_bolets verdures_amb_salsa brocoli_allada sopa_verdures amanida_fasols sopa_de_cigrons amanida_de_tomaquet escalivada_verdures - primer
filet_porc sopa_ceba botifarra_a_la_planxa estofat_cigrons sopa_ajo sopa_de_pedra truita_verdures llenguado_amb_lima sopa_de_peix crema_de_limon - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_amb_salsa filet_porc)
    (incompatible escalivada_verdures sopa_de_peix)
    (incompatible crema_espinacs llenguado_amb_lima)
    (incompatible verdures_amb_salsa botifarra_a_la_planxa)
    (incompatible brocoli_allada botifarra_a_la_planxa)
    (incompatible escalivada_verdures sopa_ajo)
    (incompatible brocoli_allada sopa_ceba)
    (incompatible crema_espinacs botifarra_a_la_planxa)
    (platTipus crema_espinacs crema)
    (platTipus sopa_de_peix sopa)
    (platTipus crema_de_bolets crema)
    (platTipus verdures_amb_salsa verdures)
    (platTipus brocoli_allada verdures)
    (platTipus sopa_verdures sopa)
    (platTipus amanida_fasols llegums)
    (platTipus sopa_de_cigrons sopa)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus escalivada_verdures verdures)
    (platTipus filet_porc carn)
    (platTipus sopa_ceba sopa)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus estofat_cigrons llegums)
    (platTipus sopa_ajo sopa)
    (platTipus sopa_de_pedra sopa)
    (platTipus truita_verdures verdures)
    (platTipus llenguado_amb_lima peix)
    (platTipus crema_de_limon crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori crema_de_bolets dijous)
    (platObligatori escalivada_verdures divendres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_espinacs) 380)
    (= (calories sopa_de_peix) 520)
    (= (calories crema_de_bolets) 390)
    (= (calories verdures_amb_salsa) 380)
    (= (calories brocoli_allada) 360)
    (= (calories sopa_verdures) 480)
    (= (calories amanida_fasols) 560)
    (= (calories sopa_de_cigrons) 530)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories escalivada_verdures) 350)
    (= (calories filet_porc) 900)
    (= (calories sopa_ceba) 450)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories estofat_cigrons) 690)
    (= (calories sopa_ajo) 490)
    (= (calories sopa_de_pedra) 500)
    (= (calories truita_verdures) 500)
    (= (calories llenguado_amb_lima) 750)
    (= (calories crema_de_limon) 430)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )