(define (problem menuext4b-tc2)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
penne_arrabiata cigrons_saltejats brocoli_allada hummus raviolis_ricotta verdures_a_la_planxa sopa_miso crema_de_bolets amanida_fasols sopa_verdures - primer
llenguado_amb_lima cuixa_ànec pollastre_a_la_planxa sopa_de_galets crema_taronja orata_forno wok_verdures estofat_soja crema_de_limon crema_catalana - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_a_la_planxa sopa_de_galets)
    (incompatible verdures_a_la_planxa cuixa_ànec)
    (incompatible crema_de_bolets orata_forno)
    (incompatible penne_arrabiata crema_catalana)
    (incompatible crema_de_bolets cuixa_ànec)
    (incompatible crema_de_bolets pollastre_a_la_planxa)
    (incompatible raviolis_ricotta crema_de_limon)
    (incompatible sopa_miso wok_verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus cigrons_saltejats llegums)
    (platTipus brocoli_allada verdures)
    (platTipus hummus llegums)
    (platTipus raviolis_ricotta pasta)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus sopa_miso sopa)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_fasols llegums)
    (platTipus sopa_verdures sopa)
    (platTipus llenguado_amb_lima peix)
    (platTipus cuixa_ànec carn)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus sopa_de_galets sopa)
    (platTipus crema_taronja crema)
    (platTipus orata_forno peix)
    (platTipus wok_verdures verdures)
    (platTipus estofat_soja llegums)
    (platTipus crema_de_limon crema)
    (platTipus crema_catalana crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori raviolis_ricotta divendres)
    (platObligatori crema_catalana dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories penne_arrabiata) 720)
    (= (calories cigrons_saltejats) 570)
    (= (calories brocoli_allada) 360)
    (= (calories hummus) 530)
    (= (calories raviolis_ricotta) 680)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories sopa_miso) 500)
    (= (calories crema_de_bolets) 390)
    (= (calories amanida_fasols) 560)
    (= (calories sopa_verdures) 480)
    (= (calories llenguado_amb_lima) 750)
    (= (calories cuixa_ànec) 980)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories sopa_de_galets) 470)
    (= (calories crema_taronja) 410)
    (= (calories orata_forno) 800)
    (= (calories wok_verdures) 540)
    (= (calories estofat_soja) 700)
    (= (calories crema_de_limon) 430)
    (= (calories crema_catalana) 440)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )