(define (problem menuext4b-tc2)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carbassa sopa_de_peix crema_de_carxofa amanida_de_cogombre escalivada_verdures hummus tallarins_carbonara penne_arrabiata truita_potatge raviolis_ricotta - primer
botifarra_a_la_planxa estofat_soja salmo_grillat filet_porc orata_forno parrillada_verdures wok_verdures truita_de_llenties pollastre_a_la_planxa cuixa_anec - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa filet_porc)
    (incompatible amanida_de_cogombre pollastre_a_la_planxa)
    (incompatible amanida_de_cogombre cuixa_anec)
    (incompatible crema_de_carbassa pollastre_a_la_planxa)
    (incompatible truita_potatge salmo_grillat)
    (incompatible crema_de_carbassa salmo_grillat)
    (incompatible escalivada_verdures pollastre_a_la_planxa)
    (incompatible crema_de_carbassa botifarra_a_la_planxa)
    (platTipus crema_de_carbassa crema)
    (platTipus sopa_de_peix sopa)
    (platTipus crema_de_carxofa crema)
    (platTipus amanida_de_cogombre amanida)
    (platTipus escalivada_verdures verdures)
    (platTipus hummus llegums)
    (platTipus tallarins_carbonara pasta)
    (platTipus penne_arrabiata pasta)
    (platTipus truita_potatge llegums)
    (platTipus raviolis_ricotta pasta)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus estofat_soja llegums)
    (platTipus salmo_grillat peix)
    (platTipus filet_porc carn)
    (platTipus orata_forno peix)
    (platTipus parrillada_verdures verdures)
    (platTipus wok_verdures verdures)
    (platTipus truita_de_llenties llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus cuixa_anec carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori salmo_grillat dijous)
    (platObligatori pollastre_a_la_planxa dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_de_carbassa) 350)
    (= (calories sopa_de_peix) 450)
    (= (calories crema_de_carxofa) 320)
    (= (calories amanida_de_cogombre) 260)
    (= (calories escalivada_verdures) 350)
    (= (calories hummus) 530)
    (= (calories tallarins_carbonara) 700)
    (= (calories penne_arrabiata) 720)
    (= (calories truita_potatge) 580)
    (= (calories raviolis_ricotta) 680)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories estofat_soja) 700)
    (= (calories salmo_grillat) 780)
    (= (calories filet_porc) 900)
    (= (calories orata_forno) 800)
    (= (calories parrillada_verdures) 550)
    (= (calories wok_verdures) 540)
    (= (calories truita_de_llenties) 620)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories cuixa_anec) 980)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )