(define (problem menuext4b-tc3)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
cigrons_saltejats fajitas_verdures crema_de_carbassa verdures_amb_salsa sopa_de_marisc truita_potatge sopa_de_peix hummus macarrons_forn amanida_fasols - primer
orata_forno faves_estofades crema_avellana cuixa_anec filet_porc xai_rostit curry_verdures crema_taronja sopa_ajo pollastre_a_la_planxa - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible fajitas_verdures filet_porc)
    (incompatible verdures_amb_salsa sopa_ajo)
    (incompatible truita_potatge orata_forno)
    (incompatible fajitas_verdures xai_rostit)
    (incompatible verdures_amb_salsa cuixa_anec)
    (incompatible hummus orata_forno)
    (incompatible verdures_amb_salsa pollastre_a_la_planxa)
    (incompatible crema_de_carbassa orata_forno)
    (platTipus cigrons_saltejats llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus verdures_amb_salsa verdures)
    (platTipus sopa_de_marisc sopa)
    (platTipus truita_potatge llegums)
    (platTipus sopa_de_peix sopa)
    (platTipus hummus llegums)
    (platTipus macarrons_forn pasta)
    (platTipus amanida_fasols llegums)
    (platTipus orata_forno peix)
    (platTipus faves_estofades llegums)
    (platTipus crema_avellana crema)
    (platTipus cuixa_anec carn)
    (platTipus filet_porc carn)
    (platTipus xai_rostit carn)
    (platTipus curry_verdures verdures)
    (platTipus crema_taronja crema)
    (platTipus sopa_ajo sopa)
    (platTipus pollastre_a_la_planxa carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_ajo dimarts)
    (platObligatori curry_verdures dijous)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories cigrons_saltejats) 570)
    (= (calories fajitas_verdures) 390)
    (= (calories crema_de_carbassa) 350)
    (= (calories verdures_amb_salsa) 380)
    (= (calories sopa_de_marisc) 560)
    (= (calories truita_potatge) 580)
    (= (calories sopa_de_peix) 450)
    (= (calories hummus) 530)
    (= (calories macarrons_forn) 650)
    (= (calories amanida_fasols) 560)
    (= (calories orata_forno) 800)
    (= (calories faves_estofades) 730)
    (= (calories crema_avellana) 480)
    (= (calories cuixa_anec) 980)
    (= (calories filet_porc) 900)
    (= (calories xai_rostit) 1000)
    (= (calories curry_verdures) 580)
    (= (calories crema_taronja) 410)
    (= (calories sopa_ajo) 490)
    (= (calories pollastre_a_la_planxa) 940)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )