(define (problem menuext4b-tc5)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carabasso tallarins_carbonara penne_arrabiata verdures_a_la_planxa amanida_quinoa macarrons_forn sopa_de_marisc amanida_de_cogombre gnocchi_pesto amanida_catalana - primer
botifarra_a_la_planxa sopa_de_peix wok_verdures crema_taronja turbot_planxa estofat_cigrons truita_verdures pollastre_a_la_planxa estofat_soja cuixa_anec - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible macarrons_forn crema_taronja)
    (incompatible amanida_catalana turbot_planxa)
    (incompatible amanida_de_cogombre cuixa_anec)
    (incompatible amanida_de_cogombre pollastre_a_la_planxa)
    (incompatible amanida_quinoa botifarra_a_la_planxa)
    (incompatible crema_de_carabasso pollastre_a_la_planxa)
    (incompatible amanida_quinoa cuixa_anec)
    (incompatible amanida_quinoa pollastre_a_la_planxa)
    (platTipus crema_de_carabasso crema)
    (platTipus tallarins_carbonara pasta)
    (platTipus penne_arrabiata pasta)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus amanida_quinoa amanida)
    (platTipus macarrons_forn pasta)
    (platTipus sopa_de_marisc sopa)
    (platTipus amanida_de_cogombre amanida)
    (platTipus gnocchi_pesto pasta)
    (platTipus amanida_catalana amanida)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus sopa_de_peix sopa)
    (platTipus wok_verdures verdures)
    (platTipus crema_taronja crema)
    (platTipus turbot_planxa peix)
    (platTipus estofat_cigrons llegums)
    (platTipus truita_verdures verdures)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus estofat_soja llegums)
    (platTipus cuixa_anec carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori cuixa_anec dimecres)
    (platObligatori truita_verdures dimarts)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_de_carabasso) 330)
    (= (calories tallarins_carbonara) 700)
    (= (calories penne_arrabiata) 720)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories amanida_quinoa) 360)
    (= (calories macarrons_forn) 650)
    (= (calories sopa_de_marisc) 560)
    (= (calories amanida_de_cogombre) 260)
    (= (calories gnocchi_pesto) 740)
    (= (calories amanida_catalana) 300)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories sopa_de_peix) 520)
    (= (calories wok_verdures) 540)
    (= (calories crema_taronja) 410)
    (= (calories turbot_planxa) 790)
    (= (calories estofat_cigrons) 690)
    (= (calories truita_verdures) 500)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories estofat_soja) 700)
    (= (calories cuixa_anec) 980)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )