(define (problem menuext4b-tc1)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_fasols cigrons_saltejats fajitas_verdures hummus crema_de_bolets amanida_asiatica sopa_verdures tallarins_carbonara crema_espinacs escalivada_verdures - primer
orata_forno truita_de_llenties xai_rostit parrillada_verdures salmo_grillat wok_verdures cuixa_anec botifarra_a_la_planxa crema_catalana crema_de_limon - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_bolets xai_rostit)
    (incompatible amanida_fasols orata_forno)
    (incompatible amanida_asiatica botifarra_a_la_planxa)
    (incompatible escalivada_verdures xai_rostit)
    (incompatible fajitas_verdures cuixa_anec)
    (incompatible escalivada_verdures botifarra_a_la_planxa)
    (incompatible cigrons_saltejats salmo_grillat)
    (incompatible crema_espinacs cuixa_anec)
    (platTipus amanida_fasols llegums)
    (platTipus cigrons_saltejats llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus hummus llegums)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_asiatica amanida)
    (platTipus sopa_verdures sopa)
    (platTipus tallarins_carbonara pasta)
    (platTipus crema_espinacs crema)
    (platTipus escalivada_verdures verdures)
    (platTipus orata_forno peix)
    (platTipus truita_de_llenties llegums)
    (platTipus xai_rostit carn)
    (platTipus parrillada_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus wok_verdures verdures)
    (platTipus cuixa_anec carn)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus crema_catalana crema)
    (platTipus crema_de_limon crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori parrillada_verdures dijous)
    (platObligatori orata_forno dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_fasols) 560)
    (= (calories cigrons_saltejats) 570)
    (= (calories fajitas_verdures) 390)
    (= (calories hummus) 530)
    (= (calories crema_de_bolets) 390)
    (= (calories amanida_asiatica) 330)
    (= (calories sopa_verdures) 480)
    (= (calories tallarins_carbonara) 700)
    (= (calories crema_espinacs) 380)
    (= (calories escalivada_verdures) 350)
    (= (calories orata_forno) 800)
    (= (calories truita_de_llenties) 620)
    (= (calories xai_rostit) 1000)
    (= (calories parrillada_verdures) 550)
    (= (calories salmo_grillat) 780)
    (= (calories wok_verdures) 540)
    (= (calories cuixa_anec) 980)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories crema_catalana) 440)
    (= (calories crema_de_limon) 430)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )