(define (problem menuext4b-tc4)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
estofat_llenties amanida_fasols sopa_de_peix fajitas_verdures crema_de_carbassa sopa_de_cigrons crema_de_bolets sopa_de_marisc macarrons_forn sopa_miso - primer
sopa_de_galets xai_rostit crema_catalana faves_estofades filet_porc pollastre_a_la_planxa hamburguesa_mongeta crema_avellana curry_verdures sopa_ajo - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa xai_rostit)
    (incompatible fajitas_verdures filet_porc)
    (incompatible fajitas_verdures pollastre_a_la_planxa)
    (incompatible sopa_de_cigrons curry_verdures)
    (incompatible fajitas_verdures sopa_de_galets)
    (incompatible macarrons_forn crema_catalana)
    (incompatible sopa_de_marisc curry_verdures)
    (incompatible crema_de_bolets xai_rostit)
    (platTipus estofat_llenties llegums)
    (platTipus amanida_fasols llegums)
    (platTipus sopa_de_peix sopa)
    (platTipus fajitas_verdures verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus sopa_de_cigrons sopa)
    (platTipus crema_de_bolets crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus macarrons_forn pasta)
    (platTipus sopa_miso sopa)
    (platTipus sopa_de_galets sopa)
    (platTipus xai_rostit carn)
    (platTipus crema_catalana crema)
    (platTipus faves_estofades llegums)
    (platTipus filet_porc carn)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus crema_avellana crema)
    (platTipus curry_verdures verdures)
    (platTipus sopa_ajo sopa)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori macarrons_forn dilluns)
    (platObligatori sopa_de_peix dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories estofat_llenties) 600)
    (= (calories amanida_fasols) 560)
    (= (calories sopa_de_peix) 450)
    (= (calories fajitas_verdures) 390)
    (= (calories crema_de_carbassa) 350)
    (= (calories sopa_de_cigrons) 530)
    (= (calories crema_de_bolets) 390)
    (= (calories sopa_de_marisc) 560)
    (= (calories macarrons_forn) 650)
    (= (calories sopa_miso) 500)
    (= (calories sopa_de_galets) 470)
    (= (calories xai_rostit) 1000)
    (= (calories crema_catalana) 440)
    (= (calories faves_estofades) 730)
    (= (calories filet_porc) 900)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories crema_avellana) 480)
    (= (calories curry_verdures) 580)
    (= (calories sopa_ajo) 490)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )