(define (problem menuext4b-tc1)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
hummus fajitas_verdures brocoli_allada crema_de_carxofa sopa_de_peix sopa_miso verdures_a_la_planxa penne_arrabiata estofat_llenties crema_de_carbassa - primer
cuixa_ànec tataki_verdures faves_estofades truita_verdures crema_de_limon salmo_grillat orata_forno crema_taronja pollastre_a_la_planxa xai_rostit - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible sopa_miso truita_verdures)
    (incompatible estofat_llenties orata_forno)
    (incompatible brocoli_allada cuixa_ànec)
    (incompatible brocoli_allada pollastre_a_la_planxa)
    (incompatible crema_de_carxofa salmo_grillat)
    (incompatible crema_de_carxofa cuixa_ànec)
    (incompatible estofat_llenties salmo_grillat)
    (incompatible sopa_miso tataki_verdures)
    (platTipus hummus llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus brocoli_allada verdures)
    (platTipus crema_de_carxofa crema)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_miso sopa)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus estofat_llenties llegums)
    (platTipus crema_de_carbassa crema)
    (platTipus cuixa_ànec carn)
    (platTipus tataki_verdures verdures)
    (platTipus faves_estofades llegums)
    (platTipus truita_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus salmo_grillat peix)
    (platTipus orata_forno peix)
    (platTipus crema_taronja crema)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus xai_rostit carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori truita_verdures dimarts)
    (platObligatori sopa_miso dijous)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories hummus) 530)
    (= (calories fajitas_verdures) 390)
    (= (calories brocoli_allada) 360)
    (= (calories crema_de_carxofa) 320)
    (= (calories sopa_de_peix) 450)
    (= (calories sopa_miso) 500)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories penne_arrabiata) 720)
    (= (calories estofat_llenties) 600)
    (= (calories crema_de_carbassa) 350)
    (= (calories cuixa_ànec) 980)
    (= (calories tataki_verdures) 520)
    (= (calories faves_estofades) 730)
    (= (calories truita_verdures) 500)
    (= (calories crema_de_limon) 430)
    (= (calories salmo_grillat) 780)
    (= (calories orata_forno) 800)
    (= (calories crema_taronja) 410)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories xai_rostit) 1000)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )