(define (problem menuext4b-tc3)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
verdures_amb_salsa fajitas_verdures amanida_fasols crema_de_carxofa sopa_de_marisc cigrons_saltejats crema_de_carabasso crema_de_bolets hummus amanida_catalana - primer
bacalla_amb_tomaquet crema_de_limon sopa_de_peix hamburguesa_mongeta llenguado_amb_lima crema_catalana sopa_ceba estofat_soja parrillada_verdures crema_taronja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_fasols bacalla_amb_tomaquet)
    (incompatible verdures_amb_salsa sopa_de_peix)
    (incompatible sopa_de_marisc parrillada_verdures)
    (incompatible cigrons_saltejats llenguado_amb_lima)
    (incompatible cigrons_saltejats bacalla_amb_tomaquet)
    (incompatible crema_de_carxofa llenguado_amb_lima)
    (incompatible crema_de_bolets bacalla_amb_tomaquet)
    (incompatible verdures_amb_salsa sopa_ceba)
    (platTipus verdures_amb_salsa verdures)
    (platTipus fajitas_verdures verdures)
    (platTipus amanida_fasols llegums)
    (platTipus crema_de_carxofa crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus cigrons_saltejats llegums)
    (platTipus crema_de_carabasso crema)
    (platTipus crema_de_bolets crema)
    (platTipus hummus llegums)
    (platTipus amanida_catalana amanida)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus crema_de_limon crema)
    (platTipus sopa_de_peix sopa)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus llenguado_amb_lima peix)
    (platTipus crema_catalana crema)
    (platTipus sopa_ceba sopa)
    (platTipus estofat_soja llegums)
    (platTipus parrillada_verdures verdures)
    (platTipus crema_taronja crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori fajitas_verdures dilluns)
    (platObligatori crema_taronja dijous)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories verdures_amb_salsa) 380)
    (= (calories fajitas_verdures) 390)
    (= (calories amanida_fasols) 560)
    (= (calories crema_de_carxofa) 320)
    (= (calories sopa_de_marisc) 560)
    (= (calories cigrons_saltejats) 570)
    (= (calories crema_de_carabasso) 330)
    (= (calories crema_de_bolets) 390)
    (= (calories hummus) 530)
    (= (calories amanida_catalana) 300)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories crema_de_limon) 430)
    (= (calories sopa_de_peix) 520)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories llenguado_amb_lima) 750)
    (= (calories crema_catalana) 440)
    (= (calories sopa_ceba) 450)
    (= (calories estofat_soja) 700)
    (= (calories parrillada_verdures) 550)
    (= (calories crema_taronja) 410)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )