(define (problem menuext4b-tc1)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_de_peix crema_de_carxofa fajitas_verdures sopa_de_cigrons sopa_verdures amanida_quinoa crema_de_carbassa verdures_a_la_planxa penne_arrabiata amanida_de_tomaquet - primer
faves_estofades tataki_verdures bacalla_amb_tomaquet estofat_cigrons salmo_grillat truita_de_llenties filet_porc crema_de_xocolata crema_taronja orata_forno - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carxofa salmo_grillat)
    (incompatible penne_arrabiata crema_de_xocolata)
    (incompatible crema_de_carxofa bacalla_amb_tomaquet)
    (incompatible crema_de_carxofa filet_porc)
    (incompatible amanida_quinoa orata_forno)
    (incompatible sopa_de_cigrons tataki_verdures)
    (incompatible crema_de_carbassa filet_porc)
    (incompatible crema_de_carxofa orata_forno)
    (platTipus sopa_de_peix sopa)
    (platTipus crema_de_carxofa crema)
    (platTipus fajitas_verdures verdures)
    (platTipus sopa_de_cigrons sopa)
    (platTipus sopa_verdures sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus crema_de_carbassa crema)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus faves_estofades llegums)
    (platTipus tataki_verdures verdures)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus estofat_cigrons llegums)
    (platTipus salmo_grillat peix)
    (platTipus truita_de_llenties llegums)
    (platTipus filet_porc carn)
    (platTipus crema_de_xocolata crema)
    (platTipus crema_taronja crema)
    (platTipus orata_forno peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_de_peix dimarts)
    (platObligatori salmo_grillat divendres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories sopa_de_peix) 450)
    (= (calories crema_de_carxofa) 320)
    (= (calories fajitas_verdures) 390)
    (= (calories sopa_de_cigrons) 530)
    (= (calories sopa_verdures) 480)
    (= (calories amanida_quinoa) 360)
    (= (calories crema_de_carbassa) 350)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories penne_arrabiata) 720)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories faves_estofades) 730)
    (= (calories tataki_verdures) 520)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories estofat_cigrons) 690)
    (= (calories salmo_grillat) 780)
    (= (calories truita_de_llenties) 620)
    (= (calories filet_porc) 900)
    (= (calories crema_de_xocolata) 450)
    (= (calories crema_taronja) 410)
    (= (calories orata_forno) 800)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )