(define (problem menuext4b-tc5)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carbassa sopa_de_marisc penne_arrabiata crema_de_carabasso amanida_quinoa verdures_a_la_planxa crema_espinacs raviolis_ricotta truita_potatge cigrons_saltejats - primer
pollastre_a_la_planxa crema_catalana botifarra_a_la_planxa crema_de_xocolata estofat_cigrons curry_verdures crema_taronja truita_verdures tataki_verdures estofat_soja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa pollastre_a_la_planxa)
    (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
    (incompatible penne_arrabiata crema_taronja)
    (incompatible amanida_quinoa botifarra_a_la_planxa)
    (incompatible sopa_de_marisc tataki_verdures)
    (incompatible amanida_quinoa pollastre_a_la_planxa)
    (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
    (incompatible crema_de_carabasso pollastre_a_la_planxa)
    (platTipus crema_de_carbassa crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus penne_arrabiata pasta)
    (platTipus crema_de_carabasso crema)
    (platTipus amanida_quinoa amanida)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus crema_espinacs crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus truita_potatge llegums)
    (platTipus cigrons_saltejats llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus crema_catalana crema)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus crema_de_xocolata crema)
    (platTipus estofat_cigrons llegums)
    (platTipus curry_verdures verdures)
    (platTipus crema_taronja crema)
    (platTipus truita_verdures verdures)
    (platTipus tataki_verdures verdures)
    (platTipus estofat_soja llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori crema_espinacs divendres)
    (platObligatori truita_potatge dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_de_carbassa) 350)
    (= (calories sopa_de_marisc) 560)
    (= (calories penne_arrabiata) 720)
    (= (calories crema_de_carabasso) 330)
    (= (calories amanida_quinoa) 360)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories crema_espinacs) 380)
    (= (calories raviolis_ricotta) 680)
    (= (calories truita_potatge) 580)
    (= (calories cigrons_saltejats) 570)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories crema_catalana) 440)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories crema_de_xocolata) 450)
    (= (calories estofat_cigrons) 690)
    (= (calories curry_verdures) 580)
    (= (calories crema_taronja) 410)
    (= (calories truita_verdures) 500)
    (= (calories tataki_verdures) 520)
    (= (calories estofat_soja) 700)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )