(define (problem menuext4b-tc3)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_asiatica crema_espinacs sopa_de_marisc penne_arrabiata sopa_miso amanida_quinoa amanida_de_cogombre crema_de_carabasso estofat_llenties verdures_a_la_planxa - primer
bacalla_amb_tomaquet xai_rostit estofat_cigrons sopa_de_peix truita_verdures hamburguesa_mongeta parrillada_verdures salmo_grillat pollastre_a_la_planxa crema_taronja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible verdures_a_la_planxa sopa_de_peix)
    (incompatible amanida_de_cogombre bacalla_amb_tomaquet)
    (incompatible sopa_miso parrillada_verdures)
    (incompatible amanida_asiatica salmo_grillat)
    (incompatible verdures_a_la_planxa xai_rostit)
    (incompatible amanida_quinoa salmo_grillat)
    (incompatible crema_espinacs xai_rostit)
    (incompatible amanida_asiatica pollastre_a_la_planxa)
    (platTipus amanida_asiatica amanida)
    (platTipus crema_espinacs crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus penne_arrabiata pasta)
    (platTipus sopa_miso sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus amanida_de_cogombre amanida)
    (platTipus crema_de_carabasso crema)
    (platTipus estofat_llenties llegums)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus xai_rostit carn)
    (platTipus estofat_cigrons llegums)
    (platTipus sopa_de_peix sopa)
    (platTipus truita_verdures verdures)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus parrillada_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus crema_taronja crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_de_peix dimarts)
    (platObligatori amanida_de_cogombre dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_asiatica) 330)
    (= (calories crema_espinacs) 380)
    (= (calories sopa_de_marisc) 560)
    (= (calories penne_arrabiata) 720)
    (= (calories sopa_miso) 500)
    (= (calories amanida_quinoa) 360)
    (= (calories amanida_de_cogombre) 260)
    (= (calories crema_de_carabasso) 330)
    (= (calories estofat_llenties) 600)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories xai_rostit) 1000)
    (= (calories estofat_cigrons) 690)
    (= (calories sopa_de_peix) 520)
    (= (calories truita_verdures) 500)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories parrillada_verdures) 550)
    (= (calories salmo_grillat) 780)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories crema_taronja) 410)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )