(define (problem menuext4b-tc4)
          (:domain menuext4b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_de_cigrons fajitas_verdures crema_espinacs amanida_catalana sopa_miso crema_de_bolets sopa_de_marisc escalivada_verdures sopa_de_peix gnocchi_pesto - primer
crema_avellana crema_de_limon hamburguesa_mongeta filet_porc sopa_de_galets crema_taronja crema_de_xocolata truita_verdures parrillada_verdures wok_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible sopa_miso parrillada_verdures)
    (incompatible sopa_de_marisc parrillada_verdures)
    (incompatible gnocchi_pesto crema_avellana)
    (incompatible gnocchi_pesto crema_de_xocolata)
    (incompatible sopa_de_marisc wok_verdures)
    (incompatible gnocchi_pesto crema_de_limon)
    (incompatible fajitas_verdures filet_porc)
    (incompatible fajitas_verdures sopa_de_galets)
    (platTipus sopa_de_cigrons sopa)
    (platTipus fajitas_verdures verdures)
    (platTipus crema_espinacs crema)
    (platTipus amanida_catalana amanida)
    (platTipus sopa_miso sopa)
    (platTipus crema_de_bolets crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus escalivada_verdures verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus gnocchi_pesto pasta)
    (platTipus crema_avellana crema)
    (platTipus crema_de_limon crema)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus filet_porc carn)
    (platTipus sopa_de_galets sopa)
    (platTipus crema_taronja crema)
    (platTipus crema_de_xocolata crema)
    (platTipus truita_verdures verdures)
    (platTipus parrillada_verdures verdures)
    (platTipus wok_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori fajitas_verdures dimarts)
    (platObligatori crema_de_limon dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories sopa_de_cigrons) 530)
    (= (calories fajitas_verdures) 390)
    (= (calories crema_espinacs) 380)
    (= (calories amanida_catalana) 300)
    (= (calories sopa_miso) 500)
    (= (calories crema_de_bolets) 390)
    (= (calories sopa_de_marisc) 560)
    (= (calories escalivada_verdures) 350)
    (= (calories sopa_de_peix) 450)
    (= (calories gnocchi_pesto) 740)
    (= (calories crema_avellana) 480)
    (= (calories crema_de_limon) 430)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories filet_porc) 900)
    (= (calories sopa_de_galets) 470)
    (= (calories crema_taronja) 410)
    (= (calories crema_de_xocolata) 450)
    (= (calories truita_verdures) 500)
    (= (calories parrillada_verdures) 550)
    (= (calories wok_verdures) 540)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )