(define (problem menuext2b-tc2)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_miso raviolis_ricotta amanida_quinoa brocoli_allada crema_espinacs penne_arrabiata verdures_amb_salsa crema_de_carxofa amanida_catalana amanida_fasols - primer
tataki_verdures sopa_de_pedra botifarra_a_la_planxa wok_verdures crema_avellana crema_de_limon estofat_cigrons faves_estofades turbot_planxa estofat_soja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible brocoli_allada sopa_de_pedra)
    (incompatible amanida_quinoa turbot_planxa)
    (incompatible crema_de_carxofa botifarra_a_la_planxa)
    (incompatible penne_arrabiata crema_avellana)
    (incompatible verdures_amb_salsa sopa_de_pedra)
    (incompatible crema_espinacs botifarra_a_la_planxa)
    (incompatible raviolis_ricotta crema_de_limon)
    (incompatible amanida_quinoa botifarra_a_la_planxa)
    (platTipus sopa_miso sopa)
    (platTipus raviolis_ricotta pasta)
    (platTipus amanida_quinoa amanida)
    (platTipus brocoli_allada verdures)
    (platTipus crema_espinacs crema)
    (platTipus penne_arrabiata pasta)
    (platTipus verdures_amb_salsa verdures)
    (platTipus crema_de_carxofa crema)
    (platTipus amanida_catalana amanida)
    (platTipus amanida_fasols llegums)
    (platTipus tataki_verdures verdures)
    (platTipus sopa_de_pedra sopa)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus wok_verdures verdures)
    (platTipus crema_avellana crema)
    (platTipus crema_de_limon crema)
    (platTipus estofat_cigrons llegums)
    (platTipus faves_estofades llegums)
    (platTipus turbot_planxa peix)
    (platTipus estofat_soja llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )