(define (problem menuext2b-tc5)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_asiatica truita_potatge amanida_de_tomaquet crema_de_carabasso tallarins_carbonara crema_de_carbassa fajitas_verdures amanida_catalana verdures_a_la_planxa sopa_de_peix - primer
bacalla_amb_tomaquet estofat_cigrons salmo_grillat botifarra_a_la_planxa sopa_ceba estofat_soja sopa_de_galets sopa_de_pedra crema_de_limon curry_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_catalana salmo_grillat)
    (incompatible amanida_asiatica botifarra_a_la_planxa)
    (incompatible verdures_a_la_planxa sopa_de_pedra)
    (incompatible verdures_a_la_planxa sopa_ceba)
    (incompatible fajitas_verdures sopa_de_pedra)
    (incompatible crema_de_carabasso salmo_grillat)
    (incompatible crema_de_carbassa bacalla_amb_tomaquet)
    (incompatible fajitas_verdures sopa_ceba)
    (platTipus amanida_asiatica amanida)
    (platTipus truita_potatge llegums)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus crema_de_carabasso crema)
    (platTipus tallarins_carbonara pasta)
    (platTipus crema_de_carbassa crema)
    (platTipus fajitas_verdures verdures)
    (platTipus amanida_catalana amanida)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus estofat_cigrons llegums)
    (platTipus salmo_grillat peix)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus sopa_ceba sopa)
    (platTipus estofat_soja llegums)
    (platTipus sopa_de_galets sopa)
    (platTipus sopa_de_pedra sopa)
    (platTipus crema_de_limon crema)
    (platTipus curry_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )