(define (problem menuext2b-tc5)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
macarrons_forn verdures_a_la_planxa sopa_verdures amanida_de_tomaquet truita_potatge raviolis_ricotta brocoli_allada crema_de_carbassa amanida_asiatica crema_de_carabasso - primer
wok_verdures crema_de_limon crema_taronja crema_avellana bacalla_amb_tomaquet parrillada_verdures sopa_de_peix estofat_cigrons cuixa_anec faves_estofades - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_asiatica bacalla_amb_tomaquet)
    (incompatible macarrons_forn crema_taronja)
    (incompatible crema_de_carbassa cuixa_anec)
    (incompatible amanida_de_tomaquet cuixa_anec)
    (incompatible verdures_a_la_planxa sopa_de_peix)
    (incompatible crema_de_carbassa bacalla_amb_tomaquet)
    (incompatible sopa_verdures wok_verdures)
    (incompatible brocoli_allada cuixa_anec)
    (platTipus macarrons_forn pasta)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus sopa_verdures sopa)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus truita_potatge llegums)
    (platTipus raviolis_ricotta pasta)
    (platTipus brocoli_allada verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus amanida_asiatica amanida)
    (platTipus crema_de_carabasso crema)
    (platTipus wok_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus crema_taronja crema)
    (platTipus crema_avellana crema)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus parrillada_verdures verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus estofat_cigrons llegums)
    (platTipus cuixa_anec carn)
    (platTipus faves_estofades llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )