(define (problem menuext2b-tc4)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
escalivada_verdures amanida_catalana penne_arrabiata amanida_de_cogombre sopa_miso crema_de_carxofa amanida_fasols crema_de_bolets crema_de_carbassa raviolis_ricotta - primer
truita_de_llenties turbot_planxa llenguado_amb_lima faves_estofades sopa_de_pedra filet_porc parrillada_verdures xai_rostit tataki_verdures pollastre_a_la_planxa - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_de_cogombre pollastre_a_la_planxa)
    (incompatible crema_de_carxofa pollastre_a_la_planxa)
    (incompatible crema_de_bolets filet_porc)
    (incompatible crema_de_carxofa llenguado_amb_lima)
    (incompatible crema_de_carxofa xai_rostit)
    (incompatible crema_de_carbassa xai_rostit)
    (incompatible amanida_de_cogombre turbot_planxa)
    (incompatible amanida_catalana filet_porc)
    (platTipus escalivada_verdures verdures)
    (platTipus amanida_catalana amanida)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_de_cogombre amanida)
    (platTipus sopa_miso sopa)
    (platTipus crema_de_carxofa crema)
    (platTipus amanida_fasols llegums)
    (platTipus crema_de_bolets crema)
    (platTipus crema_de_carbassa crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus truita_de_llenties llegums)
    (platTipus turbot_planxa peix)
    (platTipus llenguado_amb_lima peix)
    (platTipus faves_estofades llegums)
    (platTipus sopa_de_pedra sopa)
    (platTipus filet_porc carn)
    (platTipus parrillada_verdures verdures)
    (platTipus xai_rostit carn)
    (platTipus tataki_verdures verdures)
    (platTipus pollastre_a_la_planxa carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )