(define (problem menuext2b-tc2)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
escalivada_verdures truita_potatge tallarins_carbonara amanida_catalana sopa_verdures crema_de_carbassa crema_de_carabasso amanida_quinoa amanida_fasols fajitas_verdures - primer
turbot_planxa filet_porc estofat_soja crema_avellana truita_de_llenties bacalla_amb_tomaquet llenguado_amb_lima sopa_ajo crema_taronja salmo_grillat - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_catalana turbot_planxa)
    (incompatible amanida_quinoa llenguado_amb_lima)
    (incompatible crema_de_carbassa bacalla_amb_tomaquet)
    (incompatible amanida_quinoa salmo_grillat)
    (incompatible amanida_quinoa turbot_planxa)
    (incompatible tallarins_carbonara crema_avellana)
    (incompatible crema_de_carabasso filet_porc)
    (incompatible amanida_catalana llenguado_amb_lima)
    (platTipus escalivada_verdures verdures)
    (platTipus truita_potatge llegums)
    (platTipus tallarins_carbonara pasta)
    (platTipus amanida_catalana amanida)
    (platTipus sopa_verdures sopa)
    (platTipus crema_de_carbassa crema)
    (platTipus crema_de_carabasso crema)
    (platTipus amanida_quinoa amanida)
    (platTipus amanida_fasols llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus turbot_planxa peix)
    (platTipus filet_porc carn)
    (platTipus estofat_soja llegums)
    (platTipus crema_avellana crema)
    (platTipus truita_de_llenties llegums)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus llenguado_amb_lima peix)
    (platTipus sopa_ajo sopa)
    (platTipus crema_taronja crema)
    (platTipus salmo_grillat peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )