(define (problem menuext2b-tc3)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carabasso verdures_amb_salsa cigrons_saltejats sopa_de_marisc amanida_de_cogombre amanida_de_tomaquet crema_espinacs sopa_miso estofat_llenties crema_de_carxofa - primer
bacalla_amb_tomaquet xai_rostit crema_de_xocolata salmo_grillat faves_estofades parrillada_verdures sopa_de_pedra hamburguesa_mongeta llenguado_amb_lima tataki_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible sopa_miso tataki_verdures)
    (incompatible amanida_de_cogombre llenguado_amb_lima)
    (incompatible sopa_miso parrillada_verdures)
    (incompatible verdures_amb_salsa sopa_de_pedra)
    (incompatible crema_de_carabasso xai_rostit)
    (incompatible cigrons_saltejats llenguado_amb_lima)
    (incompatible crema_de_carabasso llenguado_amb_lima)
    (incompatible crema_de_carxofa bacalla_amb_tomaquet)
    (platTipus crema_de_carabasso crema)
    (platTipus verdures_amb_salsa verdures)
    (platTipus cigrons_saltejats llegums)
    (platTipus sopa_de_marisc sopa)
    (platTipus amanida_de_cogombre amanida)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus crema_espinacs crema)
    (platTipus sopa_miso sopa)
    (platTipus estofat_llenties llegums)
    (platTipus crema_de_carxofa crema)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus xai_rostit carn)
    (platTipus crema_de_xocolata crema)
    (platTipus salmo_grillat peix)
    (platTipus faves_estofades llegums)
    (platTipus parrillada_verdures verdures)
    (platTipus sopa_de_pedra sopa)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus llenguado_amb_lima peix)
    (platTipus tataki_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )