(define (problem menuext2b-tc1)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_de_cogombre crema_de_carbassa amanida_de_tomaquet crema_de_carabasso sopa_de_marisc hummus truita_potatge sopa_de_cigrons escalivada_verdures amanida_fasols - primer
truita_de_llenties salmo_grillat pollastre_a_la_planxa wok_verdures bacalla_amb_tomaquet filet_porc curry_verdures faves_estofades estofat_soja orata_forno - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carabasso bacalla_amb_tomaquet)
    (incompatible sopa_de_cigrons curry_verdures)
    (incompatible crema_de_carbassa orata_forno)
    (incompatible amanida_fasols orata_forno)
    (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
    (incompatible amanida_de_cogombre bacalla_amb_tomaquet)
    (incompatible hummus salmo_grillat)
    (incompatible crema_de_carabasso filet_porc)
    (platTipus amanida_de_cogombre amanida)
    (platTipus crema_de_carbassa crema)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus crema_de_carabasso crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus hummus llegums)
    (platTipus truita_potatge llegums)
    (platTipus sopa_de_cigrons sopa)
    (platTipus escalivada_verdures verdures)
    (platTipus amanida_fasols llegums)
    (platTipus truita_de_llenties llegums)
    (platTipus salmo_grillat peix)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus wok_verdures verdures)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus filet_porc carn)
    (platTipus curry_verdures verdures)
    (platTipus faves_estofades llegums)
    (platTipus estofat_soja llegums)
    (platTipus orata_forno peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )