(define (problem menuext2b-tc5)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_asiatica gnocchi_pesto truita_potatge brocoli_allada crema_de_carbassa tallarins_carbonara escalivada_verdures crema_de_bolets sopa_miso amanida_de_tomaquet - primer
estofat_soja turbot_planxa botifarra_a_la_planxa cuixa_anec sopa_ceba sopa_ajo orata_forno crema_avellana crema_de_xocolata truita_de_llenties - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_asiatica botifarra_a_la_planxa)
    (incompatible crema_de_bolets botifarra_a_la_planxa)
    (incompatible amanida_asiatica turbot_planxa)
    (incompatible truita_potatge orata_forno)
    (incompatible crema_de_carbassa botifarra_a_la_planxa)
    (incompatible crema_de_bolets turbot_planxa)
    (incompatible amanida_de_tomaquet orata_forno)
    (incompatible gnocchi_pesto crema_avellana)
    (platTipus amanida_asiatica amanida)
    (platTipus gnocchi_pesto pasta)
    (platTipus truita_potatge llegums)
    (platTipus brocoli_allada verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus tallarins_carbonara pasta)
    (platTipus escalivada_verdures verdures)
    (platTipus crema_de_bolets crema)
    (platTipus sopa_miso sopa)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus estofat_soja llegums)
    (platTipus turbot_planxa peix)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus cuixa_anec carn)
    (platTipus sopa_ceba sopa)
    (platTipus sopa_ajo sopa)
    (platTipus orata_forno peix)
    (platTipus crema_avellana crema)
    (platTipus crema_de_xocolata crema)
    (platTipus truita_de_llenties llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )