(define (problem menuext2b-tc3)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_de_cigrons amanida_quinoa crema_de_carbassa gnocchi_pesto sopa_verdures amanida_fasols amanida_de_cogombre amanida_asiatica tallarins_carbonara truita_potatge - primer
pollastre_a_la_planxa truita_de_llenties salmo_grillat bacalla_amb_tomaquet truita_verdures filet_porc crema_avellana crema_de_xocolata sopa_ajo estofat_soja - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa salmo_grillat)
    (incompatible sopa_de_cigrons truita_verdures)
    (incompatible gnocchi_pesto crema_avellana)
    (incompatible truita_potatge bacalla_amb_tomaquet)
    (incompatible amanida_de_cogombre filet_porc)
    (incompatible truita_potatge salmo_grillat)
    (incompatible amanida_quinoa pollastre_a_la_planxa)
    (incompatible amanida_quinoa salmo_grillat)
    (platTipus sopa_de_cigrons sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus crema_de_carbassa crema)
    (platTipus gnocchi_pesto pasta)
    (platTipus sopa_verdures sopa)
    (platTipus amanida_fasols llegums)
    (platTipus amanida_de_cogombre amanida)
    (platTipus amanida_asiatica amanida)
    (platTipus tallarins_carbonara pasta)
    (platTipus truita_potatge llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus truita_de_llenties llegums)
    (platTipus salmo_grillat peix)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus truita_verdures verdures)
    (platTipus filet_porc carn)
    (platTipus crema_avellana crema)
    (platTipus crema_de_xocolata crema)
    (platTipus sopa_ajo sopa)
    (platTipus estofat_soja llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )