(define (problem menuext2b-tc1)
          (:domain menuext2b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
truita_potatge crema_de_carabasso fajitas_verdures crema_espinacs crema_de_carbassa gnocchi_pesto crema_de_carxofa sopa_miso sopa_de_marisc amanida_asiatica - primer
crema_de_xocolata tataki_verdures sopa_ceba truita_verdures crema_catalana crema_de_limon orata_forno crema_avellana turbot_planxa filet_porc - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa filet_porc)
    (incompatible sopa_de_marisc truita_verdures)
    (incompatible amanida_asiatica orata_forno)
    (incompatible crema_de_carxofa turbot_planxa)
    (incompatible crema_espinacs orata_forno)
    (incompatible crema_de_carxofa filet_porc)
    (incompatible sopa_de_marisc tataki_verdures)
    (incompatible sopa_miso tataki_verdures)
    (platTipus truita_potatge llegums)
    (platTipus crema_de_carabasso crema)
    (platTipus fajitas_verdures verdures)
    (platTipus crema_espinacs crema)
    (platTipus crema_de_carbassa crema)
    (platTipus gnocchi_pesto pasta)
    (platTipus crema_de_carxofa crema)
    (platTipus sopa_miso sopa)
    (platTipus sopa_de_marisc sopa)
    (platTipus amanida_asiatica amanida)
    (platTipus crema_de_xocolata crema)
    (platTipus tataki_verdures verdures)
    (platTipus sopa_ceba sopa)
    (platTipus truita_verdures verdures)
    (platTipus crema_catalana crema)
    (platTipus crema_de_limon crema)
    (platTipus orata_forno peix)
    (platTipus crema_avellana crema)
    (platTipus turbot_planxa peix)
    (platTipus filet_porc carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
        )