(define (problem menu-ext5b-5)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  crema_de_carabasso sopa_verdures sopa_de_peix verdures_amb_salsa truita_potatge sopa_de_marisc crema_de_bolets sopa_miso amanida_fasols amanida_de_tomaquet macarrons_forn amanida_catalana - primer
  hamburguesa_mongeta salmo_grillat crema_de_limon xai_rostit sopa_de_peix estofat_cigrons crema_de_xocolata estofat_soja parrillada_verdures crema_catalana truita_verdures sopa_de_galets - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible crema_de_carabasso xai_rostit)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible sopa_de_peix truita_verdures)
  (incompatible verdures_amb_salsa xai_rostit)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa sopa_de_galets)
  (incompatible truita_potatge salmo_grillat)
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc truita_verdures)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_bolets xai_rostit)
  (incompatible sopa_miso parrillada_verdures)
  (incompatible sopa_miso truita_verdures)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible amanida_de_tomaquet xai_rostit)
  (incompatible macarrons_forn crema_de_limon)
  (incompatible macarrons_forn crema_de_xocolata)
  (incompatible macarrons_forn crema_catalana)
  (incompatible amanida_catalana salmo_grillat)
  (incompatible amanida_catalana xai_rostit)
  (platTipus crema_de_carabasso crema)
  (platTipus sopa_verdures sopa)
  (platTipus sopa_de_peix sopa)
  (platTipus verdures_amb_salsa verdures)
  (platTipus truita_potatge llegums)
  (platTipus sopa_de_marisc sopa)
  (platTipus crema_de_bolets crema)
  (platTipus sopa_miso sopa)
  (platTipus amanida_fasols llegums)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus macarrons_forn pasta)
  (platTipus amanida_catalana amanida)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus salmo_grillat peix)
  (platTipus crema_de_limon crema)
  (platTipus xai_rostit carn)
  (platTipus sopa_de_peix sopa)
  (platTipus estofat_cigrons llegums)
  (platTipus crema_de_xocolata crema)
  (platTipus estofat_soja llegums)
  (platTipus parrillada_verdures verdures)
  (platTipus crema_catalana crema)
  (platTipus truita_verdures verdures)
  (platTipus sopa_de_galets sopa)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories crema_de_carabasso) 330)
  (= (calories sopa_verdures) 480)
  (= (calories sopa_de_peix) 450)
  (= (calories verdures_amb_salsa) 380)
  (= (calories truita_potatge) 580)
  (= (calories sopa_de_marisc) 560)
  (= (calories crema_de_bolets) 390)
  (= (calories sopa_miso) 500)
  (= (calories amanida_fasols) 560)
  (= (calories amanida_de_tomaquet) 270)
  (= (calories macarrons_forn) 650)
  (= (calories amanida_catalana) 300)
  (= (calories hamburguesa_mongeta) 670)
  (= (calories salmo_grillat) 780)
  (= (calories crema_de_limon) 430)
  (= (calories xai_rostit) 1000)
  (= (calories sopa_de_peix) 520)
  (= (calories estofat_cigrons) 690)
  (= (calories crema_de_xocolata) 450)
  (= (calories estofat_soja) 700)
  (= (calories parrillada_verdures) 550)
  (= (calories crema_catalana) 440)
  (= (calories truita_verdures) 500)
  (= (calories sopa_de_galets) 470)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (= (preu crema_de_carabasso) 2)
  (= (preu sopa_verdures) 4)
  (= (preu sopa_de_peix) 5)
  (= (preu verdures_amb_salsa) 4)
  (= (preu truita_potatge) 5)
  (= (preu sopa_de_marisc) 6)
  (= (preu crema_de_bolets) 4)
  (= (preu sopa_miso) 5)
  (= (preu amanida_fasols) 4)
  (= (preu amanida_de_tomaquet) 3)
  (= (preu macarrons_forn) 4)
  (= (preu amanida_catalana) 4)
  (= (preu hamburguesa_mongeta) 5)
  (= (preu salmo_grillat) 9)
  (= (preu crema_de_limon) 4)
  (= (preu xai_rostit) 9)
  (= (preu sopa_de_peix) 6)
  (= (preu estofat_cigrons) 5)
  (= (preu crema_de_xocolata) 5)
  (= (preu estofat_soja) 5)
  (= (preu parrillada_verdures) 5)
  (= (preu crema_catalana) 4)
  (= (preu truita_verdures) 4)
  (= (preu sopa_de_galets) 4)
  (= (costDiari) 0)
  (= (costTotal) 0)
  (platObligatori crema_de_carabasso dimarts)
  (platObligatori estofat_soja divendres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )