      (define (problem menu-ext5b-4)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_de_tomaquet hummus cigrons_saltejats sopa_de_cigrons crema_de_carbassa macarrons_forn estofat_llenties amanida_de_cogombre raviolis_ricotta sopa_de_marisc sopa_de_peix tallarins_carbonara - primer
  tortellinis_carne amanida_de_espinacs bacalla_amb_tomate faves_estofades pennes_amb_pesto amanida_cesar xai_rostit llenguado_amb_lima crema_catalana sopa_de_pedra crema_de_xocolata truita_de_llenties - segon
  amanida carn crema llegums pasta peix sopa DummyT - tipus
)

        (:init
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_de_tomaquet llenguado_amb_lima)
      (incompatible hummus tortellinis_carne)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus llenguado_amb_lima)
      (incompatible cigrons_saltejats tortellinis_carne)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats llenguado_amb_lima)
      (incompatible sopa_de_cigrons tortellinis_carne)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible crema_de_carbassa llenguado_amb_lima)
      (incompatible macarrons_forn amanida_de_espinacs)
      (incompatible macarrons_forn amanida_cesar)
      (incompatible macarrons_forn crema_catalana)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible estofat_llenties tortellinis_carne)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre llenguado_amb_lima)
      (incompatible raviolis_ricotta amanida_de_espinacs)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible raviolis_ricotta crema_catalana)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible sopa_de_marisc tortellinis_carne)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_peix tortellinis_carne)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible tallarins_carbonara amanida_de_espinacs)
      (incompatible tallarins_carbonara amanida_cesar)
      (incompatible tallarins_carbonara crema_catalana)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus hummus llegums)
      (platTipus cigrons_saltejats llegums)
      (platTipus sopa_de_cigrons sopa)
      (platTipus crema_de_carbassa crema)
      (platTipus macarrons_forn pasta)
      (platTipus estofat_llenties llegums)
      (platTipus amanida_de_cogombre amanida)
      (platTipus raviolis_ricotta pasta)
      (platTipus sopa_de_marisc sopa)
      (platTipus sopa_de_peix sopa)
      (platTipus tallarins_carbonara pasta)
      (platTipus tortellinis_carne pasta)
      (platTipus amanida_de_espinacs amanida)
      (platTipus bacalla_amb_tomate peix)
      (platTipus faves_estofades llegums)
      (platTipus pennes_amb_pesto pasta)
      (platTipus amanida_cesar amanida)
      (platTipus xai_rostit carn)
      (platTipus llenguado_amb_lima peix)
      (platTipus crema_catalana crema)
      (platTipus sopa_de_pedra sopa)
      (platTipus crema_de_xocolata crema)
      (platTipus truita_de_llenties llegums)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories amanida_de_tomaquet) 130)
      (= (calories hummus) 300)
      (= (calories cigrons_saltejats) 330)
      (= (calories sopa_de_cigrons) 300)
      (= (calories crema_de_carbassa) 180)
      (= (calories macarrons_forn) 380)
      (= (calories estofat_llenties) 350)
      (= (calories amanida_de_cogombre) 120)
      (= (calories raviolis_ricotta) 400)
      (= (calories sopa_de_marisc) 320)
      (= (calories sopa_de_peix) 250)
      (= (calories tallarins_carbonara) 420)
      (= (calories tortellinis_carne) 600)
      (= (calories amanida_de_espinacs) 170)
      (= (calories bacalla_amb_tomate) 550)
      (= (calories faves_estofades) 480)
      (= (calories pennes_amb_pesto) 500)
      (= (calories amanida_cesar) 180)
      (= (calories xai_rostit) 700)
      (= (calories llenguado_amb_lima) 500)
      (= (calories crema_catalana) 250)
      (= (calories sopa_de_pedra) 300)
      (= (calories crema_de_xocolata) 260)
      (= (calories truita_de_llenties) 400)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (= (preu amanida_de_tomaquet) 3)
      (= (preu hummus) 4)
      (= (preu cigrons_saltejats) 4)
      (= (preu sopa_de_cigrons) 4)
      (= (preu crema_de_carbassa) 3)
      (= (preu macarrons_forn) 4)
      (= (preu estofat_llenties) 5)
      (= (preu amanida_de_cogombre) 3)
      (= (preu raviolis_ricotta) 5)
      (= (preu sopa_de_marisc) 6)
      (= (preu sopa_de_peix) 5)
      (= (preu tallarins_carbonara) 5)
      (= (preu tortellinis_carne) 7)
      (= (preu amanida_de_espinacs) 3)
      (= (preu bacalla_amb_tomate) 7)
      (= (preu faves_estofades) 6)
      (= (preu pennes_amb_pesto) 6)
      (= (preu amanida_cesar) 4)
      (= (preu xai_rostit) 9)
      (= (preu llenguado_amb_lima) 8)
      (= (preu crema_catalana) 4)
      (= (preu sopa_de_pedra) 5)
      (= (preu crema_de_xocolata) 5)
      (= (preu truita_de_llenties) 5)
      (= (costDiari) 0)
      (= (costTotal) 0)
      (platObligatori bacalla_amb_tomate dimarts)
      (platObligatori crema_de_xocolata dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )