      (define (problem menu-ext5b-5)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  crema_de_carxofa tataki_salmo cigrons_saltejats sopa_de_marisc estofat_llenties llobarro_forn ceviche_tonyina botifarra_brasa carpaccio_vedella hummus raviolis_ricotta macarrons_forn - primer
  sopa_de_peix pennes_amb_pesto sopa_de_galets amanida_de_espinacs parrillada_verdures botifarra_a_la_planxa truita_verdures estofat_cigrons pollastre_a_la_planxa crema_de_xocolata amanida_cesar salmo_grillat - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible crema_de_carxofa botifarra_a_la_planxa)
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible tataki_salmo pollastre_a_la_planxa)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc truita_verdures)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible llobarro_forn pollastre_a_la_planxa)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible ceviche_tonyina pollastre_a_la_planxa)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible botifarra_brasa truita_verdures)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible carpaccio_vedella sopa_de_galets)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus salmo_grillat)
      (incompatible raviolis_ricotta amanida_de_espinacs)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible macarrons_forn amanida_de_espinacs)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn amanida_cesar)
      (platTipus crema_de_carxofa crema)
      (platTipus tataki_salmo peix)
      (platTipus cigrons_saltejats llegums)
      (platTipus sopa_de_marisc sopa)
      (platTipus estofat_llenties llegums)
      (platTipus llobarro_forn peix)
      (platTipus ceviche_tonyina peix)
      (platTipus botifarra_brasa carn)
      (platTipus carpaccio_vedella carn)
      (platTipus hummus llegums)
      (platTipus raviolis_ricotta pasta)
      (platTipus macarrons_forn pasta)
      (platTipus sopa_de_peix sopa)
      (platTipus pennes_amb_pesto pasta)
      (platTipus sopa_de_galets sopa)
      (platTipus amanida_de_espinacs amanida)
      (platTipus parrillada_verdures verdures)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus truita_verdures verdures)
      (platTipus estofat_cigrons llegums)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus crema_de_xocolata crema)
      (platTipus amanida_cesar amanida)
      (platTipus salmo_grillat peix)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories crema_de_carxofa) 160)
      (= (calories tataki_salmo) 240)
      (= (calories cigrons_saltejats) 330)
      (= (calories sopa_de_marisc) 320)
      (= (calories estofat_llenties) 350)
      (= (calories llobarro_forn) 260)
      (= (calories ceviche_tonyina) 220)
      (= (calories botifarra_brasa) 350)
      (= (calories carpaccio_vedella) 200)
      (= (calories hummus) 300)
      (= (calories raviolis_ricotta) 400)
      (= (calories macarrons_forn) 380)
      (= (calories sopa_de_peix) 320)
      (= (calories pennes_amb_pesto) 500)
      (= (calories sopa_de_galets) 280)
      (= (calories amanida_de_espinacs) 170)
      (= (calories parrillada_verdures) 340)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories truita_verdures) 300)
      (= (calories estofat_cigrons) 450)
      (= (calories pollastre_a_la_planxa) 650)
      (= (calories crema_de_xocolata) 260)
      (= (calories amanida_cesar) 180)
      (= (calories salmo_grillat) 520)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (= (preu crema_de_carxofa) 3)
      (= (preu tataki_salmo) 7)
      (= (preu cigrons_saltejats) 4)
      (= (preu sopa_de_marisc) 6)
      (= (preu estofat_llenties) 5)
      (= (preu llobarro_forn) 5)
      (= (preu ceviche_tonyina) 6)
      (= (preu botifarra_brasa) 6)
      (= (preu carpaccio_vedella) 7)
      (= (preu hummus) 4)
      (= (preu raviolis_ricotta) 5)
      (= (preu macarrons_forn) 4)
      (= (preu sopa_de_peix) 6)
      (= (preu pennes_amb_pesto) 6)
      (= (preu sopa_de_galets) 4)
      (= (preu amanida_de_espinacs) 3)
      (= (preu parrillada_verdures) 5)
      (= (preu botifarra_a_la_planxa) 7)
      (= (preu truita_verdures) 4)
      (= (preu estofat_cigrons) 5)
      (= (preu pollastre_a_la_planxa) 8)
      (= (preu crema_de_xocolata) 5)
      (= (preu amanida_cesar) 4)
      (= (preu salmo_grillat) 9)
      (= (costDiari) 0)
      (= (costTotal) 0)
      (platObligatori raviolis_ricotta dijous)
      (platObligatori llobarro_forn dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )