(define (problem menu-ext5b-1)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_quinoa verdures_a_la_planxa sopa_verdures estofat_llenties tallarins_carbonara raviolis_ricotta gnocchi_pesto sopa_de_peix verdures_amb_salsa amanida_fasols fajitas_verdures sopa_miso - primer
  tataki_verdures salmo_grillat cuixa_ànec sopa_de_pedra hamburguesa_mongeta llenguado_amb_lima parrillada_verdures sopa_ceba sopa_de_peix estofat_cigrons faves_estofades bacalla_amb_tomate - segon
  amanida carn llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible amanida_quinoa cuixa_ànec)
  (incompatible amanida_quinoa llenguado_amb_lima)
  (incompatible amanida_quinoa bacalla_amb_tomate)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible sopa_verdures tataki_verdures)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible estofat_llenties llenguado_amb_lima)
  (incompatible estofat_llenties bacalla_amb_tomate)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa sopa_ceba)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible amanida_fasols llenguado_amb_lima)
  (incompatible amanida_fasols bacalla_amb_tomate)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible fajitas_verdures sopa_de_pedra)
  (incompatible fajitas_verdures sopa_ceba)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible sopa_miso tataki_verdures)
  (incompatible sopa_miso parrillada_verdures)
  (platTipus amanida_quinoa amanida)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus sopa_verdures sopa)
  (platTipus estofat_llenties llegums)
  (platTipus tallarins_carbonara pasta)
  (platTipus raviolis_ricotta pasta)
  (platTipus gnocchi_pesto pasta)
  (platTipus sopa_de_peix sopa)
  (platTipus verdures_amb_salsa verdures)
  (platTipus amanida_fasols llegums)
  (platTipus fajitas_verdures verdures)
  (platTipus sopa_miso sopa)
  (platTipus tataki_verdures verdures)
  (platTipus salmo_grillat peix)
  (platTipus cuixa_ànec carn)
  (platTipus sopa_de_pedra sopa)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus llenguado_amb_lima peix)
  (platTipus parrillada_verdures verdures)
  (platTipus sopa_ceba sopa)
  (platTipus sopa_de_peix sopa)
  (platTipus estofat_cigrons llegums)
  (platTipus faves_estofades llegums)
  (platTipus bacalla_amb_tomate peix)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories amanida_quinoa) 360)
  (= (calories verdures_a_la_planxa) 300)
  (= (calories sopa_verdures) 480)
  (= (calories estofat_llenties) 600)
  (= (calories tallarins_carbonara) 700)
  (= (calories raviolis_ricotta) 680)
  (= (calories gnocchi_pesto) 740)
  (= (calories sopa_de_peix) 450)
  (= (calories verdures_amb_salsa) 380)
  (= (calories amanida_fasols) 560)
  (= (calories fajitas_verdures) 390)
  (= (calories sopa_miso) 500)
  (= (calories tataki_verdures) 520)
  (= (calories salmo_grillat) 780)
  (= (calories cuixa_ànec) 980)
  (= (calories sopa_de_pedra) 500)
  (= (calories hamburguesa_mongeta) 670)
  (= (calories llenguado_amb_lima) 750)
  (= (calories parrillada_verdures) 550)
  (= (calories sopa_ceba) 450)
  (= (calories sopa_de_peix) 520)
  (= (calories estofat_cigrons) 690)
  (= (calories faves_estofades) 730)
  (= (calories bacalla_amb_tomate) 810)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (= (preu amanida_quinoa) 4)
  (= (preu verdures_a_la_planxa) 3)
  (= (preu sopa_verdures) 4)
  (= (preu estofat_llenties) 5)
  (= (preu tallarins_carbonara) 5)
  (= (preu raviolis_ricotta) 5)
  (= (preu gnocchi_pesto) 5)
  (= (preu sopa_de_peix) 5)
  (= (preu verdures_amb_salsa) 4)
  (= (preu amanida_fasols) 4)
  (= (preu fajitas_verdures) 4)
  (= (preu sopa_miso) 5)
  (= (preu tataki_verdures) 5)
  (= (preu salmo_grillat) 9)
  (= (preu cuixa_ànec) 9)
  (= (preu sopa_de_pedra) 5)
  (= (preu hamburguesa_mongeta) 5)
  (= (preu llenguado_amb_lima) 8)
  (= (preu parrillada_verdures) 5)
  (= (preu sopa_ceba) 4)
  (= (preu sopa_de_peix) 6)
  (= (preu estofat_cigrons) 5)
  (= (preu faves_estofades) 6)
  (= (preu bacalla_amb_tomate) 7)
  (= (costDiari) 0)
  (= (costTotal) 0)
  (platObligatori sopa_de_pedra dimarts)
  (platObligatori sopa_de_peix dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )