      (define (problem menu-ext5b-2)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  botifarra_brasa crema_de_carxofa amanida_de_cogombre sopa_de_marisc croquetes_carn tallarins_carbonara sopa_de_peix verdures_amb_salsa hummus escalivada_verdures estofat_llenties llobarro_forn - primer
  sopa_de_peix xai_rostit parrillada_verdures amanida_de_espinacs llenguado_amb_lima amanida_cesar salmo_grillat amanida_de_remolatxa tortellinis_carne crema_catalana pennes_amb_pesto bacalla_amb_tomate - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible crema_de_carxofa xai_rostit)
      (incompatible crema_de_carxofa llenguado_amb_lima)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible crema_de_carxofa bacalla_amb_tomate)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible amanida_de_cogombre llenguado_amb_lima)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc tortellinis_carne)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible tallarins_carbonara amanida_de_espinacs)
      (incompatible tallarins_carbonara amanida_cesar)
      (incompatible tallarins_carbonara amanida_de_remolatxa)
      (incompatible tallarins_carbonara crema_catalana)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix tortellinis_carne)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible verdures_amb_salsa sopa_de_peix)
      (incompatible verdures_amb_salsa xai_rostit)
      (incompatible hummus llenguado_amb_lima)
      (incompatible hummus salmo_grillat)
      (incompatible hummus tortellinis_carne)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible estofat_llenties llenguado_amb_lima)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible estofat_llenties tortellinis_carne)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible llobarro_forn xai_rostit)
      (incompatible llobarro_forn crema_catalana)
      (platTipus botifarra_brasa carn)
      (platTipus crema_de_carxofa crema)
      (platTipus amanida_de_cogombre amanida)
      (platTipus sopa_de_marisc sopa)
      (platTipus croquetes_carn carn)
      (platTipus tallarins_carbonara pasta)
      (platTipus sopa_de_peix sopa)
      (platTipus verdures_amb_salsa verdures)
      (platTipus hummus llegums)
      (platTipus escalivada_verdures verdures)
      (platTipus estofat_llenties llegums)
      (platTipus llobarro_forn peix)
      (platTipus sopa_de_peix sopa)
      (platTipus xai_rostit carn)
      (platTipus parrillada_verdures verdures)
      (platTipus amanida_de_espinacs amanida)
      (platTipus llenguado_amb_lima peix)
      (platTipus amanida_cesar amanida)
      (platTipus salmo_grillat peix)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus tortellinis_carne pasta)
      (platTipus crema_catalana crema)
      (platTipus pennes_amb_pesto pasta)
      (platTipus bacalla_amb_tomate peix)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories botifarra_brasa) 350)
      (= (calories crema_de_carxofa) 160)
      (= (calories amanida_de_cogombre) 120)
      (= (calories sopa_de_marisc) 320)
      (= (calories croquetes_carn) 250)
      (= (calories tallarins_carbonara) 420)
      (= (calories sopa_de_peix) 250)
      (= (calories verdures_amb_salsa) 200)
      (= (calories hummus) 300)
      (= (calories escalivada_verdures) 180)
      (= (calories estofat_llenties) 350)
      (= (calories llobarro_forn) 260)
      (= (calories sopa_de_peix) 320)
      (= (calories xai_rostit) 700)
      (= (calories parrillada_verdures) 340)
      (= (calories amanida_de_espinacs) 170)
      (= (calories llenguado_amb_lima) 500)
      (= (calories amanida_cesar) 180)
      (= (calories salmo_grillat) 520)
      (= (calories amanida_de_remolatxa) 160)
      (= (calories tortellinis_carne) 600)
      (= (calories crema_catalana) 250)
      (= (calories pennes_amb_pesto) 500)
      (= (calories bacalla_amb_tomate) 550)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (= (preu botifarra_brasa) 6)
      (= (preu crema_de_carxofa) 3)
      (= (preu amanida_de_cogombre) 3)
      (= (preu sopa_de_marisc) 6)
      (= (preu croquetes_carn) 4)
      (= (preu tallarins_carbonara) 5)
      (= (preu sopa_de_peix) 5)
      (= (preu verdures_amb_salsa) 4)
      (= (preu hummus) 4)
      (= (preu escalivada_verdures) 3)
      (= (preu estofat_llenties) 5)
      (= (preu llobarro_forn) 5)
      (= (preu sopa_de_peix) 6)
      (= (preu xai_rostit) 9)
      (= (preu parrillada_verdures) 5)
      (= (preu amanida_de_espinacs) 3)
      (= (preu llenguado_amb_lima) 8)
      (= (preu amanida_cesar) 4)
      (= (preu salmo_grillat) 9)
      (= (preu amanida_de_remolatxa) 3)
      (= (preu tortellinis_carne) 7)
      (= (preu crema_catalana) 4)
      (= (preu pennes_amb_pesto) 6)
      (= (preu bacalla_amb_tomate) 7)
      (= (costDiari) 0)
      (= (costTotal) 0)
      (platObligatori tortellinis_carne dilluns)
      (platObligatori crema_de_carxofa dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )