(define (problem menu-ext5b-2)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_verdures amanida_de_tomaquet cigrons_saltejats crema_espinacs crema_de_carxofa crema_de_bolets sopa_de_peix amanida_fasols raviolis_ricotta fajitas_verdures amanida_quinoa gnocchi_pesto - primer
  sopa_de_peix botifarra_a_la_planxa faves_estofades crema_avellana parrillada_verdures sopa_de_galets crema_de_xocolata filet_porc truita_verdures pollastre_a_la_planxa salmo_grillat cuixa_ànec - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible amanida_de_tomaquet cuixa_ànec)
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible crema_espinacs botifarra_a_la_planxa)
  (incompatible crema_espinacs filet_porc)
  (incompatible crema_espinacs pollastre_a_la_planxa)
  (incompatible crema_espinacs salmo_grillat)
  (incompatible crema_espinacs cuixa_ànec)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa pollastre_a_la_planxa)
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible crema_de_carxofa cuixa_ànec)
  (incompatible crema_de_bolets botifarra_a_la_planxa)
  (incompatible crema_de_bolets filet_porc)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible sopa_de_peix truita_verdures)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible raviolis_ricotta crema_avellana)
  (incompatible raviolis_ricotta crema_de_xocolata)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures pollastre_a_la_planxa)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible amanida_quinoa botifarra_a_la_planxa)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible amanida_quinoa cuixa_ànec)
  (incompatible gnocchi_pesto crema_avellana)
  (incompatible gnocchi_pesto crema_de_xocolata)
  (platTipus sopa_verdures sopa)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus cigrons_saltejats llegums)
  (platTipus crema_espinacs crema)
  (platTipus crema_de_carxofa crema)
  (platTipus crema_de_bolets crema)
  (platTipus sopa_de_peix sopa)
  (platTipus amanida_fasols llegums)
  (platTipus raviolis_ricotta pasta)
  (platTipus fajitas_verdures verdures)
  (platTipus amanida_quinoa amanida)
  (platTipus gnocchi_pesto pasta)
  (platTipus sopa_de_peix sopa)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus faves_estofades llegums)
  (platTipus crema_avellana crema)
  (platTipus parrillada_verdures verdures)
  (platTipus sopa_de_galets sopa)
  (platTipus crema_de_xocolata crema)
  (platTipus filet_porc carn)
  (platTipus truita_verdures verdures)
  (platTipus pollastre_a_la_planxa carn)
  (platTipus salmo_grillat peix)
  (platTipus cuixa_ànec carn)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_verdures) 480)
  (= (calories amanida_de_tomaquet) 270)
  (= (calories cigrons_saltejats) 570)
  (= (calories crema_espinacs) 380)
  (= (calories crema_de_carxofa) 320)
  (= (calories crema_de_bolets) 390)
  (= (calories sopa_de_peix) 450)
  (= (calories amanida_fasols) 560)
  (= (calories raviolis_ricotta) 680)
  (= (calories fajitas_verdures) 390)
  (= (calories amanida_quinoa) 360)
  (= (calories gnocchi_pesto) 740)
  (= (calories sopa_de_peix) 520)
  (= (calories botifarra_a_la_planxa) 880)
  (= (calories faves_estofades) 730)
  (= (calories crema_avellana) 480)
  (= (calories parrillada_verdures) 550)
  (= (calories sopa_de_galets) 470)
  (= (calories crema_de_xocolata) 450)
  (= (calories filet_porc) 900)
  (= (calories truita_verdures) 500)
  (= (calories pollastre_a_la_planxa) 940)
  (= (calories salmo_grillat) 780)
  (= (calories cuixa_ànec) 980)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (= (preu sopa_verdures) 4)
  (= (preu amanida_de_tomaquet) 3)
  (= (preu cigrons_saltejats) 4)
  (= (preu crema_espinacs) 4)
  (= (preu crema_de_carxofa) 3)
  (= (preu crema_de_bolets) 4)
  (= (preu sopa_de_peix) 5)
  (= (preu amanida_fasols) 4)
  (= (preu raviolis_ricotta) 5)
  (= (preu fajitas_verdures) 4)
  (= (preu amanida_quinoa) 4)
  (= (preu gnocchi_pesto) 5)
  (= (preu sopa_de_peix) 6)
  (= (preu botifarra_a_la_planxa) 7)
  (= (preu faves_estofades) 6)
  (= (preu crema_avellana) 5)
  (= (preu parrillada_verdures) 5)
  (= (preu sopa_de_galets) 4)
  (= (preu crema_de_xocolata) 5)
  (= (preu filet_porc) 8)
  (= (preu truita_verdures) 4)
  (= (preu pollastre_a_la_planxa) 8)
  (= (preu salmo_grillat) 9)
  (= (preu cuixa_ànec) 9)
  (= (costDiari) 0)
  (= (costTotal) 0)
  (platObligatori botifarra_a_la_planxa dimarts)
  (platObligatori amanida_de_tomaquet dijous)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )