      (define (problem menu-ext5b-3)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_peix amanida_catalana estofat_llenties crema_de_carabasso sopa_de_cigrons cigrons_saltejats ceviche_tonyina crema_de_carbassa verdures_amb_salsa verdures_a_la_planxa raviolis_ricotta hummus - primer
  tortellinis_carne crema_de_xocolata truita_de_llenties truita_verdures crema_catalana tataki_verdures espaguetis_marisc faves_estofades amanida_cesar botifarra_a_la_planxa crema_de_limon salmo_grillat - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible sopa_de_peix tortellinis_carne)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix espaguetis_marisc)
      (incompatible amanida_catalana botifarra_a_la_planxa)
      (incompatible amanida_catalana salmo_grillat)
      (incompatible estofat_llenties tortellinis_carne)
      (incompatible estofat_llenties espaguetis_marisc)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible crema_de_carabasso botifarra_a_la_planxa)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible sopa_de_cigrons tortellinis_carne)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons espaguetis_marisc)
      (incompatible cigrons_saltejats tortellinis_carne)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible cigrons_saltejats salmo_grillat)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible ceviche_tonyina crema_catalana)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible ceviche_tonyina crema_de_limon)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible verdures_amb_salsa botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible raviolis_ricotta crema_catalana)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible raviolis_ricotta crema_de_limon)
      (incompatible hummus tortellinis_carne)
      (incompatible hummus espaguetis_marisc)
      (incompatible hummus salmo_grillat)
      (platTipus sopa_de_peix sopa)
      (platTipus amanida_catalana amanida)
      (platTipus estofat_llenties llegums)
      (platTipus crema_de_carabasso crema)
      (platTipus sopa_de_cigrons sopa)
      (platTipus cigrons_saltejats llegums)
      (platTipus ceviche_tonyina peix)
      (platTipus crema_de_carbassa crema)
      (platTipus verdures_amb_salsa verdures)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus raviolis_ricotta pasta)
      (platTipus hummus llegums)
      (platTipus tortellinis_carne pasta)
      (platTipus crema_de_xocolata crema)
      (platTipus truita_de_llenties llegums)
      (platTipus truita_verdures verdures)
      (platTipus crema_catalana crema)
      (platTipus tataki_verdures verdures)
      (platTipus espaguetis_marisc pasta)
      (platTipus faves_estofades llegums)
      (platTipus amanida_cesar amanida)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus crema_de_limon crema)
      (platTipus salmo_grillat peix)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories sopa_de_peix) 250)
      (= (calories amanida_catalana) 150)
      (= (calories estofat_llenties) 350)
      (= (calories crema_de_carabasso) 170)
      (= (calories sopa_de_cigrons) 300)
      (= (calories cigrons_saltejats) 330)
      (= (calories ceviche_tonyina) 220)
      (= (calories crema_de_carbassa) 180)
      (= (calories verdures_amb_salsa) 200)
      (= (calories verdures_a_la_planxa) 150)
      (= (calories raviolis_ricotta) 400)
      (= (calories hummus) 300)
      (= (calories tortellinis_carne) 600)
      (= (calories crema_de_xocolata) 260)
      (= (calories truita_de_llenties) 400)
      (= (calories truita_verdures) 300)
      (= (calories crema_catalana) 250)
      (= (calories tataki_verdures) 320)
      (= (calories espaguetis_marisc) 550)
      (= (calories faves_estofades) 480)
      (= (calories amanida_cesar) 180)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories crema_de_limon) 240)
      (= (calories salmo_grillat) 520)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (= (preu sopa_de_peix) 5)
      (= (preu amanida_catalana) 4)
      (= (preu estofat_llenties) 5)
      (= (preu crema_de_carabasso) 2)
      (= (preu sopa_de_cigrons) 4)
      (= (preu cigrons_saltejats) 4)
      (= (preu ceviche_tonyina) 6)
      (= (preu crema_de_carbassa) 3)
      (= (preu verdures_amb_salsa) 4)
      (= (preu verdures_a_la_planxa) 3)
      (= (preu raviolis_ricotta) 5)
      (= (preu hummus) 4)
      (= (preu tortellinis_carne) 7)
      (= (preu crema_de_xocolata) 5)
      (= (preu truita_de_llenties) 5)
      (= (preu truita_verdures) 4)
      (= (preu crema_catalana) 4)
      (= (preu tataki_verdures) 5)
      (= (preu espaguetis_marisc) 6)
      (= (preu faves_estofades) 6)
      (= (preu amanida_cesar) 4)
      (= (preu botifarra_a_la_planxa) 7)
      (= (preu crema_de_limon) 4)
      (= (preu salmo_grillat) 9)
      (= (costDiari) 0)
      (= (costTotal) 0)
      (platObligatori botifarra_a_la_planxa dijous)
      (platObligatori tortellinis_carne dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )