(define (problem menu-ext5b-4)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_marisc sopa_de_peix estofat_llenties verdures_amb_salsa verdures_a_la_planxa brocoli_allada amanida_fasols crema_de_carbassa sopa_verdures amanida_quinoa gnocchi_pesto raviolis_ricotta - primer
  crema_catalana botifarra_a_la_planxa orata_forno parrillada_verdures truita_de_llenties wok_verdures crema_de_xocolata estofat_cigrons filet_porc crema_avellana cuixa_ànec sopa_de_pedra - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible sopa_de_peix wok_verdures)
  (incompatible estofat_llenties orata_forno)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa filet_porc)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible brocoli_allada filet_porc)
  (incompatible brocoli_allada cuixa_ànec)
  (incompatible brocoli_allada sopa_de_pedra)
  (incompatible amanida_fasols orata_forno)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa orata_forno)
  (incompatible crema_de_carbassa filet_porc)
  (incompatible crema_de_carbassa cuixa_ànec)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures wok_verdures)
  (incompatible amanida_quinoa botifarra_a_la_planxa)
  (incompatible amanida_quinoa orata_forno)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa cuixa_ànec)
  (incompatible gnocchi_pesto crema_catalana)
  (incompatible gnocchi_pesto crema_de_xocolata)
  (incompatible gnocchi_pesto crema_avellana)
  (incompatible raviolis_ricotta crema_catalana)
  (incompatible raviolis_ricotta crema_de_xocolata)
  (incompatible raviolis_ricotta crema_avellana)
  (platTipus sopa_de_marisc sopa)
  (platTipus sopa_de_peix sopa)
  (platTipus estofat_llenties llegums)
  (platTipus verdures_amb_salsa verdures)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus brocoli_allada verdures)
  (platTipus amanida_fasols llegums)
  (platTipus crema_de_carbassa crema)
  (platTipus sopa_verdures sopa)
  (platTipus amanida_quinoa amanida)
  (platTipus gnocchi_pesto pasta)
  (platTipus raviolis_ricotta pasta)
  (platTipus crema_catalana crema)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus orata_forno peix)
  (platTipus parrillada_verdures verdures)
  (platTipus truita_de_llenties llegums)
  (platTipus wok_verdures verdures)
  (platTipus crema_de_xocolata crema)
  (platTipus estofat_cigrons llegums)
  (platTipus filet_porc carn)
  (platTipus crema_avellana crema)
  (platTipus cuixa_ànec carn)
  (platTipus sopa_de_pedra sopa)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_de_marisc) 560)
  (= (calories sopa_de_peix) 450)
  (= (calories estofat_llenties) 600)
  (= (calories verdures_amb_salsa) 380)
  (= (calories verdures_a_la_planxa) 300)
  (= (calories brocoli_allada) 360)
  (= (calories amanida_fasols) 560)
  (= (calories crema_de_carbassa) 350)
  (= (calories sopa_verdures) 480)
  (= (calories amanida_quinoa) 360)
  (= (calories gnocchi_pesto) 740)
  (= (calories raviolis_ricotta) 680)
  (= (calories crema_catalana) 440)
  (= (calories botifarra_a_la_planxa) 880)
  (= (calories orata_forno) 800)
  (= (calories parrillada_verdures) 550)
  (= (calories truita_de_llenties) 620)
  (= (calories wok_verdures) 540)
  (= (calories crema_de_xocolata) 450)
  (= (calories estofat_cigrons) 690)
  (= (calories filet_porc) 900)
  (= (calories crema_avellana) 480)
  (= (calories cuixa_ànec) 980)
  (= (calories sopa_de_pedra) 500)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (= (preu sopa_de_marisc) 6)
  (= (preu sopa_de_peix) 5)
  (= (preu estofat_llenties) 5)
  (= (preu verdures_amb_salsa) 4)
  (= (preu verdures_a_la_planxa) 3)
  (= (preu brocoli_allada) 3)
  (= (preu amanida_fasols) 4)
  (= (preu crema_de_carbassa) 3)
  (= (preu sopa_verdures) 4)
  (= (preu amanida_quinoa) 4)
  (= (preu gnocchi_pesto) 5)
  (= (preu raviolis_ricotta) 5)
  (= (preu crema_catalana) 4)
  (= (preu botifarra_a_la_planxa) 7)
  (= (preu orata_forno) 8)
  (= (preu parrillada_verdures) 5)
  (= (preu truita_de_llenties) 5)
  (= (preu wok_verdures) 4)
  (= (preu crema_de_xocolata) 5)
  (= (preu estofat_cigrons) 5)
  (= (preu filet_porc) 8)
  (= (preu crema_avellana) 5)
  (= (preu cuixa_ànec) 9)
  (= (preu sopa_de_pedra) 5)
  (= (costDiari) 0)
  (= (costTotal) 0)
  (platObligatori sopa_de_peix dijous)
  (platObligatori sopa_verdures dimecres)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )