(define (problem menu-ext5b-3)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_marisc fajitas_verdures truita_potatge penne_arrabiata cigrons_saltejats amanida_catalana escalivada_verdures brocoli_allada macarrons_forn verdures_amb_salsa sopa_de_cigrons crema_espinacs - primer
  estofat_soja botifarra_a_la_planxa parrillada_verdures tataki_verdures filet_porc salmo_grillat hamburguesa_mongeta wok_verdures turbot_planxa sopa_de_peix llenguado_amb_lima estofat_cigrons - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible truita_potatge salmo_grillat)
  (incompatible truita_potatge turbot_planxa)
  (incompatible truita_potatge llenguado_amb_lima)
  (incompatible cigrons_saltejats salmo_grillat)
  (incompatible cigrons_saltejats turbot_planxa)
  (incompatible cigrons_saltejats llenguado_amb_lima)
  (incompatible amanida_catalana botifarra_a_la_planxa)
  (incompatible amanida_catalana filet_porc)
  (incompatible amanida_catalana salmo_grillat)
  (incompatible amanida_catalana turbot_planxa)
  (incompatible amanida_catalana llenguado_amb_lima)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures filet_porc)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible brocoli_allada filet_porc)
  (incompatible brocoli_allada sopa_de_peix)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible sopa_de_cigrons tataki_verdures)
  (incompatible sopa_de_cigrons wok_verdures)
  (incompatible crema_espinacs botifarra_a_la_planxa)
  (incompatible crema_espinacs filet_porc)
  (incompatible crema_espinacs salmo_grillat)
  (incompatible crema_espinacs turbot_planxa)
  (incompatible crema_espinacs llenguado_amb_lima)
  (platTipus sopa_de_marisc sopa)
  (platTipus fajitas_verdures verdures)
  (platTipus truita_potatge llegums)
  (platTipus penne_arrabiata pasta)
  (platTipus cigrons_saltejats llegums)
  (platTipus amanida_catalana amanida)
  (platTipus escalivada_verdures verdures)
  (platTipus brocoli_allada verdures)
  (platTipus macarrons_forn pasta)
  (platTipus verdures_amb_salsa verdures)
  (platTipus sopa_de_cigrons sopa)
  (platTipus crema_espinacs crema)
  (platTipus estofat_soja llegums)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus parrillada_verdures verdures)
  (platTipus tataki_verdures verdures)
  (platTipus filet_porc carn)
  (platTipus salmo_grillat peix)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus wok_verdures verdures)
  (platTipus turbot_planxa peix)
  (platTipus sopa_de_peix sopa)
  (platTipus llenguado_amb_lima peix)
  (platTipus estofat_cigrons llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
  (= (calories sopa_de_marisc) 560)
  (= (calories fajitas_verdures) 390)
  (= (calories truita_potatge) 580)
  (= (calories penne_arrabiata) 720)
  (= (calories cigrons_saltejats) 570)
  (= (calories amanida_catalana) 300)
  (= (calories escalivada_verdures) 350)
  (= (calories brocoli_allada) 360)
  (= (calories macarrons_forn) 650)
  (= (calories verdures_amb_salsa) 380)
  (= (calories sopa_de_cigrons) 530)
  (= (calories crema_espinacs) 380)
  (= (calories estofat_soja) 700)
  (= (calories botifarra_a_la_planxa) 880)
  (= (calories parrillada_verdures) 550)
  (= (calories tataki_verdures) 520)
  (= (calories filet_porc) 900)
  (= (calories salmo_grillat) 780)
  (= (calories hamburguesa_mongeta) 670)
  (= (calories wok_verdures) 540)
  (= (calories turbot_planxa) 790)
  (= (calories sopa_de_peix) 520)
  (= (calories llenguado_amb_lima) 750)
  (= (calories estofat_cigrons) 690)
  (= (minCalories) 1000)
  (= (maxCalories) 1500)
  (= (preu sopa_de_marisc) 6)
  (= (preu fajitas_verdures) 4)
  (= (preu truita_potatge) 5)
  (= (preu penne_arrabiata) 5)
  (= (preu cigrons_saltejats) 4)
  (= (preu amanida_catalana) 4)
  (= (preu escalivada_verdures) 3)
  (= (preu brocoli_allada) 3)
  (= (preu macarrons_forn) 4)
  (= (preu verdures_amb_salsa) 4)
  (= (preu sopa_de_cigrons) 4)
  (= (preu crema_espinacs) 4)
  (= (preu estofat_soja) 5)
  (= (preu botifarra_a_la_planxa) 7)
  (= (preu parrillada_verdures) 5)
  (= (preu tataki_verdures) 5)
  (= (preu filet_porc) 8)
  (= (preu salmo_grillat) 9)
  (= (preu hamburguesa_mongeta) 5)
  (= (preu wok_verdures) 4)
  (= (preu turbot_planxa) 8)
  (= (preu sopa_de_peix) 6)
  (= (preu llenguado_amb_lima) 8)
  (= (preu estofat_cigrons) 5)
  (= (costDiari) 0)
  (= (costTotal) 0)
  (platObligatori macarrons_forn dijous)
  (platObligatori botifarra_a_la_planxa dilluns)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )