      (define (problem menu-ext5b-1)
        (:domain menuext5b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  macarrons_forn croquetes_carn carpaccio_vedella llobarro_forn cigrons_saltejats sopa_de_cigrons ceviche_tonyina hummus sopa_de_marisc sopa_de_peix tataki_salmo amanida_catalana - primer
  pollastre_a_la_planxa pennes_amb_pesto truita_verdures parrillada_verdures crema_de_xocolata botifarra_a_la_planxa crema_de_limon amanida_cesar faves_estofades espaguetis_marisc estofat_cigrons tataki_verdures - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn amanida_cesar)
      (incompatible croquetes_carn truita_verdures)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible croquetes_carn tataki_verdures)
      (incompatible carpaccio_vedella truita_verdures)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible llobarro_forn pollastre_a_la_planxa)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible cigrons_saltejats pennes_amb_pesto)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons espaguetis_marisc)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible ceviche_tonyina pollastre_a_la_planxa)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible ceviche_tonyina botifarra_a_la_planxa)
      (incompatible ceviche_tonyina crema_de_limon)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus espaguetis_marisc)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_marisc truita_verdures)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc espaguetis_marisc)
      (incompatible sopa_de_marisc tataki_verdures)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix espaguetis_marisc)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible tataki_salmo pollastre_a_la_planxa)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible amanida_catalana pollastre_a_la_planxa)
      (incompatible amanida_catalana botifarra_a_la_planxa)
      (platTipus macarrons_forn pasta)
      (platTipus croquetes_carn carn)
      (platTipus carpaccio_vedella carn)
      (platTipus llobarro_forn peix)
      (platTipus cigrons_saltejats llegums)
      (platTipus sopa_de_cigrons sopa)
      (platTipus ceviche_tonyina peix)
      (platTipus hummus llegums)
      (platTipus sopa_de_marisc sopa)
      (platTipus sopa_de_peix sopa)
      (platTipus tataki_salmo peix)
      (platTipus amanida_catalana amanida)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus pennes_amb_pesto pasta)
      (platTipus truita_verdures verdures)
      (platTipus parrillada_verdures verdures)
      (platTipus crema_de_xocolata crema)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus crema_de_limon crema)
      (platTipus amanida_cesar amanida)
      (platTipus faves_estofades llegums)
      (platTipus espaguetis_marisc pasta)
      (platTipus estofat_cigrons llegums)
      (platTipus tataki_verdures verdures)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
      (= (calories macarrons_forn) 380)
      (= (calories croquetes_carn) 250)
      (= (calories carpaccio_vedella) 200)
      (= (calories llobarro_forn) 260)
      (= (calories cigrons_saltejats) 330)
      (= (calories sopa_de_cigrons) 300)
      (= (calories ceviche_tonyina) 220)
      (= (calories hummus) 300)
      (= (calories sopa_de_marisc) 320)
      (= (calories sopa_de_peix) 250)
      (= (calories tataki_salmo) 240)
      (= (calories amanida_catalana) 150)
      (= (calories pollastre_a_la_planxa) 650)
      (= (calories pennes_amb_pesto) 500)
      (= (calories truita_verdures) 300)
      (= (calories parrillada_verdures) 340)
      (= (calories crema_de_xocolata) 260)
      (= (calories botifarra_a_la_planxa) 600)
      (= (calories crema_de_limon) 240)
      (= (calories amanida_cesar) 180)
      (= (calories faves_estofades) 480)
      (= (calories espaguetis_marisc) 550)
      (= (calories estofat_cigrons) 450)
      (= (calories tataki_verdures) 320)
      (= (minCalories) 1000)
      (= (maxCalories) 1500)
      (= (preu macarrons_forn) 4)
      (= (preu croquetes_carn) 4)
      (= (preu carpaccio_vedella) 7)
      (= (preu llobarro_forn) 5)
      (= (preu cigrons_saltejats) 4)
      (= (preu sopa_de_cigrons) 4)
      (= (preu ceviche_tonyina) 6)
      (= (preu hummus) 4)
      (= (preu sopa_de_marisc) 6)
      (= (preu sopa_de_peix) 5)
      (= (preu tataki_salmo) 7)
      (= (preu amanida_catalana) 4)
      (= (preu pollastre_a_la_planxa) 8)
      (= (preu pennes_amb_pesto) 6)
      (= (preu truita_verdures) 4)
      (= (preu parrillada_verdures) 5)
      (= (preu crema_de_xocolata) 5)
      (= (preu botifarra_a_la_planxa) 7)
      (= (preu crema_de_limon) 4)
      (= (preu amanida_cesar) 4)
      (= (preu faves_estofades) 6)
      (= (preu espaguetis_marisc) 6)
      (= (preu estofat_cigrons) 5)
      (= (preu tataki_verdures) 5)
      (= (costDiari) 0)
      (= (costTotal) 0)
      (platObligatori macarrons_forn dijous)
      (platObligatori carpaccio_vedella dimarts)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))
        (:metric minimize (costTotal))
      )