(define (problem menuext5b-tc2)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
raviolis_ricotta crema_de_carabasso tallarins_carbonara escalivada_verdures amanida_de_tomaquet crema_de_carxofa estofat_llenties macarrons_forn amanida_quinoa brocoli_allada - primer
truita_verdures sopa_de_peix curry_verdures hamburguesa_mongeta salmo_grillat xai_rostit bacalla_amb_tomaquet sopa_de_galets orata_forno faves_estofades - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible brocoli_allada sopa_de_galets)
    (incompatible brocoli_allada sopa_de_peix)
    (incompatible crema_de_carxofa xai_rostit)
    (incompatible amanida_de_tomaquet orata_forno)
    (incompatible amanida_de_tomaquet bacalla_amb_tomaquet)
    (incompatible crema_de_carabasso bacalla_amb_tomaquet)
    (incompatible escalivada_verdures sopa_de_galets)
    (incompatible crema_de_carabasso xai_rostit)
    (platTipus raviolis_ricotta pasta)
    (platTipus crema_de_carabasso crema)
    (platTipus tallarins_carbonara pasta)
    (platTipus escalivada_verdures verdures)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus crema_de_carxofa crema)
    (platTipus estofat_llenties llegums)
    (platTipus macarrons_forn pasta)
    (platTipus amanida_quinoa amanida)
    (platTipus brocoli_allada verdures)
    (platTipus truita_verdures verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus curry_verdures verdures)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus salmo_grillat peix)
    (platTipus xai_rostit carn)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus sopa_de_galets sopa)
    (platTipus orata_forno peix)
    (platTipus faves_estofades llegums)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori hamburguesa_mongeta dijous)
    (platObligatori estofat_llenties dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories raviolis_ricotta) 680)
    (= (calories crema_de_carabasso) 330)
    (= (calories tallarins_carbonara) 700)
    (= (calories escalivada_verdures) 350)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories crema_de_carxofa) 320)
    (= (calories estofat_llenties) 600)
    (= (calories macarrons_forn) 650)
    (= (calories amanida_quinoa) 360)
    (= (calories brocoli_allada) 360)
    (= (calories truita_verdures) 500)
    (= (calories sopa_de_peix) 520)
    (= (calories curry_verdures) 580)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories salmo_grillat) 780)
    (= (calories xai_rostit) 1000)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories sopa_de_galets) 470)
    (= (calories orata_forno) 800)
    (= (calories faves_estofades) 730)
    (= (preu raviolis_ricotta) 5)
    (= (preu crema_de_carabasso) 2)
    (= (preu tallarins_carbonara) 5)
    (= (preu escalivada_verdures) 3)
    (= (preu amanida_de_tomaquet) 3)
    (= (preu crema_de_carxofa) 3)
    (= (preu estofat_llenties) 5)
    (= (preu macarrons_forn) 4)
    (= (preu amanida_quinoa) 4)
    (= (preu brocoli_allada) 3)
    (= (preu truita_verdures) 4)
    (= (preu sopa_de_peix) 6)
    (= (preu curry_verdures) 5)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu salmo_grillat) 9)
    (= (preu xai_rostit) 9)
    (= (preu bacalla_amb_tomaquet) 7)
    (= (preu sopa_de_galets) 4)
    (= (preu orata_forno) 8)
    (= (preu faves_estofades) 6)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )