(define (problem menuext5b-tc1)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
gnocchi_pesto macarrons_forn verdures_a_la_planxa crema_espinacs sopa_de_marisc crema_de_bolets crema_de_carxofa sopa_miso hummus raviolis_ricotta - primer
crema_catalana sopa_de_pedra crema_taronja cuixa_ànec salmo_grillat bacalla_amb_tomate truita_verdures sopa_de_peix estofat_cigrons crema_de_limon - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carxofa bacalla_amb_tomate)
    (incompatible sopa_miso truita_verdures)
    (incompatible crema_espinacs cuixa_ànec)
    (incompatible crema_de_bolets salmo_grillat)
    (incompatible macarrons_forn crema_de_limon)
    (incompatible gnocchi_pesto crema_catalana)
    (incompatible macarrons_forn crema_taronja)
    (incompatible macarrons_forn crema_catalana)
    (platTipus gnocchi_pesto pasta)
    (platTipus macarrons_forn pasta)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus crema_espinacs crema)
    (platTipus sopa_de_marisc sopa)
    (platTipus crema_de_bolets crema)
    (platTipus crema_de_carxofa crema)
    (platTipus sopa_miso sopa)
    (platTipus hummus llegums)
    (platTipus raviolis_ricotta pasta)
    (platTipus crema_catalana crema)
    (platTipus sopa_de_pedra sopa)
    (platTipus crema_taronja crema)
    (platTipus cuixa_ànec carn)
    (platTipus salmo_grillat peix)
    (platTipus bacalla_amb_tomate peix)
    (platTipus truita_verdures verdures)
    (platTipus sopa_de_peix sopa)
    (platTipus estofat_cigrons llegums)
    (platTipus crema_de_limon crema)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori bacalla_amb_tomate dimecres)
    (platObligatori sopa_de_marisc dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories gnocchi_pesto) 740)
    (= (calories macarrons_forn) 650)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories crema_espinacs) 380)
    (= (calories sopa_de_marisc) 560)
    (= (calories crema_de_bolets) 390)
    (= (calories crema_de_carxofa) 320)
    (= (calories sopa_miso) 500)
    (= (calories hummus) 530)
    (= (calories raviolis_ricotta) 680)
    (= (calories crema_catalana) 440)
    (= (calories sopa_de_pedra) 500)
    (= (calories crema_taronja) 410)
    (= (calories cuixa_ànec) 980)
    (= (calories salmo_grillat) 780)
    (= (calories bacalla_amb_tomate) 810)
    (= (calories truita_verdures) 500)
    (= (calories sopa_de_peix) 520)
    (= (calories estofat_cigrons) 690)
    (= (calories crema_de_limon) 430)
    (= (preu gnocchi_pesto) 5)
    (= (preu macarrons_forn) 4)
    (= (preu verdures_a_la_planxa) 3)
    (= (preu crema_espinacs) 4)
    (= (preu sopa_de_marisc) 6)
    (= (preu crema_de_bolets) 4)
    (= (preu crema_de_carxofa) 3)
    (= (preu sopa_miso) 5)
    (= (preu hummus) 4)
    (= (preu raviolis_ricotta) 5)
    (= (preu crema_catalana) 4)
    (= (preu sopa_de_pedra) 5)
    (= (preu crema_taronja) 4)
    (= (preu cuixa_ànec) 9)
    (= (preu salmo_grillat) 9)
    (= (preu bacalla_amb_tomate) 7)
    (= (preu truita_verdures) 4)
    (= (preu sopa_de_peix) 6)
    (= (preu estofat_cigrons) 5)
    (= (preu crema_de_limon) 4)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )