(define (problem menuext5b-tc5)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
truita_potatge sopa_de_cigrons amanida_de_cogombre amanida_catalana verdures_a_la_planxa penne_arrabiata verdures_amb_salsa crema_espinacs sopa_verdures amanida_quinoa - primer
crema_de_limon turbot_planxa filet_porc bacalla_amb_tomate crema_taronja estofat_cigrons faves_estofades truita_de_llenties salmo_grillat wok_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_espinacs filet_porc)
    (incompatible crema_espinacs salmo_grillat)
    (incompatible penne_arrabiata crema_taronja)
    (incompatible amanida_catalana salmo_grillat)
    (incompatible truita_potatge turbot_planxa)
    (incompatible amanida_quinoa salmo_grillat)
    (incompatible crema_espinacs bacalla_amb_tomate)
    (incompatible truita_potatge salmo_grillat)
    (platTipus truita_potatge llegums)
    (platTipus sopa_de_cigrons sopa)
    (platTipus amanida_de_cogombre amanida)
    (platTipus amanida_catalana amanida)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus penne_arrabiata pasta)
    (platTipus verdures_amb_salsa verdures)
    (platTipus crema_espinacs crema)
    (platTipus sopa_verdures sopa)
    (platTipus amanida_quinoa amanida)
    (platTipus crema_de_limon crema)
    (platTipus turbot_planxa peix)
    (platTipus filet_porc carn)
    (platTipus bacalla_amb_tomate peix)
    (platTipus crema_taronja crema)
    (platTipus estofat_cigrons llegums)
    (platTipus faves_estofades llegums)
    (platTipus truita_de_llenties llegums)
    (platTipus salmo_grillat peix)
    (platTipus wok_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori turbot_planxa dijous)
    (platObligatori crema_de_limon dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories truita_potatge) 580)
    (= (calories sopa_de_cigrons) 530)
    (= (calories amanida_de_cogombre) 260)
    (= (calories amanida_catalana) 300)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories penne_arrabiata) 720)
    (= (calories verdures_amb_salsa) 380)
    (= (calories crema_espinacs) 380)
    (= (calories sopa_verdures) 480)
    (= (calories amanida_quinoa) 360)
    (= (calories crema_de_limon) 430)
    (= (calories turbot_planxa) 790)
    (= (calories filet_porc) 900)
    (= (calories bacalla_amb_tomate) 810)
    (= (calories crema_taronja) 410)
    (= (calories estofat_cigrons) 690)
    (= (calories faves_estofades) 730)
    (= (calories truita_de_llenties) 620)
    (= (calories salmo_grillat) 780)
    (= (calories wok_verdures) 540)
    (= (preu truita_potatge) 5)
    (= (preu sopa_de_cigrons) 4)
    (= (preu amanida_de_cogombre) 3)
    (= (preu amanida_catalana) 4)
    (= (preu verdures_a_la_planxa) 3)
    (= (preu penne_arrabiata) 5)
    (= (preu verdures_amb_salsa) 4)
    (= (preu crema_espinacs) 4)
    (= (preu sopa_verdures) 4)
    (= (preu amanida_quinoa) 4)
    (= (preu crema_de_limon) 4)
    (= (preu turbot_planxa) 8)
    (= (preu filet_porc) 8)
    (= (preu bacalla_amb_tomate) 7)
    (= (preu crema_taronja) 4)
    (= (preu estofat_cigrons) 5)
    (= (preu faves_estofades) 6)
    (= (preu truita_de_llenties) 5)
    (= (preu salmo_grillat) 9)
    (= (preu wok_verdures) 4)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )