(define (problem menuext5b-tc3)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_de_cogombre crema_de_carxofa penne_arrabiata amanida_de_tomaquet sopa_de_cigrons estofat_llenties tallarins_carbonara amanida_quinoa crema_de_carbassa macarrons_forn - primer
sopa_ajo pollastre_a_la_planxa parrillada_verdures orata_forno xai_rostit crema_avellana botifarra_a_la_planxa sopa_de_peix sopa_ceba bacalla_amb_tomate - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carbassa botifarra_a_la_planxa)
    (incompatible estofat_llenties bacalla_amb_tomate)
    (incompatible macarrons_forn crema_avellana)
    (incompatible amanida_de_tomaquet orata_forno)
    (incompatible crema_de_carbassa orata_forno)
    (incompatible crema_de_carbassa pollastre_a_la_planxa)
    (incompatible amanida_quinoa xai_rostit)
    (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
    (platTipus amanida_de_cogombre amanida)
    (platTipus crema_de_carxofa crema)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus sopa_de_cigrons sopa)
    (platTipus estofat_llenties llegums)
    (platTipus tallarins_carbonara pasta)
    (platTipus amanida_quinoa amanida)
    (platTipus crema_de_carbassa crema)
    (platTipus macarrons_forn pasta)
    (platTipus sopa_ajo sopa)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus parrillada_verdures verdures)
    (platTipus orata_forno peix)
    (platTipus xai_rostit carn)
    (platTipus crema_avellana crema)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_ceba sopa)
    (platTipus bacalla_amb_tomate peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori sopa_ceba dilluns)
    (platObligatori estofat_llenties dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_de_cogombre) 260)
    (= (calories crema_de_carxofa) 320)
    (= (calories penne_arrabiata) 720)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories sopa_de_cigrons) 530)
    (= (calories estofat_llenties) 600)
    (= (calories tallarins_carbonara) 700)
    (= (calories amanida_quinoa) 360)
    (= (calories crema_de_carbassa) 350)
    (= (calories macarrons_forn) 650)
    (= (calories sopa_ajo) 490)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories parrillada_verdures) 550)
    (= (calories orata_forno) 800)
    (= (calories xai_rostit) 1000)
    (= (calories crema_avellana) 480)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories sopa_de_peix) 520)
    (= (calories sopa_ceba) 450)
    (= (calories bacalla_amb_tomate) 810)
    (= (preu amanida_de_cogombre) 3)
    (= (preu crema_de_carxofa) 3)
    (= (preu penne_arrabiata) 5)
    (= (preu amanida_de_tomaquet) 3)
    (= (preu sopa_de_cigrons) 4)
    (= (preu estofat_llenties) 5)
    (= (preu tallarins_carbonara) 5)
    (= (preu amanida_quinoa) 4)
    (= (preu crema_de_carbassa) 3)
    (= (preu macarrons_forn) 4)
    (= (preu sopa_ajo) 4)
    (= (preu pollastre_a_la_planxa) 8)
    (= (preu parrillada_verdures) 5)
    (= (preu orata_forno) 8)
    (= (preu xai_rostit) 9)
    (= (preu crema_avellana) 5)
    (= (preu botifarra_a_la_planxa) 7)
    (= (preu sopa_de_peix) 6)
    (= (preu sopa_ceba) 4)
    (= (preu bacalla_amb_tomate) 7)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )