(define (problem menuext5b-tc4)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
cigrons_saltejats hummus fajitas_verdures verdures_a_la_planxa crema_de_bolets penne_arrabiata crema_de_carxofa sopa_verdures sopa_de_marisc amanida_fasols - primer
parrillada_verdures salmo_grillat crema_avellana hamburguesa_mongeta sopa_ajo llenguado_amb_lima crema_taronja wok_verdures filet_porc sopa_ceba - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_de_carxofa salmo_grillat)
    (incompatible sopa_verdures wok_verdures)
    (incompatible sopa_verdures parrillada_verdures)
    (incompatible crema_de_carxofa filet_porc)
    (incompatible cigrons_saltejats llenguado_amb_lima)
    (incompatible sopa_de_marisc parrillada_verdures)
    (incompatible amanida_fasols salmo_grillat)
    (incompatible penne_arrabiata crema_taronja)
    (platTipus cigrons_saltejats llegums)
    (platTipus hummus llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus crema_de_bolets crema)
    (platTipus penne_arrabiata pasta)
    (platTipus crema_de_carxofa crema)
    (platTipus sopa_verdures sopa)
    (platTipus sopa_de_marisc sopa)
    (platTipus amanida_fasols llegums)
    (platTipus parrillada_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus crema_avellana crema)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus sopa_ajo sopa)
    (platTipus llenguado_amb_lima peix)
    (platTipus crema_taronja crema)
    (platTipus wok_verdures verdures)
    (platTipus filet_porc carn)
    (platTipus sopa_ceba sopa)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori llenguado_amb_lima dimarts)
    (platObligatori amanida_fasols dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories cigrons_saltejats) 570)
    (= (calories hummus) 530)
    (= (calories fajitas_verdures) 390)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories crema_de_bolets) 390)
    (= (calories penne_arrabiata) 720)
    (= (calories crema_de_carxofa) 320)
    (= (calories sopa_verdures) 480)
    (= (calories sopa_de_marisc) 560)
    (= (calories amanida_fasols) 560)
    (= (calories parrillada_verdures) 550)
    (= (calories salmo_grillat) 780)
    (= (calories crema_avellana) 480)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories sopa_ajo) 490)
    (= (calories llenguado_amb_lima) 750)
    (= (calories crema_taronja) 410)
    (= (calories wok_verdures) 540)
    (= (calories filet_porc) 900)
    (= (calories sopa_ceba) 450)
    (= (preu cigrons_saltejats) 4)
    (= (preu hummus) 4)
    (= (preu fajitas_verdures) 4)
    (= (preu verdures_a_la_planxa) 3)
    (= (preu crema_de_bolets) 4)
    (= (preu penne_arrabiata) 5)
    (= (preu crema_de_carxofa) 3)
    (= (preu sopa_verdures) 4)
    (= (preu sopa_de_marisc) 6)
    (= (preu amanida_fasols) 4)
    (= (preu parrillada_verdures) 5)
    (= (preu salmo_grillat) 9)
    (= (preu crema_avellana) 5)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu sopa_ajo) 4)
    (= (preu llenguado_amb_lima) 8)
    (= (preu crema_taronja) 4)
    (= (preu wok_verdures) 4)
    (= (preu filet_porc) 8)
    (= (preu sopa_ceba) 4)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )