(define (problem menuext5b-tc1)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_carabasso amanida_catalana penne_arrabiata crema_de_bolets amanida_de_tomaquet cigrons_saltejats estofat_llenties fajitas_verdures sopa_de_cigrons raviolis_ricotta - primer
bacalla_amb_tomaquet faves_estofades tataki_verdures crema_de_limon xai_rostit estofat_soja llenguado_amb_lima parrillada_verdures salmo_grillat botifarra_a_la_planxa - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible raviolis_ricotta crema_de_limon)
    (incompatible penne_arrabiata crema_de_limon)
    (incompatible sopa_de_cigrons tataki_verdures)
    (incompatible amanida_catalana salmo_grillat)
    (incompatible cigrons_saltejats bacalla_amb_tomaquet)
    (incompatible crema_de_bolets botifarra_a_la_planxa)
    (incompatible amanida_de_tomaquet xai_rostit)
    (incompatible amanida_de_tomaquet bacalla_amb_tomaquet)
    (platTipus crema_de_carabasso crema)
    (platTipus amanida_catalana amanida)
    (platTipus penne_arrabiata pasta)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus cigrons_saltejats llegums)
    (platTipus estofat_llenties llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus sopa_de_cigrons sopa)
    (platTipus raviolis_ricotta pasta)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus faves_estofades llegums)
    (platTipus tataki_verdures verdures)
    (platTipus crema_de_limon crema)
    (platTipus xai_rostit carn)
    (platTipus estofat_soja llegums)
    (platTipus llenguado_amb_lima peix)
    (platTipus parrillada_verdures verdures)
    (platTipus salmo_grillat peix)
    (platTipus botifarra_a_la_planxa carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori parrillada_verdures dilluns)
    (platObligatori estofat_llenties dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_de_carabasso) 330)
    (= (calories amanida_catalana) 300)
    (= (calories penne_arrabiata) 720)
    (= (calories crema_de_bolets) 390)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories cigrons_saltejats) 570)
    (= (calories estofat_llenties) 600)
    (= (calories fajitas_verdures) 390)
    (= (calories sopa_de_cigrons) 530)
    (= (calories raviolis_ricotta) 680)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories faves_estofades) 730)
    (= (calories tataki_verdures) 520)
    (= (calories crema_de_limon) 430)
    (= (calories xai_rostit) 1000)
    (= (calories estofat_soja) 700)
    (= (calories llenguado_amb_lima) 750)
    (= (calories parrillada_verdures) 550)
    (= (calories salmo_grillat) 780)
    (= (calories botifarra_a_la_planxa) 880)
    (= (preu crema_de_carabasso) 2)
    (= (preu amanida_catalana) 4)
    (= (preu penne_arrabiata) 5)
    (= (preu crema_de_bolets) 4)
    (= (preu amanida_de_tomaquet) 3)
    (= (preu cigrons_saltejats) 4)
    (= (preu estofat_llenties) 5)
    (= (preu fajitas_verdures) 4)
    (= (preu sopa_de_cigrons) 4)
    (= (preu raviolis_ricotta) 5)
    (= (preu bacalla_amb_tomaquet) 7)
    (= (preu faves_estofades) 6)
    (= (preu tataki_verdures) 5)
    (= (preu crema_de_limon) 4)
    (= (preu xai_rostit) 9)
    (= (preu estofat_soja) 5)
    (= (preu llenguado_amb_lima) 8)
    (= (preu parrillada_verdures) 5)
    (= (preu salmo_grillat) 9)
    (= (preu botifarra_a_la_planxa) 7)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )