(define (problem menuext5b-tc3)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
crema_de_bolets macarrons_forn crema_espinacs estofat_llenties fajitas_verdures sopa_verdures verdures_amb_salsa amanida_de_cogombre amanida_quinoa amanida_catalana - primer
wok_verdures pollastre_a_la_planxa tataki_verdures crema_avellana hamburguesa_mongeta turbot_planxa crema_de_limon curry_verdures crema_taronja salmo_grillat - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_espinacs turbot_planxa)
    (incompatible macarrons_forn crema_taronja)
    (incompatible amanida_quinoa pollastre_a_la_planxa)
    (incompatible fajitas_verdures pollastre_a_la_planxa)
    (incompatible amanida_de_cogombre salmo_grillat)
    (incompatible crema_espinacs salmo_grillat)
    (incompatible amanida_catalana salmo_grillat)
    (incompatible crema_espinacs pollastre_a_la_planxa)
    (platTipus crema_de_bolets crema)
    (platTipus macarrons_forn pasta)
    (platTipus crema_espinacs crema)
    (platTipus estofat_llenties llegums)
    (platTipus fajitas_verdures verdures)
    (platTipus sopa_verdures sopa)
    (platTipus verdures_amb_salsa verdures)
    (platTipus amanida_de_cogombre amanida)
    (platTipus amanida_quinoa amanida)
    (platTipus amanida_catalana amanida)
    (platTipus wok_verdures verdures)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus tataki_verdures verdures)
    (platTipus crema_avellana crema)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus turbot_planxa peix)
    (platTipus crema_de_limon crema)
    (platTipus curry_verdures verdures)
    (platTipus crema_taronja crema)
    (platTipus salmo_grillat peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori verdures_amb_salsa dilluns)
    (platObligatori crema_de_limon dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories crema_de_bolets) 390)
    (= (calories macarrons_forn) 650)
    (= (calories crema_espinacs) 380)
    (= (calories estofat_llenties) 600)
    (= (calories fajitas_verdures) 390)
    (= (calories sopa_verdures) 480)
    (= (calories verdures_amb_salsa) 380)
    (= (calories amanida_de_cogombre) 260)
    (= (calories amanida_quinoa) 360)
    (= (calories amanida_catalana) 300)
    (= (calories wok_verdures) 540)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories tataki_verdures) 520)
    (= (calories crema_avellana) 480)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories turbot_planxa) 790)
    (= (calories crema_de_limon) 430)
    (= (calories curry_verdures) 580)
    (= (calories crema_taronja) 410)
    (= (calories salmo_grillat) 780)
    (= (preu crema_de_bolets) 4)
    (= (preu macarrons_forn) 4)
    (= (preu crema_espinacs) 4)
    (= (preu estofat_llenties) 5)
    (= (preu fajitas_verdures) 4)
    (= (preu sopa_verdures) 4)
    (= (preu verdures_amb_salsa) 4)
    (= (preu amanida_de_cogombre) 3)
    (= (preu amanida_quinoa) 4)
    (= (preu amanida_catalana) 4)
    (= (preu wok_verdures) 4)
    (= (preu pollastre_a_la_planxa) 8)
    (= (preu tataki_verdures) 5)
    (= (preu crema_avellana) 5)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu turbot_planxa) 8)
    (= (preu crema_de_limon) 4)
    (= (preu curry_verdures) 5)
    (= (preu crema_taronja) 4)
    (= (preu salmo_grillat) 9)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )