(define (problem menuext5b-tc4)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_de_tomaquet sopa_verdures brocoli_allada crema_de_carxofa raviolis_ricotta penne_arrabiata amanida_de_cogombre escalivada_verdures sopa_miso amanida_fasols - primer
sopa_de_galets sopa_de_peix salmo_grillat botifarra_a_la_planxa xai_rostit parrillada_verdures sopa_de_pedra turbot_planxa sopa_ceba llenguado_amb_lima - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible brocoli_allada sopa_de_galets)
    (incompatible amanida_fasols llenguado_amb_lima)
    (incompatible crema_de_carxofa turbot_planxa)
    (incompatible crema_de_carxofa xai_rostit)
    (incompatible amanida_de_cogombre botifarra_a_la_planxa)
    (incompatible amanida_de_cogombre llenguado_amb_lima)
    (incompatible crema_de_carxofa salmo_grillat)
    (incompatible crema_de_carxofa botifarra_a_la_planxa)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus sopa_verdures sopa)
    (platTipus brocoli_allada verdures)
    (platTipus crema_de_carxofa crema)
    (platTipus raviolis_ricotta pasta)
    (platTipus penne_arrabiata pasta)
    (platTipus amanida_de_cogombre amanida)
    (platTipus escalivada_verdures verdures)
    (platTipus sopa_miso sopa)
    (platTipus amanida_fasols llegums)
    (platTipus sopa_de_galets sopa)
    (platTipus sopa_de_peix sopa)
    (platTipus salmo_grillat peix)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus xai_rostit carn)
    (platTipus parrillada_verdures verdures)
    (platTipus sopa_de_pedra sopa)
    (platTipus turbot_planxa peix)
    (platTipus sopa_ceba sopa)
    (platTipus llenguado_amb_lima peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori salmo_grillat dimarts)
    (platObligatori parrillada_verdures dijous)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories sopa_verdures) 480)
    (= (calories brocoli_allada) 360)
    (= (calories crema_de_carxofa) 320)
    (= (calories raviolis_ricotta) 680)
    (= (calories penne_arrabiata) 720)
    (= (calories amanida_de_cogombre) 260)
    (= (calories escalivada_verdures) 350)
    (= (calories sopa_miso) 500)
    (= (calories amanida_fasols) 560)
    (= (calories sopa_de_galets) 470)
    (= (calories sopa_de_peix) 520)
    (= (calories salmo_grillat) 780)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories xai_rostit) 1000)
    (= (calories parrillada_verdures) 550)
    (= (calories sopa_de_pedra) 500)
    (= (calories turbot_planxa) 790)
    (= (calories sopa_ceba) 450)
    (= (calories llenguado_amb_lima) 750)
    (= (preu amanida_de_tomaquet) 3)
    (= (preu sopa_verdures) 4)
    (= (preu brocoli_allada) 3)
    (= (preu crema_de_carxofa) 3)
    (= (preu raviolis_ricotta) 5)
    (= (preu penne_arrabiata) 5)
    (= (preu amanida_de_cogombre) 3)
    (= (preu escalivada_verdures) 3)
    (= (preu sopa_miso) 5)
    (= (preu amanida_fasols) 4)
    (= (preu sopa_de_galets) 4)
    (= (preu sopa_de_peix) 6)
    (= (preu salmo_grillat) 9)
    (= (preu botifarra_a_la_planxa) 7)
    (= (preu xai_rostit) 9)
    (= (preu parrillada_verdures) 5)
    (= (preu sopa_de_pedra) 5)
    (= (preu turbot_planxa) 8)
    (= (preu sopa_ceba) 4)
    (= (preu llenguado_amb_lima) 8)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )