(define (problem menuext5b-tc2)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_asiatica hummus tallarins_carbonara amanida_fasols escalivada_verdures raviolis_ricotta cigrons_saltejats truita_potatge gnocchi_pesto sopa_verdures - primer
llenguado_amb_lima truita_verdures hamburguesa_mongeta pollastre_a_la_planxa crema_avellana sopa_de_pedra xai_rostit parrillada_verdures filet_porc cuixa_anec - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible sopa_verdures parrillada_verdures)
    (incompatible amanida_asiatica pollastre_a_la_planxa)
    (incompatible raviolis_ricotta crema_avellana)
    (incompatible truita_potatge llenguado_amb_lima)
    (incompatible amanida_asiatica llenguado_amb_lima)
    (incompatible escalivada_verdures xai_rostit)
    (incompatible cigrons_saltejats llenguado_amb_lima)
    (incompatible tallarins_carbonara crema_avellana)
    (platTipus amanida_asiatica amanida)
    (platTipus hummus llegums)
    (platTipus tallarins_carbonara pasta)
    (platTipus amanida_fasols llegums)
    (platTipus escalivada_verdures verdures)
    (platTipus raviolis_ricotta pasta)
    (platTipus cigrons_saltejats llegums)
    (platTipus truita_potatge llegums)
    (platTipus gnocchi_pesto pasta)
    (platTipus sopa_verdures sopa)
    (platTipus llenguado_amb_lima peix)
    (platTipus truita_verdures verdures)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus crema_avellana crema)
    (platTipus sopa_de_pedra sopa)
    (platTipus xai_rostit carn)
    (platTipus parrillada_verdures verdures)
    (platTipus filet_porc carn)
    (platTipus cuixa_anec carn)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori parrillada_verdures dimecres)
    (platObligatori truita_potatge divendres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_asiatica) 330)
    (= (calories hummus) 530)
    (= (calories tallarins_carbonara) 700)
    (= (calories amanida_fasols) 560)
    (= (calories escalivada_verdures) 350)
    (= (calories raviolis_ricotta) 680)
    (= (calories cigrons_saltejats) 570)
    (= (calories truita_potatge) 580)
    (= (calories gnocchi_pesto) 740)
    (= (calories sopa_verdures) 480)
    (= (calories llenguado_amb_lima) 750)
    (= (calories truita_verdures) 500)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories crema_avellana) 480)
    (= (calories sopa_de_pedra) 500)
    (= (calories xai_rostit) 1000)
    (= (calories parrillada_verdures) 550)
    (= (calories filet_porc) 900)
    (= (calories cuixa_anec) 980)
    (= (preu amanida_asiatica) 4)
    (= (preu hummus) 4)
    (= (preu tallarins_carbonara) 5)
    (= (preu amanida_fasols) 4)
    (= (preu escalivada_verdures) 3)
    (= (preu raviolis_ricotta) 5)
    (= (preu cigrons_saltejats) 4)
    (= (preu truita_potatge) 5)
    (= (preu gnocchi_pesto) 5)
    (= (preu sopa_verdures) 4)
    (= (preu llenguado_amb_lima) 8)
    (= (preu truita_verdures) 4)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu pollastre_a_la_planxa) 8)
    (= (preu crema_avellana) 5)
    (= (preu sopa_de_pedra) 5)
    (= (preu xai_rostit) 9)
    (= (preu parrillada_verdures) 5)
    (= (preu filet_porc) 8)
    (= (preu cuixa_anec) 9)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )