(define (problem menuext5b-tc5)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
truita_potatge brocoli_allada fajitas_verdures amanida_asiatica verdures_a_la_planxa crema_de_bolets sopa_de_peix crema_de_carabasso amanida_quinoa sopa_de_cigrons - primer
crema_de_xocolata botifarra_a_la_planxa truita_de_llenties orata_forno crema_de_limon hamburguesa_mongeta sopa_de_pedra estofat_soja filet_porc bacalla_amb_tomaquet - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible fajitas_verdures filet_porc)
    (incompatible fajitas_verdures botifarra_a_la_planxa)
    (incompatible crema_de_carabasso orata_forno)
    (incompatible crema_de_bolets filet_porc)
    (incompatible amanida_quinoa orata_forno)
    (incompatible amanida_asiatica orata_forno)
    (incompatible truita_potatge orata_forno)
    (incompatible amanida_asiatica filet_porc)
    (platTipus truita_potatge llegums)
    (platTipus brocoli_allada verdures)
    (platTipus fajitas_verdures verdures)
    (platTipus amanida_asiatica amanida)
    (platTipus verdures_a_la_planxa verdures)
    (platTipus crema_de_bolets crema)
    (platTipus sopa_de_peix sopa)
    (platTipus crema_de_carabasso crema)
    (platTipus amanida_quinoa amanida)
    (platTipus sopa_de_cigrons sopa)
    (platTipus crema_de_xocolata crema)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus truita_de_llenties llegums)
    (platTipus orata_forno peix)
    (platTipus crema_de_limon crema)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus sopa_de_pedra sopa)
    (platTipus estofat_soja llegums)
    (platTipus filet_porc carn)
    (platTipus bacalla_amb_tomaquet peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori brocoli_allada dimecres)
    (platObligatori sopa_de_peix dijous)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories truita_potatge) 580)
    (= (calories brocoli_allada) 360)
    (= (calories fajitas_verdures) 390)
    (= (calories amanida_asiatica) 330)
    (= (calories verdures_a_la_planxa) 300)
    (= (calories crema_de_bolets) 390)
    (= (calories sopa_de_peix) 450)
    (= (calories crema_de_carabasso) 330)
    (= (calories amanida_quinoa) 360)
    (= (calories sopa_de_cigrons) 530)
    (= (calories crema_de_xocolata) 450)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories truita_de_llenties) 620)
    (= (calories orata_forno) 800)
    (= (calories crema_de_limon) 430)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories sopa_de_pedra) 500)
    (= (calories estofat_soja) 700)
    (= (calories filet_porc) 900)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (preu truita_potatge) 5)
    (= (preu brocoli_allada) 3)
    (= (preu fajitas_verdures) 4)
    (= (preu amanida_asiatica) 4)
    (= (preu verdures_a_la_planxa) 3)
    (= (preu crema_de_bolets) 4)
    (= (preu sopa_de_peix) 5)
    (= (preu crema_de_carabasso) 2)
    (= (preu amanida_quinoa) 4)
    (= (preu sopa_de_cigrons) 4)
    (= (preu crema_de_xocolata) 5)
    (= (preu botifarra_a_la_planxa) 7)
    (= (preu truita_de_llenties) 5)
    (= (preu orata_forno) 8)
    (= (preu crema_de_limon) 4)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu sopa_de_pedra) 5)
    (= (preu estofat_soja) 5)
    (= (preu filet_porc) 8)
    (= (preu bacalla_amb_tomaquet) 7)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )