(define (problem menuext5b-tc4)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
amanida_catalana amanida_fasols macarrons_forn sopa_de_peix cigrons_saltejats brocoli_allada crema_de_carbassa crema_espinacs sopa_verdures crema_de_carabasso - primer
truita_de_llenties pollastre_a_la_planxa turbot_planxa estofat_soja faves_estofades crema_de_limon truita_verdures sopa_ajo sopa_de_peix orata_forno - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_espinacs pollastre_a_la_planxa)
    (incompatible brocoli_allada sopa_de_peix)
    (incompatible crema_de_carbassa turbot_planxa)
    (incompatible crema_espinacs orata_forno)
    (incompatible cigrons_saltejats orata_forno)
    (incompatible amanida_fasols turbot_planxa)
    (incompatible crema_espinacs turbot_planxa)
    (incompatible cigrons_saltejats turbot_planxa)
    (platTipus amanida_catalana amanida)
    (platTipus amanida_fasols llegums)
    (platTipus macarrons_forn pasta)
    (platTipus sopa_de_peix sopa)
    (platTipus cigrons_saltejats llegums)
    (platTipus brocoli_allada verdures)
    (platTipus crema_de_carbassa crema)
    (platTipus crema_espinacs crema)
    (platTipus sopa_verdures sopa)
    (platTipus crema_de_carabasso crema)
    (platTipus truita_de_llenties llegums)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus turbot_planxa peix)
    (platTipus estofat_soja llegums)
    (platTipus faves_estofades llegums)
    (platTipus crema_de_limon crema)
    (platTipus truita_verdures verdures)
    (platTipus sopa_ajo sopa)
    (platTipus orata_forno peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori turbot_planxa dijous)
    (platObligatori cigrons_saltejats dimecres)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories amanida_catalana) 300)
    (= (calories amanida_fasols) 560)
    (= (calories macarrons_forn) 650)
    (= (calories sopa_de_peix) 520)
    (= (calories cigrons_saltejats) 570)
    (= (calories brocoli_allada) 360)
    (= (calories crema_de_carbassa) 350)
    (= (calories crema_espinacs) 380)
    (= (calories sopa_verdures) 480)
    (= (calories crema_de_carabasso) 330)
    (= (calories truita_de_llenties) 620)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories turbot_planxa) 790)
    (= (calories estofat_soja) 700)
    (= (calories faves_estofades) 730)
    (= (calories crema_de_limon) 430)
    (= (calories truita_verdures) 500)
    (= (calories sopa_ajo) 490)
    (= (calories orata_forno) 800)
    (= (preu amanida_catalana) 4)
    (= (preu amanida_fasols) 4)
    (= (preu macarrons_forn) 4)
    (= (preu sopa_de_peix) 6)
    (= (preu cigrons_saltejats) 4)
    (= (preu brocoli_allada) 3)
    (= (preu crema_de_carbassa) 3)
    (= (preu crema_espinacs) 4)
    (= (preu sopa_verdures) 4)
    (= (preu crema_de_carabasso) 2)
    (= (preu truita_de_llenties) 5)
    (= (preu pollastre_a_la_planxa) 8)
    (= (preu turbot_planxa) 8)
    (= (preu estofat_soja) 5)
    (= (preu faves_estofades) 6)
    (= (preu crema_de_limon) 4)
    (= (preu truita_verdures) 4)
    (= (preu sopa_ajo) 4)
    (= (preu orata_forno) 8)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )