(define (problem menuext5b-tc1)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
sopa_de_peix sopa_de_marisc crema_de_bolets amanida_quinoa amanida_fasols escalivada_verdures crema_espinacs cigrons_saltejats amanida_de_tomaquet raviolis_ricotta - primer
salmo_grillat sopa_de_peix truita_de_llenties faves_estofades crema_catalana xai_rostit turbot_planxa wok_verdures hamburguesa_mongeta sopa_ajo - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_fasols turbot_planxa)
    (incompatible cigrons_saltejats salmo_grillat)
    (incompatible amanida_quinoa salmo_grillat)
    (incompatible sopa_de_peix wok_verdures)
    (incompatible amanida_fasols salmo_grillat)
    (incompatible crema_espinacs salmo_grillat)
    (incompatible escalivada_verdures xai_rostit)
    (incompatible amanida_de_tomaquet xai_rostit)
    (platTipus sopa_de_peix sopa)
    (platTipus sopa_de_marisc sopa)
    (platTipus crema_de_bolets crema)
    (platTipus amanida_quinoa amanida)
    (platTipus amanida_fasols llegums)
    (platTipus escalivada_verdures verdures)
    (platTipus crema_espinacs crema)
    (platTipus cigrons_saltejats llegums)
    (platTipus amanida_de_tomaquet amanida)
    (platTipus raviolis_ricotta pasta)
    (platTipus salmo_grillat peix)
    (platTipus truita_de_llenties llegums)
    (platTipus faves_estofades llegums)
    (platTipus crema_catalana crema)
    (platTipus xai_rostit carn)
    (platTipus turbot_planxa peix)
    (platTipus wok_verdures verdures)
    (platTipus hamburguesa_mongeta llegums)
    (platTipus sopa_ajo sopa)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori crema_espinacs divendres)
    (platObligatori amanida_quinoa dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories sopa_de_peix) 520)
    (= (calories sopa_de_marisc) 560)
    (= (calories crema_de_bolets) 390)
    (= (calories amanida_quinoa) 360)
    (= (calories amanida_fasols) 560)
    (= (calories escalivada_verdures) 350)
    (= (calories crema_espinacs) 380)
    (= (calories cigrons_saltejats) 570)
    (= (calories amanida_de_tomaquet) 270)
    (= (calories raviolis_ricotta) 680)
    (= (calories salmo_grillat) 780)
    (= (calories truita_de_llenties) 620)
    (= (calories faves_estofades) 730)
    (= (calories crema_catalana) 440)
    (= (calories xai_rostit) 1000)
    (= (calories turbot_planxa) 790)
    (= (calories wok_verdures) 540)
    (= (calories hamburguesa_mongeta) 670)
    (= (calories sopa_ajo) 490)
    (= (preu sopa_de_peix) 6)
    (= (preu sopa_de_marisc) 6)
    (= (preu crema_de_bolets) 4)
    (= (preu amanida_quinoa) 4)
    (= (preu amanida_fasols) 4)
    (= (preu escalivada_verdures) 3)
    (= (preu crema_espinacs) 4)
    (= (preu cigrons_saltejats) 4)
    (= (preu amanida_de_tomaquet) 3)
    (= (preu raviolis_ricotta) 5)
    (= (preu salmo_grillat) 9)
    (= (preu truita_de_llenties) 5)
    (= (preu faves_estofades) 6)
    (= (preu crema_catalana) 4)
    (= (preu xai_rostit) 9)
    (= (preu turbot_planxa) 8)
    (= (preu wok_verdures) 4)
    (= (preu hamburguesa_mongeta) 5)
    (= (preu sopa_ajo) 4)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )