(define (problem menuext5b-tc3)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
penne_arrabiata estofat_llenties escalivada_verdures tallarins_carbonara truita_potatge crema_espinacs crema_de_carxofa amanida_catalana sopa_de_cigrons sopa_verdures - primer
sopa_de_pedra truita_verdures sopa_de_galets crema_taronja estofat_soja truita_de_llenties sopa_ajo salmo_grillat crema_de_limon parrillada_verdures - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible crema_espinacs salmo_grillat)
    (incompatible penne_arrabiata crema_taronja)
    (incompatible truita_potatge salmo_grillat)
    (incompatible crema_de_carxofa salmo_grillat)
    (incompatible sopa_de_cigrons parrillada_verdures)
    (incompatible tallarins_carbonara crema_taronja)
    (incompatible estofat_llenties salmo_grillat)
    (incompatible tallarins_carbonara crema_de_limon)
    (platTipus penne_arrabiata pasta)
    (platTipus estofat_llenties llegums)
    (platTipus escalivada_verdures verdures)
    (platTipus tallarins_carbonara pasta)
    (platTipus truita_potatge llegums)
    (platTipus crema_espinacs crema)
    (platTipus crema_de_carxofa crema)
    (platTipus amanida_catalana amanida)
    (platTipus sopa_de_cigrons sopa)
    (platTipus sopa_verdures sopa)
    (platTipus sopa_de_pedra sopa)
    (platTipus truita_verdures verdures)
    (platTipus sopa_de_galets sopa)
    (platTipus crema_taronja crema)
    (platTipus estofat_soja llegums)
    (platTipus truita_de_llenties llegums)
    (platTipus sopa_ajo sopa)
    (platTipus salmo_grillat peix)
    (platTipus crema_de_limon crema)
    (platTipus parrillada_verdures verdures)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori crema_taronja divendres)
    (platObligatori estofat_llenties dilluns)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories penne_arrabiata) 720)
    (= (calories estofat_llenties) 600)
    (= (calories escalivada_verdures) 350)
    (= (calories tallarins_carbonara) 700)
    (= (calories truita_potatge) 580)
    (= (calories crema_espinacs) 380)
    (= (calories crema_de_carxofa) 320)
    (= (calories amanida_catalana) 300)
    (= (calories sopa_de_cigrons) 530)
    (= (calories sopa_verdures) 480)
    (= (calories sopa_de_pedra) 500)
    (= (calories truita_verdures) 500)
    (= (calories sopa_de_galets) 470)
    (= (calories crema_taronja) 410)
    (= (calories estofat_soja) 700)
    (= (calories truita_de_llenties) 620)
    (= (calories sopa_ajo) 490)
    (= (calories salmo_grillat) 780)
    (= (calories crema_de_limon) 430)
    (= (calories parrillada_verdures) 550)
    (= (preu penne_arrabiata) 5)
    (= (preu estofat_llenties) 5)
    (= (preu escalivada_verdures) 3)
    (= (preu tallarins_carbonara) 5)
    (= (preu truita_potatge) 5)
    (= (preu crema_espinacs) 4)
    (= (preu crema_de_carxofa) 3)
    (= (preu amanida_catalana) 4)
    (= (preu sopa_de_cigrons) 4)
    (= (preu sopa_verdures) 4)
    (= (preu sopa_de_pedra) 5)
    (= (preu truita_verdures) 4)
    (= (preu sopa_de_galets) 4)
    (= (preu crema_taronja) 4)
    (= (preu estofat_soja) 5)
    (= (preu truita_de_llenties) 5)
    (= (preu sopa_ajo) 4)
    (= (preu salmo_grillat) 9)
    (= (preu crema_de_limon) 4)
    (= (preu parrillada_verdures) 5)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )