(define (problem menuext5b-tc2)
          (:domain menuext5b)

          (:objects
            dilluns dimarts dimecres dijous divendres DummyD - dia
estofat_llenties sopa_de_marisc crema_de_carxofa amanida_asiatica penne_arrabiata sopa_de_peix raviolis_ricotta amanida_quinoa hummus escalivada_verdures - primer
botifarra_a_la_planxa bacalla_amb_tomaquet pollastre_a_la_planxa sopa_de_pedra sopa_de_peix faves_estofades sopa_de_galets orata_forno crema_taronja turbot_planxa - segon
DummyT amanida carn crema llegums pasta peix sopa verdures - tipus
          )

          (:init
            (incompatible amanida_quinoa bacalla_amb_tomaquet)
    (incompatible escalivada_verdures sopa_de_pedra)
    (incompatible amanida_asiatica turbot_planxa)
    (incompatible estofat_llenties bacalla_amb_tomaquet)
    (incompatible escalivada_verdures sopa_de_peix)
    (incompatible crema_de_carxofa botifarra_a_la_planxa)
    (incompatible hummus bacalla_amb_tomaquet)
    (incompatible raviolis_ricotta crema_taronja)
    (platTipus estofat_llenties llegums)
    (platTipus sopa_de_marisc sopa)
    (platTipus crema_de_carxofa crema)
    (platTipus amanida_asiatica amanida)
    (platTipus penne_arrabiata pasta)
    (platTipus sopa_de_peix sopa)
    (platTipus raviolis_ricotta pasta)
    (platTipus amanida_quinoa amanida)
    (platTipus hummus llegums)
    (platTipus escalivada_verdures verdures)
    (platTipus botifarra_a_la_planxa carn)
    (platTipus bacalla_amb_tomaquet peix)
    (platTipus pollastre_a_la_planxa carn)
    (platTipus sopa_de_pedra sopa)
    (platTipus faves_estofades llegums)
    (platTipus sopa_de_galets sopa)
    (platTipus orata_forno peix)
    (platTipus crema_taronja crema)
    (platTipus turbot_planxa peix)
    (diaAnt DummyD dilluns)
    (diaAnt dilluns dimarts)
    (diaAnt dimarts dimecres)
    (diaAnt dimecres dijous)
    (diaAnt dijous divendres)
    (primerAsignat DummyD)
(segonAsignat  DummyD)
(diaPrimerTipus DummyD DummyT)
(diaSegonTipus  DummyD DummyT)
    (platObligatori amanida_quinoa dilluns)
    (platObligatori sopa_de_galets dimarts)
    (= (minCalories) 1000)
    (= (maxCalories) 1500)
    (= (calories estofat_llenties) 600)
    (= (calories sopa_de_marisc) 560)
    (= (calories crema_de_carxofa) 320)
    (= (calories amanida_asiatica) 330)
    (= (calories penne_arrabiata) 720)
    (= (calories sopa_de_peix) 520)
    (= (calories raviolis_ricotta) 680)
    (= (calories amanida_quinoa) 360)
    (= (calories hummus) 530)
    (= (calories escalivada_verdures) 350)
    (= (calories botifarra_a_la_planxa) 880)
    (= (calories bacalla_amb_tomaquet) 810)
    (= (calories pollastre_a_la_planxa) 940)
    (= (calories sopa_de_pedra) 500)
    (= (calories faves_estofades) 730)
    (= (calories sopa_de_galets) 470)
    (= (calories orata_forno) 800)
    (= (calories crema_taronja) 410)
    (= (calories turbot_planxa) 790)
    (= (preu estofat_llenties) 5)
    (= (preu sopa_de_marisc) 6)
    (= (preu crema_de_carxofa) 3)
    (= (preu amanida_asiatica) 4)
    (= (preu penne_arrabiata) 5)
    (= (preu sopa_de_peix) 6)
    (= (preu raviolis_ricotta) 5)
    (= (preu amanida_quinoa) 4)
    (= (preu hummus) 4)
    (= (preu escalivada_verdures) 3)
    (= (preu botifarra_a_la_planxa) 7)
    (= (preu bacalla_amb_tomaquet) 7)
    (= (preu pollastre_a_la_planxa) 8)
    (= (preu sopa_de_pedra) 5)
    (= (preu faves_estofades) 6)
    (= (preu sopa_de_galets) 4)
    (= (preu orata_forno) 8)
    (= (preu crema_taronja) 4)
    (= (preu turbot_planxa) 8)
    (= (costDiari) 0)
    (= (costTotal) 0)
          )

          (:goal
            (forall (?d - dia)
              (and (primerAsignat ?d) (segonAsignat ?d)))
          )
  (:metric minimize (costTotal))
        )