(define (problem menu-basicb-1)
        (:domain menubasicb)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  hummus amanida_asiatica amanida_catalana amanida_fasols crema_de_bolets crema_de_carxofa truita_potatge amanida_quinoa fajitas_verdures raviolis_ricotta amanida_de_tomaquet penne_arrabiata - primer
  filet_porc crema_de_limon crema_catalana crema_de_xocolata sopa_de_galets sopa_de_peix bacalla_amb_tomate turbot_planxa parrillada_verdures salmo_grillat truita_verdures estofat_cigrons - segon
)

        (:init
  (incompatible hummus bacalla_amb_tomate)
  (incompatible hummus turbot_planxa)
  (incompatible hummus salmo_grillat)
  (incompatible amanida_asiatica filet_porc)
  (incompatible amanida_asiatica bacalla_amb_tomate)
  (incompatible amanida_asiatica turbot_planxa)
  (incompatible amanida_asiatica salmo_grillat)
  (incompatible amanida_catalana filet_porc)
  (incompatible amanida_catalana bacalla_amb_tomate)
  (incompatible amanida_catalana turbot_planxa)
  (incompatible amanida_catalana salmo_grillat)
  (incompatible amanida_fasols bacalla_amb_tomate)
  (incompatible amanida_fasols turbot_planxa)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible crema_de_bolets filet_porc)
  (incompatible crema_de_bolets bacalla_amb_tomate)
  (incompatible crema_de_bolets turbot_planxa)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa bacalla_amb_tomate)
  (incompatible crema_de_carxofa turbot_planxa)
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible truita_potatge bacalla_amb_tomate)
  (incompatible truita_potatge turbot_planxa)
  (incompatible truita_potatge salmo_grillat)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa bacalla_amb_tomate)
  (incompatible amanida_quinoa turbot_planxa)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible fajitas_verdures filet_porc)
  (incompatible fajitas_verdures sopa_de_galets)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible raviolis_ricotta crema_de_limon)
  (incompatible raviolis_ricotta crema_catalana)
  (incompatible raviolis_ricotta crema_de_xocolata)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet bacalla_amb_tomate)
  (incompatible amanida_de_tomaquet turbot_planxa)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible penne_arrabiata crema_de_limon)
  (incompatible penne_arrabiata crema_catalana)
  (incompatible penne_arrabiata crema_de_xocolata)
        )

          ( :goal (forall (?d - dia) (diaAmbMenuAsignat ?d) ) )

      )