(define (problem menu-basicb-5)
        (:domain menubasicb)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  crema_de_carxofa escalivada_verdures amanida_de_cogombre verdures_a_la_planxa sopa_de_peix sopa_de_marisc crema_de_bolets amanida_de_tomaquet crema_de_carabasso penne_arrabiata fajitas_verdures estofat_llenties - primer
  estofat_cigrons llenguado_amb_lima botifarra_a_la_planxa wok_verdures cuixa_ànec crema_avellana sopa_ceba estofat_soja sopa_de_peix salmo_grillat tataki_verdures hamburguesa_mongeta - segon
)

        (:init
  (incompatible crema_de_carxofa llenguado_amb_lima)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa cuixa_ànec)
  (incompatible crema_de_carxofa salmo_grillat)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures cuixa_ànec)
  (incompatible escalivada_verdures sopa_ceba)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible amanida_de_cogombre llenguado_amb_lima)
  (incompatible amanida_de_cogombre botifarra_a_la_planxa)
  (incompatible amanida_de_cogombre cuixa_ànec)
  (incompatible amanida_de_cogombre salmo_grillat)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible sopa_de_peix wok_verdures)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible crema_de_bolets llenguado_amb_lima)
  (incompatible crema_de_bolets botifarra_a_la_planxa)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible amanida_de_tomaquet llenguado_amb_lima)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet cuixa_ànec)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible crema_de_carabasso llenguado_amb_lima)
  (incompatible crema_de_carabasso botifarra_a_la_planxa)
  (incompatible crema_de_carabasso cuixa_ànec)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible penne_arrabiata crema_avellana)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures cuixa_ànec)
  (incompatible fajitas_verdures sopa_ceba)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible estofat_llenties llenguado_amb_lima)
  (incompatible estofat_llenties salmo_grillat)
        )

          ( :goal (forall (?d - dia) (diaAmbMenuAsignat ?d) ) )

      )