(define (problem menu-basicb-2)
        (:domain menubasicb)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  sopa_miso crema_de_carxofa sopa_verdures penne_arrabiata crema_de_bolets amanida_catalana crema_de_carbassa cigrons_saltejats brocoli_allada sopa_de_peix verdures_a_la_planxa amanida_quinoa - primer
  sopa_de_galets estofat_soja pollastre_a_la_planxa crema_taronja crema_de_xocolata botifarra_a_la_planxa tataki_verdures xai_rostit faves_estofades turbot_planxa sopa_ceba crema_de_limon - segon
)

        (:init
  (incompatible sopa_miso tataki_verdures)
  (incompatible crema_de_carxofa pollastre_a_la_planxa)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa xai_rostit)
  (incompatible crema_de_carxofa turbot_planxa)
  (incompatible sopa_verdures tataki_verdures)
  (incompatible penne_arrabiata crema_taronja)
  (incompatible penne_arrabiata crema_de_xocolata)
  (incompatible penne_arrabiata crema_de_limon)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets botifarra_a_la_planxa)
  (incompatible crema_de_bolets xai_rostit)
  (incompatible crema_de_bolets turbot_planxa)
  (incompatible amanida_catalana pollastre_a_la_planxa)
  (incompatible amanida_catalana botifarra_a_la_planxa)
  (incompatible amanida_catalana xai_rostit)
  (incompatible amanida_catalana turbot_planxa)
  (incompatible crema_de_carbassa pollastre_a_la_planxa)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa xai_rostit)
  (incompatible crema_de_carbassa turbot_planxa)
  (incompatible cigrons_saltejats turbot_planxa)
  (incompatible brocoli_allada sopa_de_galets)
  (incompatible brocoli_allada pollastre_a_la_planxa)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible brocoli_allada xai_rostit)
  (incompatible brocoli_allada sopa_ceba)
  (incompatible sopa_de_peix tataki_verdures)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa xai_rostit)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible amanida_quinoa botifarra_a_la_planxa)
  (incompatible amanida_quinoa xai_rostit)
  (incompatible amanida_quinoa turbot_planxa)
        )

          ( :goal (forall (?d - dia) (diaAmbMenuAsignat ?d) ) )

      )