(define (problem menu-basicb-4)
        (:domain menubasicb)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia
  sopa_verdures hummus escalivada_verdures sopa_de_cigrons crema_de_carbassa verdures_amb_salsa truita_potatge crema_de_carabasso estofat_llenties crema_de_bolets amanida_de_tomaquet verdures_a_la_planxa - primer
  salmo_grillat hamburguesa_mongeta sopa_de_peix sopa_de_pedra cuixa_ànec botifarra_a_la_planxa sopa_ceba estofat_cigrons wok_verdures parrillada_verdures pollastre_a_la_planxa crema_de_limon - segon
)

        (:init
  (incompatible sopa_verdures wok_verdures)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible hummus salmo_grillat)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible escalivada_verdures sopa_de_pedra)
  (incompatible escalivada_verdures cuixa_ànec)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures sopa_ceba)
  (incompatible escalivada_verdures pollastre_a_la_planxa)
  (incompatible sopa_de_cigrons wok_verdures)
  (incompatible sopa_de_cigrons parrillada_verdures)
  (incompatible crema_de_carbassa salmo_grillat)
  (incompatible crema_de_carbassa cuixa_ànec)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa pollastre_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_ceba)
  (incompatible verdures_amb_salsa pollastre_a_la_planxa)
  (incompatible truita_potatge salmo_grillat)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible crema_de_carabasso cuixa_ànec)
  (incompatible crema_de_carabasso botifarra_a_la_planxa)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_bolets cuixa_ànec)
  (incompatible crema_de_bolets botifarra_a_la_planxa)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible amanida_de_tomaquet salmo_grillat)
  (incompatible amanida_de_tomaquet cuixa_ànec)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
        )

          ( :goal (forall (?d - dia) (diaAmbMenuAsignat ?d) ) )

      )