      (define (problem menu-ext2b-4)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  crema_de_carxofa amanida_de_tomaquet estofat_llenties escalivada_verdures sopa_de_cigrons croquetes_carn crema_de_carbassa verdures_a_la_planxa amanida_de_cogombre macarrons_forn ceviche_tonyina sopa_de_peix - primer
  truita_verdures estofat_cigrons tataki_verdures bacalla_amb_tomate pennes_amb_pesto sopa_de_peix sopa_de_pedra truita_de_llenties sopa_de_galets crema_de_limon salmo_grillat amanida_de_espinacs - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible crema_de_carxofa bacalla_amb_tomate)
      (incompatible crema_de_carxofa salmo_grillat)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet salmo_grillat)
      (incompatible estofat_llenties bacalla_amb_tomate)
      (incompatible estofat_llenties pennes_amb_pesto)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible sopa_de_cigrons truita_verdures)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons pennes_amb_pesto)
      (incompatible croquetes_carn truita_verdures)
      (incompatible croquetes_carn tataki_verdures)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible croquetes_carn sopa_de_galets)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible verdures_a_la_planxa sopa_de_pedra)
      (incompatible verdures_a_la_planxa sopa_de_galets)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn amanida_de_espinacs)
      (incompatible ceviche_tonyina crema_de_limon)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (platTipus crema_de_carxofa crema)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus estofat_llenties llegums)
      (platTipus escalivada_verdures verdures)
      (platTipus sopa_de_cigrons sopa)
      (platTipus croquetes_carn carn)
      (platTipus crema_de_carbassa crema)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus amanida_de_cogombre amanida)
      (platTipus macarrons_forn pasta)
      (platTipus ceviche_tonyina peix)
      (platTipus sopa_de_peix sopa)
      (platTipus truita_verdures verdures)
      (platTipus estofat_cigrons llegums)
      (platTipus tataki_verdures verdures)
      (platTipus bacalla_amb_tomate peix)
      (platTipus pennes_amb_pesto pasta)
      (platTipus sopa_de_peix sopa)
      (platTipus sopa_de_pedra sopa)
      (platTipus truita_de_llenties llegums)
      (platTipus sopa_de_galets sopa)
      (platTipus crema_de_limon crema)
      (platTipus salmo_grillat peix)
      (platTipus amanida_de_espinacs amanida)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )