(define (problem menu-ext2b-1)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  amanida_de_tomaquet tallarins_carbonara crema_de_carxofa crema_de_bolets estofat_llenties macarrons_forn crema_de_carabasso raviolis_ricotta amanida_quinoa penne_arrabiata hummus truita_potatge - primer
  sopa_de_peix truita_verdures llenguado_amb_lima curry_verdures filet_porc sopa_de_galets crema_taronja hamburguesa_mongeta truita_de_llenties tataki_verdures xai_rostit estofat_cigrons - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible amanida_de_tomaquet llenguado_amb_lima)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet xai_rostit)
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible crema_de_carxofa llenguado_amb_lima)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa xai_rostit)
  (incompatible crema_de_bolets llenguado_amb_lima)
  (incompatible crema_de_bolets filet_porc)
  (incompatible crema_de_bolets xai_rostit)
  (incompatible estofat_llenties llenguado_amb_lima)
  (incompatible macarrons_forn crema_taronja)
  (incompatible crema_de_carabasso llenguado_amb_lima)
  (incompatible crema_de_carabasso filet_porc)
  (incompatible crema_de_carabasso xai_rostit)
  (incompatible raviolis_ricotta crema_taronja)
  (incompatible amanida_quinoa llenguado_amb_lima)
  (incompatible amanida_quinoa filet_porc)
  (incompatible amanida_quinoa xai_rostit)
  (incompatible penne_arrabiata crema_taronja)
  (incompatible hummus llenguado_amb_lima)
  (incompatible truita_potatge llenguado_amb_lima)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus tallarins_carbonara pasta)
  (platTipus crema_de_carxofa crema)
  (platTipus crema_de_bolets crema)
  (platTipus estofat_llenties llegums)
  (platTipus macarrons_forn pasta)
  (platTipus crema_de_carabasso crema)
  (platTipus raviolis_ricotta pasta)
  (platTipus amanida_quinoa amanida)
  (platTipus penne_arrabiata pasta)
  (platTipus hummus llegums)
  (platTipus truita_potatge llegums)
  (platTipus sopa_de_peix sopa)
  (platTipus truita_verdures verdures)
  (platTipus llenguado_amb_lima peix)
  (platTipus curry_verdures verdures)
  (platTipus filet_porc carn)
  (platTipus sopa_de_galets sopa)
  (platTipus crema_taronja crema)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus truita_de_llenties llegums)
  (platTipus tataki_verdures verdures)
  (platTipus xai_rostit carn)
  (platTipus estofat_cigrons llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )