      (define (problem menu-ext2b-5)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  verdures_a_la_planxa cigrons_saltejats macarrons_forn botifarra_brasa tallarins_carbonara amanida_de_tomaquet amanida_catalana escalivada_verdures crema_de_carbassa amanida_de_cogombre sopa_de_marisc ceviche_tonyina - primer
  bacalla_amb_tomate sopa_de_peix crema_de_limon tortellinis_carne amanida_de_espinacs sopa_de_galets faves_estofades espaguetis_marisc crema_de_xocolata estofat_cigrons xai_rostit tataki_verdures - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible verdures_a_la_planxa sopa_de_galets)
      (incompatible verdures_a_la_planxa xai_rostit)
      (incompatible cigrons_saltejats bacalla_amb_tomate)
      (incompatible cigrons_saltejats tortellinis_carne)
      (incompatible cigrons_saltejats espaguetis_marisc)
      (incompatible macarrons_forn crema_de_limon)
      (incompatible macarrons_forn amanida_de_espinacs)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa tataki_verdures)
      (incompatible tallarins_carbonara crema_de_limon)
      (incompatible tallarins_carbonara amanida_de_espinacs)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (incompatible amanida_de_tomaquet bacalla_amb_tomate)
      (incompatible amanida_de_tomaquet xai_rostit)
      (incompatible amanida_catalana bacalla_amb_tomate)
      (incompatible amanida_catalana xai_rostit)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible crema_de_carbassa bacalla_amb_tomate)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible sopa_de_marisc tortellinis_carne)
      (incompatible sopa_de_marisc espaguetis_marisc)
      (incompatible sopa_de_marisc tataki_verdures)
      (incompatible ceviche_tonyina crema_de_limon)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible ceviche_tonyina xai_rostit)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus cigrons_saltejats llegums)
      (platTipus macarrons_forn pasta)
      (platTipus botifarra_brasa carn)
      (platTipus tallarins_carbonara pasta)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus amanida_catalana amanida)
      (platTipus escalivada_verdures verdures)
      (platTipus crema_de_carbassa crema)
      (platTipus amanida_de_cogombre amanida)
      (platTipus sopa_de_marisc sopa)
      (platTipus ceviche_tonyina peix)
      (platTipus bacalla_amb_tomate peix)
      (platTipus sopa_de_peix sopa)
      (platTipus crema_de_limon crema)
      (platTipus tortellinis_carne pasta)
      (platTipus amanida_de_espinacs amanida)
      (platTipus sopa_de_galets sopa)
      (platTipus faves_estofades llegums)
      (platTipus espaguetis_marisc pasta)
      (platTipus crema_de_xocolata crema)
      (platTipus estofat_cigrons llegums)
      (platTipus xai_rostit carn)
      (platTipus tataki_verdures verdures)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )