(define (problem menu-ext2b-4)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_de_marisc amanida_catalana brocoli_allada crema_de_bolets verdures_a_la_planxa sopa_verdures crema_espinacs sopa_miso raviolis_ricotta macarrons_forn amanida_quinoa crema_de_carabasso - primer
  sopa_ajo sopa_de_galets crema_de_limon orata_forno hamburguesa_mongeta salmo_grillat parrillada_verdures pollastre_a_la_planxa truita_verdures truita_de_llenties tataki_verdures llenguado_amb_lima - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc truita_verdures)
  (incompatible sopa_de_marisc tataki_verdures)
  (incompatible amanida_catalana orata_forno)
  (incompatible amanida_catalana salmo_grillat)
  (incompatible amanida_catalana pollastre_a_la_planxa)
  (incompatible amanida_catalana llenguado_amb_lima)
  (incompatible brocoli_allada sopa_ajo)
  (incompatible brocoli_allada sopa_de_galets)
  (incompatible brocoli_allada pollastre_a_la_planxa)
  (incompatible crema_de_bolets orata_forno)
  (incompatible crema_de_bolets salmo_grillat)
  (incompatible crema_de_bolets pollastre_a_la_planxa)
  (incompatible crema_de_bolets llenguado_amb_lima)
  (incompatible verdures_a_la_planxa sopa_ajo)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa pollastre_a_la_planxa)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible sopa_verdures tataki_verdures)
  (incompatible crema_espinacs orata_forno)
  (incompatible crema_espinacs salmo_grillat)
  (incompatible crema_espinacs pollastre_a_la_planxa)
  (incompatible crema_espinacs llenguado_amb_lima)
  (incompatible sopa_miso parrillada_verdures)
  (incompatible sopa_miso truita_verdures)
  (incompatible sopa_miso tataki_verdures)
  (incompatible raviolis_ricotta crema_de_limon)
  (incompatible macarrons_forn crema_de_limon)
  (incompatible amanida_quinoa orata_forno)
  (incompatible amanida_quinoa salmo_grillat)
  (incompatible amanida_quinoa pollastre_a_la_planxa)
  (incompatible amanida_quinoa llenguado_amb_lima)
  (incompatible crema_de_carabasso orata_forno)
  (incompatible crema_de_carabasso salmo_grillat)
  (incompatible crema_de_carabasso pollastre_a_la_planxa)
  (incompatible crema_de_carabasso llenguado_amb_lima)
  (platTipus sopa_de_marisc sopa)
  (platTipus amanida_catalana amanida)
  (platTipus brocoli_allada verdures)
  (platTipus crema_de_bolets crema)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus sopa_verdures sopa)
  (platTipus crema_espinacs crema)
  (platTipus sopa_miso sopa)
  (platTipus raviolis_ricotta pasta)
  (platTipus macarrons_forn pasta)
  (platTipus amanida_quinoa amanida)
  (platTipus crema_de_carabasso crema)
  (platTipus sopa_ajo sopa)
  (platTipus sopa_de_galets sopa)
  (platTipus crema_de_limon crema)
  (platTipus orata_forno peix)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus salmo_grillat peix)
  (platTipus parrillada_verdures verdures)
  (platTipus pollastre_a_la_planxa carn)
  (platTipus truita_verdures verdures)
  (platTipus truita_de_llenties llegums)
  (platTipus tataki_verdures verdures)
  (platTipus llenguado_amb_lima peix)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )