(define (problem menu-ext2b-2)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_miso sopa_verdures verdures_amb_salsa amanida_fasols amanida_de_cogombre estofat_llenties hummus escalivada_verdures amanida_asiatica verdures_a_la_planxa sopa_de_marisc sopa_de_peix - primer
  truita_verdures parrillada_verdures crema_taronja sopa_de_peix sopa_de_galets wok_verdures salmo_grillat cuixa_ànec crema_avellana filet_porc sopa_de_pedra sopa_ceba - segon
  amanida carn crema llegums peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_miso truita_verdures)
  (incompatible sopa_miso parrillada_verdures)
  (incompatible sopa_miso wok_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures wok_verdures)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa sopa_de_galets)
  (incompatible verdures_amb_salsa cuixa_ànec)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa sopa_ceba)
  (incompatible amanida_fasols salmo_grillat)
  (incompatible amanida_de_cogombre salmo_grillat)
  (incompatible amanida_de_cogombre cuixa_ànec)
  (incompatible amanida_de_cogombre filet_porc)
  (incompatible estofat_llenties salmo_grillat)
  (incompatible hummus salmo_grillat)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible escalivada_verdures sopa_de_galets)
  (incompatible escalivada_verdures cuixa_ànec)
  (incompatible escalivada_verdures filet_porc)
  (incompatible escalivada_verdures sopa_de_pedra)
  (incompatible escalivada_verdures sopa_ceba)
  (incompatible amanida_asiatica salmo_grillat)
  (incompatible amanida_asiatica cuixa_ànec)
  (incompatible amanida_asiatica filet_porc)
  (incompatible verdures_a_la_planxa sopa_de_peix)
  (incompatible verdures_a_la_planxa sopa_de_galets)
  (incompatible verdures_a_la_planxa cuixa_ànec)
  (incompatible verdures_a_la_planxa filet_porc)
  (incompatible verdures_a_la_planxa sopa_de_pedra)
  (incompatible verdures_a_la_planxa sopa_ceba)
  (incompatible sopa_de_marisc truita_verdures)
  (incompatible sopa_de_marisc parrillada_verdures)
  (incompatible sopa_de_marisc wok_verdures)
  (incompatible sopa_de_peix truita_verdures)
  (incompatible sopa_de_peix parrillada_verdures)
  (incompatible sopa_de_peix wok_verdures)
  (platTipus sopa_miso sopa)
  (platTipus sopa_verdures sopa)
  (platTipus verdures_amb_salsa verdures)
  (platTipus amanida_fasols llegums)
  (platTipus amanida_de_cogombre amanida)
  (platTipus estofat_llenties llegums)
  (platTipus hummus llegums)
  (platTipus escalivada_verdures verdures)
  (platTipus amanida_asiatica amanida)
  (platTipus verdures_a_la_planxa verdures)
  (platTipus sopa_de_marisc sopa)
  (platTipus sopa_de_peix sopa)
  (platTipus truita_verdures verdures)
  (platTipus parrillada_verdures verdures)
  (platTipus crema_taronja crema)
  (platTipus sopa_de_peix sopa)
  (platTipus sopa_de_galets sopa)
  (platTipus wok_verdures verdures)
  (platTipus salmo_grillat peix)
  (platTipus cuixa_ànec carn)
  (platTipus crema_avellana crema)
  (platTipus filet_porc carn)
  (platTipus sopa_de_pedra sopa)
  (platTipus sopa_ceba sopa)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )