      (define (problem menu-ext2b-2)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  botifarra_brasa llobarro_forn crema_de_carbassa amanida_de_cogombre escalivada_verdures amanida_catalana amanida_de_tomaquet sopa_de_cigrons crema_de_carxofa sopa_de_peix tataki_salmo carpaccio_vedella - primer
  sopa_de_pedra pollastre_a_la_planxa amanida_de_remolatxa crema_de_xocolata tataki_verdures amanida_cesar truita_de_llenties sopa_de_peix botifarra_a_la_planxa crema_de_limon parrillada_verdures tortellinis_carne - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible botifarra_brasa sopa_de_pedra)
      (incompatible botifarra_brasa tataki_verdures)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible llobarro_forn pollastre_a_la_planxa)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible crema_de_carbassa pollastre_a_la_planxa)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible amanida_de_cogombre pollastre_a_la_planxa)
      (incompatible amanida_de_cogombre botifarra_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures pollastre_a_la_planxa)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible escalivada_verdures botifarra_a_la_planxa)
      (incompatible amanida_catalana pollastre_a_la_planxa)
      (incompatible amanida_catalana botifarra_a_la_planxa)
      (incompatible amanida_de_tomaquet pollastre_a_la_planxa)
      (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
      (incompatible sopa_de_cigrons tataki_verdures)
      (incompatible sopa_de_cigrons parrillada_verdures)
      (incompatible sopa_de_cigrons tortellinis_carne)
      (incompatible crema_de_carxofa pollastre_a_la_planxa)
      (incompatible crema_de_carxofa botifarra_a_la_planxa)
      (incompatible sopa_de_peix tataki_verdures)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix tortellinis_carne)
      (incompatible tataki_salmo pollastre_a_la_planxa)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible carpaccio_vedella sopa_de_pedra)
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible carpaccio_vedella parrillada_verdures)
      (platTipus botifarra_brasa carn)
      (platTipus llobarro_forn peix)
      (platTipus crema_de_carbassa crema)
      (platTipus amanida_de_cogombre amanida)
      (platTipus escalivada_verdures verdures)
      (platTipus amanida_catalana amanida)
      (platTipus amanida_de_tomaquet amanida)
      (platTipus sopa_de_cigrons sopa)
      (platTipus crema_de_carxofa crema)
      (platTipus sopa_de_peix sopa)
      (platTipus tataki_salmo peix)
      (platTipus carpaccio_vedella carn)
      (platTipus sopa_de_pedra sopa)
      (platTipus pollastre_a_la_planxa carn)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus crema_de_xocolata crema)
      (platTipus tataki_verdures verdures)
      (platTipus amanida_cesar amanida)
      (platTipus truita_de_llenties llegums)
      (platTipus sopa_de_peix sopa)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus crema_de_limon crema)
      (platTipus parrillada_verdures verdures)
      (platTipus tortellinis_carne pasta)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )