(define (problem menu-ext2b-5)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  tallarins_carbonara verdures_amb_salsa brocoli_allada crema_de_carbassa amanida_de_cogombre fajitas_verdures amanida_de_tomaquet escalivada_verdures amanida_fasols gnocchi_pesto estofat_llenties crema_de_carxofa - primer
  botifarra_a_la_planxa crema_taronja orata_forno sopa_de_peix parrillada_verdures turbot_planxa crema_de_limon estofat_soja crema_de_xocolata filet_porc truita_verdures faves_estofades - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible tallarins_carbonara crema_taronja)
  (incompatible tallarins_carbonara crema_de_limon)
  (incompatible tallarins_carbonara crema_de_xocolata)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible brocoli_allada sopa_de_peix)
  (incompatible brocoli_allada filet_porc)
  (incompatible crema_de_carbassa botifarra_a_la_planxa)
  (incompatible crema_de_carbassa orata_forno)
  (incompatible crema_de_carbassa turbot_planxa)
  (incompatible crema_de_carbassa filet_porc)
  (incompatible amanida_de_cogombre botifarra_a_la_planxa)
  (incompatible amanida_de_cogombre orata_forno)
  (incompatible amanida_de_cogombre turbot_planxa)
  (incompatible amanida_de_cogombre filet_porc)
  (incompatible fajitas_verdures botifarra_a_la_planxa)
  (incompatible fajitas_verdures sopa_de_peix)
  (incompatible fajitas_verdures filet_porc)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet orata_forno)
  (incompatible amanida_de_tomaquet turbot_planxa)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible escalivada_verdures filet_porc)
  (incompatible amanida_fasols orata_forno)
  (incompatible amanida_fasols turbot_planxa)
  (incompatible gnocchi_pesto crema_taronja)
  (incompatible gnocchi_pesto crema_de_limon)
  (incompatible gnocchi_pesto crema_de_xocolata)
  (incompatible estofat_llenties orata_forno)
  (incompatible estofat_llenties turbot_planxa)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible crema_de_carxofa orata_forno)
  (incompatible crema_de_carxofa turbot_planxa)
  (incompatible crema_de_carxofa filet_porc)
  (platTipus tallarins_carbonara pasta)
  (platTipus verdures_amb_salsa verdures)
  (platTipus brocoli_allada verdures)
  (platTipus crema_de_carbassa crema)
  (platTipus amanida_de_cogombre amanida)
  (platTipus fajitas_verdures verdures)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus escalivada_verdures verdures)
  (platTipus amanida_fasols llegums)
  (platTipus gnocchi_pesto pasta)
  (platTipus estofat_llenties llegums)
  (platTipus crema_de_carxofa crema)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus crema_taronja crema)
  (platTipus orata_forno peix)
  (platTipus sopa_de_peix sopa)
  (platTipus parrillada_verdures verdures)
  (platTipus turbot_planxa peix)
  (platTipus crema_de_limon crema)
  (platTipus estofat_soja llegums)
  (platTipus crema_de_xocolata crema)
  (platTipus filet_porc carn)
  (platTipus truita_verdures verdures)
  (platTipus faves_estofades llegums)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )