      (define (problem menu-ext2b-3)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  verdures_amb_salsa llobarro_forn verdures_a_la_planxa ceviche_tonyina crema_de_carabasso sopa_de_peix macarrons_forn hummus amanida_de_cogombre escalivada_verdures raviolis_ricotta sopa_de_marisc - primer
  amanida_de_remolatxa pennes_amb_pesto parrillada_verdures truita_verdures estofat_cigrons llenguado_amb_lima bacalla_amb_tomate salmo_grillat crema_de_xocolata amanida_cesar sopa_de_peix faves_estofades - segon
  amanida crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible verdures_amb_salsa sopa_de_peix)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible ceviche_tonyina crema_de_xocolata)
      (incompatible crema_de_carabasso llenguado_amb_lima)
      (incompatible crema_de_carabasso bacalla_amb_tomate)
      (incompatible crema_de_carabasso salmo_grillat)
      (incompatible sopa_de_peix pennes_amb_pesto)
      (incompatible sopa_de_peix parrillada_verdures)
      (incompatible sopa_de_peix truita_verdures)
      (incompatible macarrons_forn amanida_de_remolatxa)
      (incompatible macarrons_forn crema_de_xocolata)
      (incompatible macarrons_forn amanida_cesar)
      (incompatible hummus pennes_amb_pesto)
      (incompatible hummus llenguado_amb_lima)
      (incompatible hummus bacalla_amb_tomate)
      (incompatible hummus salmo_grillat)
      (incompatible amanida_de_cogombre llenguado_amb_lima)
      (incompatible amanida_de_cogombre bacalla_amb_tomate)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible raviolis_ricotta amanida_de_remolatxa)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible raviolis_ricotta amanida_cesar)
      (incompatible sopa_de_marisc pennes_amb_pesto)
      (incompatible sopa_de_marisc parrillada_verdures)
      (incompatible sopa_de_marisc truita_verdures)
      (platTipus verdures_amb_salsa verdures)
      (platTipus llobarro_forn peix)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus ceviche_tonyina peix)
      (platTipus crema_de_carabasso crema)
      (platTipus sopa_de_peix sopa)
      (platTipus macarrons_forn pasta)
      (platTipus hummus llegums)
      (platTipus amanida_de_cogombre amanida)
      (platTipus escalivada_verdures verdures)
      (platTipus raviolis_ricotta pasta)
      (platTipus sopa_de_marisc sopa)
      (platTipus amanida_de_remolatxa amanida)
      (platTipus pennes_amb_pesto pasta)
      (platTipus parrillada_verdures verdures)
      (platTipus truita_verdures verdures)
      (platTipus estofat_cigrons llegums)
      (platTipus llenguado_amb_lima peix)
      (platTipus bacalla_amb_tomate peix)
      (platTipus salmo_grillat peix)
      (platTipus crema_de_xocolata crema)
      (platTipus amanida_cesar amanida)
      (platTipus sopa_de_peix sopa)
      (platTipus faves_estofades llegums)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )