      (define (problem menu-ext2b-1)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  raviolis_ricotta carpaccio_vedella escalivada_verdures botifarra_brasa amanida_de_cogombre crema_de_carbassa estofat_llenties croquetes_carn tallarins_carbonara tataki_salmo verdures_a_la_planxa llobarro_forn - primer
  sopa_de_galets sopa_de_pedra tataki_verdures salmo_grillat botifarra_a_la_planxa crema_de_limon xai_rostit crema_de_xocolata sopa_de_peix parrillada_verdures crema_catalana amanida_de_remolatxa - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
      (incompatible raviolis_ricotta crema_de_limon)
      (incompatible raviolis_ricotta crema_de_xocolata)
      (incompatible raviolis_ricotta crema_catalana)
      (incompatible raviolis_ricotta amanida_de_remolatxa)
      (incompatible carpaccio_vedella sopa_de_galets)
      (incompatible carpaccio_vedella sopa_de_pedra)
      (incompatible carpaccio_vedella tataki_verdures)
      (incompatible carpaccio_vedella sopa_de_peix)
      (incompatible carpaccio_vedella parrillada_verdures)
      (incompatible escalivada_verdures sopa_de_galets)
      (incompatible escalivada_verdures sopa_de_pedra)
      (incompatible escalivada_verdures botifarra_a_la_planxa)
      (incompatible escalivada_verdures xai_rostit)
      (incompatible escalivada_verdures sopa_de_peix)
      (incompatible botifarra_brasa sopa_de_galets)
      (incompatible botifarra_brasa sopa_de_pedra)
      (incompatible botifarra_brasa tataki_verdures)
      (incompatible botifarra_brasa sopa_de_peix)
      (incompatible botifarra_brasa parrillada_verdures)
      (incompatible amanida_de_cogombre salmo_grillat)
      (incompatible amanida_de_cogombre botifarra_a_la_planxa)
      (incompatible amanida_de_cogombre xai_rostit)
      (incompatible crema_de_carbassa salmo_grillat)
      (incompatible crema_de_carbassa botifarra_a_la_planxa)
      (incompatible crema_de_carbassa xai_rostit)
      (incompatible estofat_llenties salmo_grillat)
      (incompatible croquetes_carn sopa_de_galets)
      (incompatible croquetes_carn sopa_de_pedra)
      (incompatible croquetes_carn tataki_verdures)
      (incompatible croquetes_carn sopa_de_peix)
      (incompatible croquetes_carn parrillada_verdures)
      (incompatible tallarins_carbonara crema_de_limon)
      (incompatible tallarins_carbonara crema_de_xocolata)
      (incompatible tallarins_carbonara crema_catalana)
      (incompatible tallarins_carbonara amanida_de_remolatxa)
      (incompatible tataki_salmo botifarra_a_la_planxa)
      (incompatible tataki_salmo crema_de_limon)
      (incompatible tataki_salmo xai_rostit)
      (incompatible tataki_salmo crema_de_xocolata)
      (incompatible tataki_salmo crema_catalana)
      (incompatible verdures_a_la_planxa sopa_de_galets)
      (incompatible verdures_a_la_planxa sopa_de_pedra)
      (incompatible verdures_a_la_planxa botifarra_a_la_planxa)
      (incompatible verdures_a_la_planxa xai_rostit)
      (incompatible verdures_a_la_planxa sopa_de_peix)
      (incompatible llobarro_forn botifarra_a_la_planxa)
      (incompatible llobarro_forn crema_de_limon)
      (incompatible llobarro_forn xai_rostit)
      (incompatible llobarro_forn crema_de_xocolata)
      (incompatible llobarro_forn crema_catalana)
      (platTipus raviolis_ricotta pasta)
      (platTipus carpaccio_vedella carn)
      (platTipus escalivada_verdures verdures)
      (platTipus botifarra_brasa carn)
      (platTipus amanida_de_cogombre amanida)
      (platTipus crema_de_carbassa crema)
      (platTipus estofat_llenties llegums)
      (platTipus croquetes_carn carn)
      (platTipus tallarins_carbonara pasta)
      (platTipus tataki_salmo peix)
      (platTipus verdures_a_la_planxa verdures)
      (platTipus llobarro_forn peix)
      (platTipus sopa_de_galets sopa)
      (platTipus sopa_de_pedra sopa)
      (platTipus tataki_verdures verdures)
      (platTipus salmo_grillat peix)
      (platTipus botifarra_a_la_planxa carn)
      (platTipus crema_de_limon crema)
      (platTipus xai_rostit carn)
      (platTipus crema_de_xocolata crema)
      (platTipus sopa_de_peix sopa)
      (platTipus parrillada_verdures verdures)
      (platTipus crema_catalana crema)
      (platTipus amanida_de_remolatxa amanida)
      (diaAnt DummyD dilluns)
      (diaAnt dilluns dimarts)
      (diaAnt dimarts dimecres)
      (diaAnt dimecres dijous)
      (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )