(define (problem menu-ext2b-3)
        (:domain menuext2b)

          (:objects
  dilluns dimarts dimecres dijous divendres - dia DummyD - dia
  sopa_verdures crema_de_carxofa verdures_amb_salsa amanida_de_tomaquet brocoli_allada raviolis_ricotta amanida_asiatica amanida_de_cogombre hummus truita_potatge amanida_catalana escalivada_verdures - primer
  wok_verdures estofat_soja parrillada_verdures sopa_de_peix sopa_de_pedra filet_porc llenguado_amb_lima hamburguesa_mongeta sopa_de_galets botifarra_a_la_planxa crema_de_limon truita_verdures - segon
  amanida carn crema llegums pasta peix sopa verdures DummyT - tipus
)

        (:init
  (incompatible sopa_verdures wok_verdures)
  (incompatible sopa_verdures parrillada_verdures)
  (incompatible sopa_verdures truita_verdures)
  (incompatible crema_de_carxofa filet_porc)
  (incompatible crema_de_carxofa llenguado_amb_lima)
  (incompatible crema_de_carxofa botifarra_a_la_planxa)
  (incompatible verdures_amb_salsa sopa_de_peix)
  (incompatible verdures_amb_salsa sopa_de_pedra)
  (incompatible verdures_amb_salsa filet_porc)
  (incompatible verdures_amb_salsa sopa_de_galets)
  (incompatible verdures_amb_salsa botifarra_a_la_planxa)
  (incompatible amanida_de_tomaquet filet_porc)
  (incompatible amanida_de_tomaquet llenguado_amb_lima)
  (incompatible amanida_de_tomaquet botifarra_a_la_planxa)
  (incompatible brocoli_allada sopa_de_peix)
  (incompatible brocoli_allada sopa_de_pedra)
  (incompatible brocoli_allada filet_porc)
  (incompatible brocoli_allada sopa_de_galets)
  (incompatible brocoli_allada botifarra_a_la_planxa)
  (incompatible raviolis_ricotta crema_de_limon)
  (incompatible amanida_asiatica filet_porc)
  (incompatible amanida_asiatica llenguado_amb_lima)
  (incompatible amanida_asiatica botifarra_a_la_planxa)
  (incompatible amanida_de_cogombre filet_porc)
  (incompatible amanida_de_cogombre llenguado_amb_lima)
  (incompatible amanida_de_cogombre botifarra_a_la_planxa)
  (incompatible hummus llenguado_amb_lima)
  (incompatible truita_potatge llenguado_amb_lima)
  (incompatible amanida_catalana filet_porc)
  (incompatible amanida_catalana llenguado_amb_lima)
  (incompatible amanida_catalana botifarra_a_la_planxa)
  (incompatible escalivada_verdures sopa_de_peix)
  (incompatible escalivada_verdures sopa_de_pedra)
  (incompatible escalivada_verdures filet_porc)
  (incompatible escalivada_verdures sopa_de_galets)
  (incompatible escalivada_verdures botifarra_a_la_planxa)
  (platTipus sopa_verdures sopa)
  (platTipus crema_de_carxofa crema)
  (platTipus verdures_amb_salsa verdures)
  (platTipus amanida_de_tomaquet amanida)
  (platTipus brocoli_allada verdures)
  (platTipus raviolis_ricotta pasta)
  (platTipus amanida_asiatica amanida)
  (platTipus amanida_de_cogombre amanida)
  (platTipus hummus llegums)
  (platTipus truita_potatge llegums)
  (platTipus amanida_catalana amanida)
  (platTipus escalivada_verdures verdures)
  (platTipus wok_verdures verdures)
  (platTipus estofat_soja llegums)
  (platTipus parrillada_verdures verdures)
  (platTipus sopa_de_peix sopa)
  (platTipus sopa_de_pedra sopa)
  (platTipus filet_porc carn)
  (platTipus llenguado_amb_lima peix)
  (platTipus hamburguesa_mongeta llegums)
  (platTipus sopa_de_galets sopa)
  (platTipus botifarra_a_la_planxa carn)
  (platTipus crema_de_limon crema)
  (platTipus truita_verdures verdures)
  (diaAnt DummyD dilluns)
  (diaAnt dilluns dimarts)
  (diaAnt dimarts dimecres)
  (diaAnt dimecres dijous)
  (diaAnt dijous divendres)
  (primerAsignat DummyD)
  (segonAsignat DummyD)
  (diaPrimerTipus DummyD DummyT)
  (diaSegonTipus DummyD DummyT)
        )

          (:goal (and
  (forall (?d - dia)
    (and (primerAsignat ?d) (segonAsignat ?d))
  )))

      )